openmrs/openmrs-module-radiology

omod/pom.xml

* fixes eclipse error:
Plugin execution not covered by lifecycle configuration:
org.openmrs.maven.plugins:maven-openmrs-plugin:1.0.1:initialize-module (execution: init, phase:initialize)

fix eclipse complaint about maven-openmrs-plugin

---

api/src/main/java/org/openmrs/module/radiology/DicomUtils.java
api/src/test/java/org/openmrs/module/radiology/DicomUtilsTest.java

* refactor getORCtype to return hl7 CommonOrderControl Enum
* refactor getTruncatedPriority to return hl7 CommonOrderPriority Enum
* use new hl7 package to create the hl7 ORM^O01 message
- fix invalid encoding value
- fix wrong line endings from \n to \r as defined by hl7 standard
- fix wrong hl7 version
- fix reversed patient name in message
- fill in datetime into datetime elements instead of date
- fix empty instructions passed as null
see https://issues.openmrs.org/browse/RAD-23

RAD-23 - Refactor DicomUtils.createHL7Message()

---

api/src/main/java/org/openmrs/module/radiology/Study.java
api/src/main/java/org/openmrs/module/radiology/impl/RadiologyServiceImpl.java

* set Study.scheduledStatus to SCHEDULED if order.startDate
is selected in RadiologyService only if no other scheduledStatus has been
chosen
see https://issues.openmrs.org/browse/RAD-54

RAD-54 Study.setup() overrides Study.scheduledStatus

---

api/src/main/resources/moduleApplicationContext.xml
omod/src/main/java/org/openmrs/module/radiology/web/controller/RadiologyOrderFormController.java
omod/src/main/resources/config.xml
omod/src/test/java/org/openmrs/module/radiology/test/RadiologyTestData.java
omod/src/test/java/org/openmrs/module/radiology/web/controller/RadiologyOrderFormControllerTest.java
pom.xml

* update openmrs-core dependency to 1.9.9 to be able to use Mockito @Mock in Tests
* add RadiologyOrderFormControllerTest using Mockito @Mock
* adapt moduleApplicationContext so that @Autowired in omod finds the
RadiologyService bean (adds logging advice via openmrs-core
serviceInterceptors)
* add needed services as members to RadiologyOrderFormController and
wire via @Autowired
see https://issues.openmrs.org/browse/RAD-64

RAD-64 Add RadiologyOrderFormControllerTest

---

api/src/main/java/org/openmrs/module/radiology/Utils.java
omod/src/main/java/org/openmrs/module/radiology/web/controller/RadiologyDashboardObsController.java
omod/src/main/java/org/openmrs/module/radiology/web/controller/RadiologyObsFormController.java
omod/src/main/resources/config.xml
omod/src/main/webapp/portlets/DashboardObsForm.jsp
omod/src/main/webapp/radiologyObsForm.jsp
omod/src/test/java/org/openmrs/module/radiology/web/controller/RadiologyObsFormControllerTest.java

* name global properties and Utils methods used to generate the dicom viewer
url more specific but also general hence "dicomViewerUrlBase", "dicomViewerLocalServerName"
without mentioning oviyam
* move dicom viewer url generation to Utils to reduce duplication in
controllers
* update global properties defaults to weasis and update descriptions
see https://issues.openmrs.org/browse/RAD-41

RAD-41 Change default DICOM web viewer to weasis

---

omod/src/test/java/org/openmrs/module/radiology/web/controller/RadiologyOrderFormControllerTest.java

* remove mock for RadiologyProperties which are not used anymore in RadiologyOrderFormController
see https://issues.openmrs.org/browse/RAD-73

Cleanup RadiologyOrderFormControllerTest after RAD-79

---

api/src/main/java/org/openmrs/module/radiology/RadiologyOrder.java
api/src/main/java/org/openmrs/module/radiology/RadiologyService.java
api/src/main/java/org/openmrs/module/radiology/db/RadiologyOrderDAO.java
api/src/main/java/org/openmrs/module/radiology/db/StudyDAO.java
api/src/main/java/org/openmrs/module/radiology/db/hibernate/RadiologyOrderDAOImpl.java
api/src/main/java/org/openmrs/module/radiology/db/hibernate/StudyDAOImpl.java
api/src/main/java/org/openmrs/module/radiology/impl/RadiologyServiceImpl.java
api/src/main/resources/RadiologyOrder.hbm.xml
api/src/main/resources/liquibase.xml
api/src/main/resources/moduleApplicationContext.xml
api/src/test/java/org/openmrs/module/radiology/RadiologyServiceTest.java
api/src/test/resources/org/openmrs/module/radiology/include/RadiologyServiceTestDataSet.xml
api/src/test/resources/test-hibernate.cfg.xml
omod/src/main/java/org/openmrs/module/radiology/web/controller/PortletsController.java
omod/src/main/java/org/openmrs/module/radiology/web/controller/RadiologyDashboardController.java
omod/src/main/java/org/openmrs/module/radiology/web/controller/RadiologyOrderFormController.java
omod/src/main/resources/config.xml
omod/src/test/java/org/openmrs/module/radiology/test/RadiologyTestData.java
omod/src/test/java/org/openmrs/module/radiology/web/controller/PortletsControllerTest.java
omod/src/test/java/org/openmrs/module/radiology/web/controller/RadiologyDashboardControllerTest.java
omod/src/test/java/org/openmrs/module/radiology/web/controller/RadiologyOrderFormControllerTest.java

* add RadiologyOrder java class
* add hibernate mapping RadiologyOrder.hbm.xml
* add liquibase changeset to create table radiology_order
* adapt RadiologyServiceTestDataSet.xml
* add mapping resource to api/test-hibernate.cfg.xml
* add RadiologyOrder.hbm.xml mappingFile to config.xml
* add methods to RadiologyService
- add saveRadiologyOrder(RadiologyOrder)
- add getRadiologyOrderByOrderId(Integer)
- add getRadiologyOrdersByPatient(Patient)
- add getRadiologyOrdersByPatients(List<Patient>)
- adapt getStudiesByOrders(List<Order>) ->
getStudiesByRadiologyOrders(List<RadiologyOrder>)
* adapt controllers to use new RadiologyService methods and
RadiologyOrder
see https://issues.openmrs.org/browse/RAD-82

RAD-82 Add class RadiologyOrder

---

api/src/main/java/org/openmrs/module/radiology/RadiologyOrder.java
api/src/main/java/org/openmrs/module/radiology/RadiologyService.java
api/src/main/java/org/openmrs/module/radiology/Study.java
api/src/main/java/org/openmrs/module/radiology/impl/RadiologyServiceImpl.java
api/src/test/java/org/openmrs/module/radiology/RadiologyOrderTest.java
api/src/test/java/org/openmrs/module/radiology/RadiologyServiceTest.java
api/src/test/java/org/openmrs/module/radiology/hl7/HL7GeneratorTest.java
api/src/test/java/org/openmrs/module/radiology/hl7/message/RadiologyORMO01Test.java
api/src/test/java/org/openmrs/module/radiology/hl7/segment/RadiologyOBRTest.java
api/src/test/java/org/openmrs/module/radiology/impl/RadiologyServiceImplTest.java
omod/src/main/java/org/openmrs/module/radiology/web/controller/RadiologyOrderFormController.java
omod/src/test/java/org/openmrs/module/radiology/test/RadiologyTestData.java
omod/src/test/java/org/openmrs/module/radiology/web/controller/RadiologyOrderFormControllerTest.java

* remove saveStudy from api
* make saveStudy a private method in RadiologyServiecImpl
* move tests of private RadiologyServiceImpl methods to
RadiologyServiceImplTest
* handle bi-directional associaton from RadiologyOrder to Study
in RadiologyOrder.setStudy()
* adjust RadiologyOrderFormController to changes
see https://issues.openmrs.org/browse/RAD-96

RAD-96 Save study with RadiologyOrder

---

api/src/main/java/org/openmrs/module/radiology/impl/RadiologyServiceImpl.java
api/src/test/java/org/openmrs/module/radiology/impl/RadiologyServiceImplTest.java

cleanup after RAD-101
* remove leftover rule for temporary folder "mwl" from RadiologyServiceImplTest
see https://issues.openmrs.org/browse/RAD-101

RAD-101 remove temporary folder from RadiologyServiceImplTest

---

omod/pom.xml
pom.xml

* remove maven-java-formatter-plugin excludes in omod,
since excluded files are already deleted from the repo
* reword comment in root pom about org.slf4j dependency

RAD-125 Clean root and omod pom

---

api/src/main/java/org/openmrs/module/radiology/RadiologyProperties.java
api/src/test/java/org/openmrs/module/radiology/RadiologyPropertiesComponentTest.java
omod/src/main/resources/config.xml
pom.xml

Edit getRadiologyConceptClassNames test to match the right GP
see https://issues.openmrs.org/browse/RAD-161

RAD-161 Use emr-api to manage properties

---

omod/src/main/java/org/openmrs/module/radiology/web/controller/RadiologyReportFormController.java
omod/src/main/webapp/localHeader.jsp
omod/src/main/webapp/portlets/orderSearch.jsp
omod/src/main/webapp/radiologyOrderForm.jsp
omod/src/main/webapp/radiologyReportForm.jsp
omod/src/main/webapp/resources/js/orderList.js
omod/src/test/java/org/openmrs/module/radiology/web/controller/RadiologyReportFormControllerTest.java

* split RadiologyReportFormController get request method in
one for new report and one for existing
* remove orderId from query params since radiologyReportId gives us this
info anyway
* bind radiologyOrder as hidden field in jsp so link to order is not
deleted on unclaim
see https://issues.openmrs.org/browse/RAD-170

RAD-168 Clean RadiologyReportFormConrtoller

---

api/src/main/java/org/openmrs/module/radiology/report/RadiologyReport.java
api/src/main/resources/RadiologyReport.hbm.xml
api/src/main/resources/liquibase.xml
api/src/test/resources/org/openmrs/module/radiology/include/RadiologyServiceComponentTestDataset.xml

update the database radiology_report
* column radiology_report_id
** rename to report_id
* column order_id
** add not null constraint (a report must not exist without order)
* column report_status
** shrink size to max enum of RadiologyReportStatus which is DISCONTINUED -> 12
** add not null constraint
* column principalResultsInterpreter_id
** rename to principal_results_interpreter
* column creator
** add not null constraint, defauts to '0'
* column creationDate
** rename to date_created
** convert type to datetime
** add not null constraint
* rename foreign key constraints to "tablename_columname_fk"
* remove setting dateCreated in RadiologyReport constructor since its
done by AuditableInterceptor
see https://issues.openmrs.org/browse/RAD-172

RAD-172 Clean radiology_report db

---

api/src/main/java/org/openmrs/module/radiology/report/RadiologyReport.java
api/src/test/java/org/openmrs/module/radiology/report/RadiologyReportTest.java
omod/src/test/java/org/openmrs/module/radiology/test/RadiologyTestData.java

* reduce visibility of no arg constructor which is only used by hibernate
* ensure creation of RadiologyReport only with complete RadiologyOrder
* remove RadiologyReportTest's of logic that is not implemented in
RadiologyReport
* add javadocs and tests
see https://issues.openmrs.org/browse/RAD-175

RAD-175 Prevent report creation of incomplete order

---

api/src/main/resources/RadiologyReport.hbm.xml
api/src/main/resources/liquibase.xml
api/src/test/resources/org/openmrs/module/radiology/include/RadiologyServiceComponentTestDataset.xml

since its a BaseOpenmrsObject RadiologyReport inherits it
we can thus store it and use its hashcode and equals implementation
see https://issues.openmrs.org/browse/RAD-177

RAD-177 Add uuid to radiology_report

---

pom.xml

* version 0.9.9 of reporting module was released, snapshot is no longer valid.
* fixes failed travis ci builds
see https://issues.openmrs.org/browse/RAD-178

RAD-178 Change reporting dependency to 0.9.9

---

api/src/main/java/org/openmrs/module/radiology/RadiologyOrder.java
api/src/main/java/org/openmrs/module/radiology/RadiologyService.java
api/src/main/java/org/openmrs/module/radiology/Study.java
api/src/main/java/org/openmrs/module/radiology/impl/RadiologyServiceImpl.java
api/src/test/java/org/openmrs/module/radiology/RadiologyOrderTest.java
api/src/test/java/org/openmrs/module/radiology/RadiologyServiceComponentTest.java
api/src/test/java/org/openmrs/module/radiology/StudyTest.java
omod/src/main/java/org/openmrs/module/radiology/web/controller/RadiologyOrderFormController.java
omod/src/main/webapp/radiologyOrderForm.jsp

* add isInProgress to Study
* add isInProgress and isInNotProgress to RadiologyOrder
* prevent discontinuation of radorder in API and web UI if in progress or completed
* remove isOrderActive in mav
* add isDiscontinuationAllowed to RadiologyOrder and use it jsp
see https://issues.openmrs.org/browse/RAD-144

RAD-144 RadiologyOrder can be discontinued if already performed

---

api/src/main/java/org/openmrs/module/radiology/DicomUtils.java
api/src/main/java/org/openmrs/module/radiology/hl7/HL7Utils.java
api/src/main/java/org/openmrs/module/radiology/hl7/message/RadiologyORMO01.java
api/src/main/java/org/openmrs/module/radiology/hl7/segment/RadiologyORC.java
api/src/test/java/org/openmrs/module/radiology/DicomUtilsComponentTest.java
api/src/test/java/org/openmrs/module/radiology/hl7/HL7UtilsTest.java
api/src/test/java/org/openmrs/module/radiology/hl7/message/RadiologyORMO01Test.java
api/src/test/java/org/openmrs/module/radiology/hl7/segment/RadiologyORCTest.java

* remove getCommonOrderPriorityFrom() in DicomUtils
* create method convertOrderUrgencyToCommonOrderPriority() in HL7Utils
* use new method in RadiologyORC segment directly, thus remove
parameter from RadiologyORMO01 constructor
see https://issues.openmrs.org/browse/RAD-195

RAD-195 Move getCommonOrderPriorityFrom to HL7Utils

---

api/src/main/java/org/openmrs/module/radiology/MwlStatus.java
api/src/main/java/org/openmrs/module/radiology/RadiologyService.java
api/src/main/java/org/openmrs/module/radiology/impl/RadiologyServiceImpl.java
omod/src/main/java/org/openmrs/module/radiology/web/controller/RadiologyOrderFormController.java
omod/src/test/java/org/openmrs/module/radiology/web/controller/RadiologyOrderFormControllerTest.java

return true on success of status == HL7_SEND_SUCCESS and false otherwise
makes client code (RadiologyOrderFormController) cleaner since no checks
for Study.mwlStatus are needed
see https://issues.openmrs.org/browse/RAD-196

RAD-196 RadiologyService.sendModalityWorklist return true or false

---

api/src/main/java/org/openmrs/module/radiology/DicomUtils.java
api/src/main/java/org/openmrs/module/radiology/MwlStatus.java
api/src/main/java/org/openmrs/module/radiology/Study.java
api/src/main/java/org/openmrs/module/radiology/impl/RadiologyServiceImpl.java
api/src/test/java/org/openmrs/module/radiology/DicomUtilsComponentTest.java
api/src/test/java/org/openmrs/module/radiology/RadiologyServiceComponentTest.java
api/src/test/java/org/openmrs/module/radiology/impl/RadiologyServiceImplComponentTest.java
api/src/test/resources/org/openmrs/module/radiology/include/RadiologyServiceComponentTestDataset.xml
omod/src/main/resources/messages.properties
omod/src/test/java/org/openmrs/module/radiology/web/controller/RadiologyOrderFormControllerTest.java

* remove non supported OrderRequest, keep only supported Save/Discontinue_Order
* change MwlStatus to only IN_SYNC and OUT_OF_SYNC
since all other MwlStatus do not give us additional information and just clutter
the code. by default a study is OUT_OF_SYNC since it is created in the
radiology module but not yet in the PACS DICOM MWL. once the hl7 order message
has been sent and the sending was successful we set the status to IN_SYNC.
see https://issues.openmrs.org/browse/RAD-198

RAD-198 Reduce OrderRequest and MwlStatus

---

api/src/main/java/org/openmrs/module/radiology/DicomUtils.java
api/src/main/java/org/openmrs/module/radiology/MwlStatus.java
api/src/main/java/org/openmrs/module/radiology/PerformedProcedureStepStatus.java
api/src/main/java/org/openmrs/module/radiology/ScheduledProcedureStepStatus.java
api/src/main/java/org/openmrs/module/radiology/hl7/CommonOrderOrderControl.java
tools/formatter/OpenMRSFormatter.xml

* force split of enums for every element on a separate line even
if the element is short
* exported openmrs formatter from eclipse Mars.2 release (4.5.2)
see https://issues.openmrs.org/browse/RAD-199

RAD-199 Formatter force split on enums

---

api/src/main/java/org/openmrs/module/radiology/DicomUtils.java
api/src/main/java/org/openmrs/module/radiology/hl7/util/DateTimeUtils.java
api/src/main/java/org/openmrs/module/radiology/hl7/v231/code/OrderControlElement.java
api/src/main/java/org/openmrs/module/radiology/hl7/v231/code/PriorityComponent.java
api/src/main/java/org/openmrs/module/radiology/hl7/v231/message/RadiologyORMO01.java
api/src/main/java/org/openmrs/module/radiology/hl7/v231/segment/RadiologyMSH.java
api/src/main/java/org/openmrs/module/radiology/hl7/v231/segment/RadiologyOBR.java
api/src/main/java/org/openmrs/module/radiology/hl7/v231/segment/RadiologyORC.java
api/src/main/java/org/openmrs/module/radiology/hl7/v231/segment/RadiologyPID.java
api/src/main/java/org/openmrs/module/radiology/hl7/v231/segment/RadiologyZDS.java
api/src/main/java/org/openmrs/module/radiology/hl7/v231/util/HL7Utils.java
api/src/main/java/org/openmrs/module/radiology/impl/RadiologyServiceImpl.java
api/src/test/java/org/openmrs/module/radiology/DicomUtilsComponentTest.java
api/src/test/java/org/openmrs/module/radiology/hl7/util/DateTimeUtilsTest.java
api/src/test/java/org/openmrs/module/radiology/hl7/v231/message/RadiologyORMO01Test.java
api/src/test/java/org/openmrs/module/radiology/hl7/v231/segment/RadiologyMSHTest.java
api/src/test/java/org/openmrs/module/radiology/hl7/v231/segment/RadiologyOBRTest.java
api/src/test/java/org/openmrs/module/radiology/hl7/v231/segment/RadiologyORCTest.java
api/src/test/java/org/openmrs/module/radiology/hl7/v231/segment/RadiologyPIDTest.java
api/src/test/java/org/openmrs/module/radiology/hl7/v231/segment/RadiologyZDSTest.java
api/src/test/java/org/openmrs/module/radiology/hl7/v231/util/HL7UtilsTest.java

* create subpackage hl7.v231 and move all version
specific classes beneath
* create subpackage hl7.v231.code and put
OrderControlElement and PriorityComponent in it.
* renamed above enums to stick to hl7 nomenclature
* create hl7.v231.util package and move HL7Utils in it
* move DateTimeUtils into hl7.util
see https://issues.openmrs.org/browse/RAD-205

RAD-205 Rearrange packages for hl7

---

api/src/main/java/org/openmrs/module/radiology/hl7/HL7Constants.java
api/src/main/java/org/openmrs/module/radiology/hl7/v231/message/RadiologyORMO01.java
api/src/main/java/org/openmrs/module/radiology/hl7/v231/segment/RadiologyMSH.java
api/src/test/java/org/openmrs/module/radiology/hl7/custommodel/v231/message/ORM_O01Test.java
api/src/test/java/org/openmrs/module/radiology/hl7/custommodel/v231/segment/ZDSTest.java
api/src/test/java/org/openmrs/module/radiology/hl7/v231/message/RadiologyORMO01Test.java
api/src/test/java/org/openmrs/module/radiology/hl7/v231/segment/RadiologyMSHTest.java
api/src/test/java/org/openmrs/module/radiology/hl7/v231/segment/RadiologyOBRTest.java
api/src/test/java/org/openmrs/module/radiology/hl7/v231/segment/RadiologyORCTest.java
api/src/test/java/org/openmrs/module/radiology/hl7/v231/segment/RadiologyPIDTest.java
api/src/test/java/org/openmrs/module/radiology/hl7/v231/segment/RadiologyZDSTest.java
api/src/test/java/org/openmrs/module/radiology/hl7/v231/util/HL7UtilsTest.java

* Create simple class HL7Constants containing constant ENCODING_CHARACTERS
so we have a single source of truth for them
see https://issues.openmrs.org/browse/RAD-210

RAD-210 Create HL7Constants with encoding characters

---

api/src/main/java/org/openmrs/module/radiology/validator/RadiologyDiscontinuedOrderValidator.java
api/src/test/java/org/openmrs/module/radiology/validator/RadiologyDiscontinuedOrderValidatorTest.java

Corrected issue with fork and made the desired changes. 
Make sure the supports(Class c) returns
true for objects assignable from the Order class
false for other types
Make sure the validate(Object obj, Errors errors)
fails when ** radiology order is null ** orderer is null ** orderReasonNonCoded is null
passes when ** all fields are correct
See https://issues.openmrs.org/browse/RAD-217

RAD-217 Add tests for RadiologyDiscontinuedOrderValidator

---

api/src/main/java/org/openmrs/module/radiology/validator/RadiologyReportValidator.java
api/src/test/java/org/openmrs/module/radiology/validator/RadiologyReportValidatorTest.java

Updated with changes and corrected fork.
Make sure the supports(Class c) returns
* true for objects of the RadiologyReport class
* false for other types
Make sure the validate(Object obj, Errors errors)
* fails when ** radiology report is null ** principalResultsInterpreter is empty or whitespace
* passes when ** all fields are correct
See https://issues.openmrs.org/browse/RAD-218

RAD-218 Add tests for RadiologyReportValidator

---

.travis.yml

Running travis CI in containerized environment is limited by 3GB RAM.
Somehow we now hit this limit on our component tests.
Trying out the non-containerized environment to see if thats really the issue
see https://issues.openmrs.org/browse/RAD-226

RAD-226 Travis CI fails due to memory

---

api/src/main/java/org/openmrs/module/radiology/order/RadiologyOrderServiceImpl.java

* fix OrderControl in RadiologyOrderServiceImpl's
discontinueRadiologyOrderInPacs which was NEW_ORDER instead
of CANCEL_ORDER
see https://issues.openmrs.org/browse/RAD-236

RAD-236 discontinueRadiologyOrderInPacs does not cancel order

---

api/src/main/java/org/openmrs/module/radiology/study/RadiologyStudy.java
api/src/test/java/org/openmrs/module/radiology/study/RadiologyStudyTest.java

Updated with changes and corrected fork.
Make sure the isScheduleable() returns
true for Study objects that their performedStatus is null
false for Study objects that their performedStatus is not null
Make sure the toString() returns
A string of a Study's components
"null" when a component of a study is not initialized
String of component otherwise
See https://issues.openmrs.org/browse/RAD-219

RAD-219 Add tests for Study.java

---

api/src/main/java/org/openmrs/module/radiology/order/HibernateRadiologyOrderDAO.java
api/src/main/java/org/openmrs/module/radiology/order/RadiologyOrderService.java
api/src/main/java/org/openmrs/module/radiology/report/HibernateRadiologyReportDAO.java
api/src/main/java/org/openmrs/module/radiology/study/HibernateRadiologyStudyDAO.java
api/src/test/java/org/openmrs/module/radiology/order/RadiologyOrderServiceComponentTest.java

* Change HibernateDAOs to return empty lists instead of null
see https://issues.openmrs.org/browse/RAD-243

RAD-243 Avoid NPEs in Hibernate DAOs

---

omod/src/main/java/org/openmrs/module/radiology/web/extension/html/GutterListExt.java
omod/src/main/resources/config.xml
omod/src/main/resources/messages.properties

[RAD-247: Create radiology menu](https://issues.openmrs.org/browse/RAD-248)
Added a gutter extension for radiology on the openmrs home page. It leads the manage radiology orders and needs a privilege of View Radiology Section
[RAD-248 Add orders tab](https://issues.openmrs.org/browse/RAD-248)
see https://issues.openmrs.org/browse/RAD-247

RAD-247: Create radiology menu entry

---

omod/src/main/java/org/openmrs/module/radiology/order/web/PatientDashboardRadiologyTabPortletController.java
omod/src/main/java/org/openmrs/module/radiology/web/extension/html/GutterListExt.java
omod/src/main/java/org/openmrs/module/radiology/web/extension/html/PatientDashboardRadiologyTabExt.java
omod/src/main/webapp/portlets/radiologyOrdersTab.jsp
omod/src/main/webapp/resources/radiology.css
omod/src/test/java/org/openmrs/module/radiology/order/web/PatientDashboardRadiologyTabPortletControllerTest.java

* fix javadoc summary PatientDashboardRadiologyTabPortletController.get()
* add missing @should to PatientDashboardRadiologyTabPortletController.get()
* remove @SuppressWarning from PatientDashboardRadiologyTabPortletControllerTest
* fix css lint 'Prohibit zero units'
* clean GutterListExt imports
* rename TabId to 'patientDashboardRadiologyTab'
* added linebreak in Orders tab between "Add Radiology Order" and top
see https://issues.openmrs.org/browse/RAD-248

RAD-248 minor cleanup

---

api/pom.xml
pom.xml

since we removed the hl7 package there is no need for the hapi dependency
anymore
* delete hapi dependency
see https://issues.openmrs.org/browse/RAD-253

RAD-253 Remove hapi dependency

---

api/src/main/resources/moduleApplicationContext.xml

when using the eclipse formatter on xml files it can cause
<value>org.openmrs.module.radiology.RadiologyOrderService
</value>
which makes spring fail to find the class since the line break is part of the
string.
* removed line breaks in values in moduleApplicationContext

fix moduleApplicationContext format

---

api/src/main/java/org/openmrs/module/radiology/order/HibernateRadiologyOrderDAO.java
api/src/main/java/org/openmrs/module/radiology/order/RadiologyOrderServiceImpl.java
api/src/main/java/org/openmrs/module/radiology/report/HibernateRadiologyReportDAO.java
api/src/main/java/org/openmrs/module/radiology/report/RadiologyReportServiceImpl.java
api/src/main/java/org/openmrs/module/radiology/study/HibernateRadiologyStudyDAO.java
api/src/main/java/org/openmrs/module/radiology/study/RadiologyStudyServiceImpl.java
api/src/main/resources/moduleApplicationContext.xml

* do not use @Autowired in OpenMrsService's since these slow down services down
* make RadiologyReportEditorComponentTest a unit test since changing the wiring
back xml prevented Context.getService(RadiologyReportService.class) from
finding the service
see https://issues.openmrs.org/browse/RAD-277

RAD-277 OpenmrsServices slow to load with autowired

---

api/src/main/java/org/openmrs/module/radiology/order/HibernateRadiologyOrderDAO.java
api/src/main/java/org/openmrs/module/radiology/order/RadiologyOrderDAO.java
api/src/main/java/org/openmrs/module/radiology/order/RadiologyOrderService.java
api/src/main/java/org/openmrs/module/radiology/order/RadiologyOrderServiceImpl.java
api/src/main/java/org/openmrs/module/radiology/report/HibernateRadiologyReportDAO.java
api/src/main/java/org/openmrs/module/radiology/report/RadiologyReportDAO.java
api/src/main/java/org/openmrs/module/radiology/report/RadiologyReportEditor.java
api/src/main/java/org/openmrs/module/radiology/report/RadiologyReportService.java
api/src/main/java/org/openmrs/module/radiology/report/RadiologyReportServiceImpl.java
api/src/test/java/org/openmrs/module/radiology/order/RadiologyOrderServiceComponentTest.java
api/src/test/java/org/openmrs/module/radiology/report/RadiologyReportEditorComponentTest.java
api/src/test/java/org/openmrs/module/radiology/report/RadiologyReportServiceComponentTest.java
api/src/test/java/org/openmrs/module/radiology/study/RadiologyStudyServiceComponentTest.java
omod/src/main/java/org/openmrs/module/radiology/order/web/RadiologyOrderFormController.java
omod/src/test/java/org/openmrs/module/radiology/order/web/RadiologyOrderFormControllerTest.java

the openmrs-core convention is that the service get methods which to get the
entity the service is for by its internal id are simply called
getEntity(Integer entityId)
Remove the ByXXX substring from our service and DAO methods
* RadiologyOrderService.getRadiologyOrderByOrderId()
* RadiologyReportService.getRadiologyReportByRadiologyReportId()
see https://issues.openmrs.org/browse/RAD-285

RAD-285 Rename service methods ByEntityId

---

omod/src/main/java/org/openmrs/module/radiology/web/extension/html/GutterListExt.java
omod/src/main/java/org/openmrs/module/radiology/web/extension/html/PatientDashboardRadiologyTabExt.java
omod/src/main/resources/messages.properties
omod/src/main/webapp/portlets/patientDashboardRadiologyTab.jsp
omod/src/main/webapp/radiologyDashboardForm.jsp

in the UI
* show a dashboard title, so the user knows where he is, since clicking on the
gutterlist does visually show where on the gutterlist you are
* add box around patientDashboardRadiologyTab table
* remove patient column in patientDashboardRadiologyTab since we have a huge
patient header showing us the patient we are at.
* restructure message properties for dashboard, gutterlist,
patientDashboardRadiologyTab
see https://issues.openmrs.org/browse/RAD-299

RAD-299 Show dashboard title and reorganize properties

---

omod/src/main/webapp/orders/radiologyOrderDetailsSegment.jsp

added orderReason to order entry page and to display of existing orders but did
show the orderable field "concept" instead of the orderReason
* show orderReason in radiologyOrderDetailsSegment
see https://issues.openmrs.org/browse/RAD-286

RAD-286 Fix display of orderReason

---

omod/src/main/webapp/orders/radiologyOrderCreationSegment.jsp

added scheduledDate to radiologyOrderCreationSegment in previous commit but it
the input element was visible by default and on page load the js was executed
which set it to hidden since default urgency="ROUTINE". this lead to the
element being visible for a short amount of time if page load is slow.
* hide scheduledDate input by default
see https://issues.openmrs.org/browse/RAD-188

RAD-188 Hide scheduledDate by default

---

api/src/main/java/org/openmrs/module/radiology/report/RadiologyReportValidator.java
api/src/test/java/org/openmrs/module/radiology/report/RadiologyReportValidatorTest.java
omod/src/main/java/org/openmrs/module/radiology/report/web/RadiologyReportFormController.java
omod/src/main/webapp/reports/radiologyReportForm.jsp
omod/src/test/java/org/openmrs/module/radiology/report/web/RadiologyReportFormControllerTest.java

RadiologyReportValidator prevents an empty report body when completing a
report, so a completed report always has a report body.
* adjusted RadiologyReportValidator to fail on empty report body
* adjusted radiologyReportForm to show error spans properly
* use jquery in tinymce init
* autowire RadiologyReportValidator since its already available as component
* fix error in RadiologyReportFormController, did not make proper use of the
Validator
see https://issues.openmrs.org/browse/RAD-173

RAD-173 Prevent empty report body

---

api/src/test/resources/org/openmrs/module/radiology/include/RadiologyEncounterMatcherComponentTestDataset.xml
api/src/test/resources/org/openmrs/module/radiology/include/RadiologyOrderServiceComponentTestDataset.xml
api/src/test/resources/org/openmrs/module/radiology/include/RadiologyReportServiceComponentTestDataset.xml
api/src/test/resources/org/openmrs/module/radiology/include/RadiologyStudyServiceComponentTestDataset.xml
omod/src/main/resources/config.xml
omod/src/test/resources/RadiologyOrderResourceComponentTestDataset.xml
omod/src/test/resources/RadiologyOrderSearchHandlerComponentTestDataset.xml

the org root UID (DICOM root UID) is entered as a global
property defaults to 2.25 but can be changed by the admin in the settings page.
however validation is missing on entry meaning if the admin configures a wrong
uid it will fail during creation of radiology orders. so the cause and the
event of failiure are separated.
* added RegexDatatypeHandler which was missing for the custom datatype
* configured the dicomUIDOrgRoot as RegexValidatedTextDatatype with a regex
ensuring proper DICOM UID is entered by the admin
* update test datasets GP of dicomUIDOrgRoot
see https://issues.openmrs.org/browse/RAD-107

RAD-107 Enforce valid DICOM UID for org root

---

api/src/main/java/org/openmrs/module/radiology/report/HibernateRadiologyReportDAO.java
api/src/main/java/org/openmrs/module/radiology/report/RadiologyReportDAO.java
api/src/main/java/org/openmrs/module/radiology/report/RadiologyReportSearchCriteria.java
api/src/main/java/org/openmrs/module/radiology/report/RadiologyReportService.java
api/src/main/java/org/openmrs/module/radiology/report/RadiologyReportServiceImpl.java
api/src/test/java/org/openmrs/module/radiology/order/RadiologyOrderValidatorTest.java
api/src/test/java/org/openmrs/module/radiology/report/RadiologyReportServiceComponentTest.java
api/src/test/resources/org/openmrs/module/radiology/include/RadiologyReportServiceComponentTestDataset.xml
omod/src/main/java/org/openmrs/module/radiology/report/web/resource/RadiologyReportResource.java

Provide search capabilities for the RadiologyReport resource so that a
user of the API can get all RadiologyReports within a certain date
range.
* add RadiologyReportSearchCriteria
* add search method to RadiologyReportService and RadiologyReportDAO
* modified RadiologyReportServiceComponentTestDataset.xml for component tests
* add component tests
see https://issues.openmrs.org/browse/RAD-282

RAD-282 Add REST search for RadiologyReport by date

---

omod/src/main/resources/messages.properties
omod/src/main/webapp/portlets/radiologyReportsTab.jsp

* when principalResultsInterpreter of a report was null due to the report
being a draft, then the list wouldnt load
* status column was hidden
* show date created and creator
see https://issues.openmrs.org/browse/RAD-136

RAD-136 Fix bug with null provider and show status

---

api/src/main/java/org/openmrs/module/radiology/report/HibernateRadiologyReportDAO.java
api/src/main/java/org/openmrs/module/radiology/report/RadiologyReportSearchCriteria.java
api/src/main/java/org/openmrs/module/radiology/report/RadiologyReportService.java
api/src/test/java/org/openmrs/module/radiology/report/RadiologyReportServiceComponentTest.java
api/src/test/resources/org/openmrs/module/radiology/include/RadiologyReportServiceComponentTestDataset.xml
omod/src/main/java/org/openmrs/module/radiology/report/web/search/RadiologyReportSearchHandler.java
omod/src/test/java/org/openmrs/module/radiology/report/web/search/RadiologyReportSearchHandlerComponentTest.java
omod/src/test/resources/RadiologyReportSearchHandlerComponentTestDataset.xml

RadiologyReport.reportStatus=DISCONTINUED should only be returned if
specifically asked for.
* add includeAll paramater to RadiologyReportSearchHandler
* add component test for RadiologyReportSearchHandler
* add includeDiscontinued attribute to RadiologyReportSearchCriteria
* modify report dao method getRadiologyReports
* add test to RadiologyReportServiceComponentTest
see https://issues.openmrs.org/browse/RAD-308

RAD-308 Do not include discontinued reports by default

---

api/src/main/java/org/openmrs/module/radiology/order/RadiologyOrderService.java
api/src/main/java/org/openmrs/module/radiology/order/RadiologyOrderServiceImpl.java
api/src/main/java/org/openmrs/module/radiology/report/RadiologyReportService.java
api/src/main/java/org/openmrs/module/radiology/report/RadiologyReportServiceImpl.java
api/src/main/java/org/openmrs/module/radiology/study/RadiologyStudyService.java
api/src/main/java/org/openmrs/module/radiology/study/RadiologyStudyServiceImpl.java

Spring advises to annotate only concrete classes with @Transactional
* remove @Transactional from our Service interfaces
* add class level @Transactional(readOnly=true) to our Service implemenations at class level
* override @Transactional(readOnly=true) for methods which are not-read only
* remove @Transactional from private method RadiologyOrderServiceImpl.saveRadiologyOrderEncounter
since it has no effect
see https://issues.openmrs.org/browse/RAD-332

RAD-332 Fix Transactions Across Service Methods

---

pom.xml

Added two maven profiles:
- `unit-test` (running all tests expect `*ComponentTest.java`)
- `integration-test` (running only `*ComponentTest.java` tests)
You can execute a maven profile by running e.g. `mvn test -P unit-test`.
If you are running maven without a profile (e.g. `mvn clean package`) all tests are executed but in separate goals.
Obviously no automated tests are provided for this change.
see https://issues.openmrs.org/browse/RAD-249

RAD-249 Add maven profile for integration-test

---

api/src/main/java/org/openmrs/module/radiology/RadiologyConstants.java
api/src/main/java/org/openmrs/module/radiology/order/AccessionNumberGenerator.java
api/src/main/java/org/openmrs/module/radiology/order/HibernateRadiologyOrderDAO.java
api/src/main/java/org/openmrs/module/radiology/order/RadiologyOrderDAO.java
api/src/main/java/org/openmrs/module/radiology/order/RadiologyOrderService.java
api/src/main/java/org/openmrs/module/radiology/order/RadiologyOrderServiceImpl.java
api/src/test/java/org/openmrs/module/radiology/order/HibernateRadiologyOrderDAOComponentTest.java
api/src/test/java/org/openmrs/module/radiology/order/RadiologyOrderServiceComponentTest.java
api/src/test/java/org/openmrs/module/radiology/order/RadiologyOrderServiceImplComponentTest.java
api/src/test/resources/org/openmrs/module/radiology/include/RadiologyOrderServiceComponentTestDataset.xml
api/src/test/resources/org/openmrs/module/radiology/include/RadiologyReportServiceComponentTestDataset.xml
api/src/test/resources/org/openmrs/module/radiology/include/RadiologyStudyServiceComponentTestDataset.xml
omod/src/main/java/org/openmrs/module/radiology/order/web/resource/RadiologyOrderResource.java
omod/src/main/resources/config.xml
omod/src/test/java/org/openmrs/module/radiology/order/web/resource/RadiologyOrderResourceComponentTest.java
omod/src/test/java/org/openmrs/module/radiology/order/web/resource/RadiologyOrderResourceTest.java
omod/src/test/resources/RadiologyOrderResourceComponentTestDataset.xml
omod/src/test/resources/RadiologyOrderSearchHandlerComponentTestDataset.xml
omod/src/test/resources/RadiologyReportResourceComponentTestDataset.xml
omod/src/test/resources/RadiologyReportSearchHandlerComponentTestDataset.xml

Generate an accessionnumber for radiology orders in same approach chosen by
order entry for orderNumber.
* add global property for accessionnr seed
* add accessionnr seed in config.xml (validated as regex so we only get digits)
* fix testdatasets for new global property
* remove unused obs row from testdatasets
* add AccessionNumberGenerator interface
* RadiologyOrderServiceImpl implements AccessionNumberGenerator
* add HibernateRadiologyOrderDAO method to get next accessionnr seed
* add HibernateRadiologyOrderDAOTest
* add test for placeRadiologyOrder
* show accessionnr in RadiologyOrderResource getDisplayString()
see https://issues.openmrs.org/browse/RAD-292

RAD-292 Generate accessionnumber

---

pom.xml

acceptance tests generate directories "build" when executed with test reports
and other temporary resources which we do not keep track in git and thus should
also not cause the plugin to complain that license headers are missing.
* exclude those directories in the mycila plugin config
* exlude other directories like .git, target ...
see https://issues.openmrs.org/browse/RAD-231

RAD-231 Exclude acceptance test build dirs from license plugin

---

omod/pom.xml

CI build error because of phantom js 2.0.0 version unavailable for linux
* add new phantomjs 2.1.1 version to pom.xml
see https://issues.openmrs.org/browse/RAD-270

RAD-270 Fix build

---

omod/src/main/webapp/portlets/radiologyReportsTab.jsp
omod/src/main/webapp/radiologyDashboardForm.jsp

On the reports tab portlet make sure that the filter defaults to the
reports of last week.
* add default value to date filter in radiologyReportsTab.jsp
* add new shortcut to daterangepicker in radiologyReportsTab.jsp
* add entry for date filter shortcut to message.properties
* hide date range picker when switching tab
see https://issues.openmrs.org/browse/RAD-340

RAD-340 Default reportlist filter to last week

---

README.md
api/pom.xml
docker-compose.yml
docs/DEMO-DATA.md
docs/DOCKER.md
omod/pom.xml
omod/src/main/assembly.xml
omod/src/main/docker/Dockerfile
pom.xml

Use fabric8io docker plugin instead of spotify's since it allows to link
containers. This way we do not need docker-compose and can totally integrate
docker into the maven build process.
* use fabric8io docker plugin
* define it in api/pom.xml with skip=true so we can build docker from the root
dir
* configure omod/pom.xml to use the docker plugin
** define the db image (from docker hub) with run properties
** define the radiology image with a link to db
* update readme
* add DOCKER.md
* put DEMO-DATA.md and DOCKER.md into docs/
see https://issues.openmrs.org/browse/RAD-333

RAD-333 Use fabric8io docker plugin

---

api/src/main/java/org/openmrs/module/radiology/order/HibernateRadiologyOrderDAO.java
api/src/main/java/org/openmrs/module/radiology/order/RadiologyOrderDAO.java
api/src/main/java/org/openmrs/module/radiology/order/RadiologyOrderService.java
api/src/main/java/org/openmrs/module/radiology/order/RadiologyOrderServiceImpl.java
api/src/test/java/org/openmrs/module/radiology/order/RadiologyOrderServiceComponentTest.java
api/src/test/resources/org/openmrs/module/radiology/include/RadiologyOrderServiceComponentTestDataset.xml

* Remove unused method getRadiologyOrderByPatients from service and DAO
see https://issues.openmrs.org/browse/RAD-344

RAD-344 Remove getRadiologyOrdersByPatients

---

api/pom.xml
api/src/test/java/org/openmrs/module/radiology/report/template/MrrtReportTemplateServiceComponentTest.java
omod/pom.xml
pom.xml

Ensure that when devs run mvn install/package the code and license headers are
formatted. Do not format on CI and fail on CI if license header is missing.
* bind mycila maven license plugin goal format to phase process-sources so it executes on
mvn install/package automatically.
* add ids to formatter plugins so we can override them easily
* extract common plugin configs for formatters into root pom in
pluginManagement
* fix missed formatting in MrrtReportTemplateServiceComponentTest
* add ci profile
* activated with env var CI=true
* license header will be checked and build will fail
* code and license header will not be formatted
see https://issues.openmrs.org/browse/RAD-345

RAD-345 Fail CI on missing license header and do not format

---

api/src/main/java/org/openmrs/module/radiology/order/HibernateRadiologyOrderDAO.java
api/src/main/java/org/openmrs/module/radiology/order/RadiologyOrderSearchCriteria.java
api/src/main/java/org/openmrs/module/radiology/order/RadiologyOrderService.java
api/src/test/java/org/openmrs/module/radiology/order/RadiologyOrderSearchCriteriaTest.java
api/src/test/java/org/openmrs/module/radiology/order/RadiologyOrderServiceComponentTest.java
api/src/test/resources/org/openmrs/module/radiology/include/RadiologyOrderServiceComponentTestDataset.xml

* Add from effective start dato to RadiologyOrderSearchCriteria, including tests
* Add to effective start dato to RadiologyOrderSearchCriteria, including tests
see https://issues.openmrs.org/browse/RAD-320

RAD-320 Add date to RadiologyOrderSearchCriteria

---

acceptanceTest/resources/demo-data.sql

* Update number seeds to assure that the assigned order or accession numbers continue after the ones from the test data
see https://issues.openmrs.org/browse/RAD-330

RAD-330 Fix number seeds in demo data

---

api/src/main/java/org/openmrs/module/radiology/study/HibernateRadiologyStudyDAO.java
api/src/main/java/org/openmrs/module/radiology/study/RadiologyStudyDAO.java
api/src/main/java/org/openmrs/module/radiology/study/RadiologyStudyService.java
api/src/main/java/org/openmrs/module/radiology/study/RadiologyStudyServiceImpl.java
api/src/test/java/org/openmrs/module/radiology/study/RadiologyStudyServiceComponentTest.java

Remove
* updateStudyPerformedStatus
* getRadiologyStudyByOrderId
* getRadiologyStudiesByRadiologyOrders
from RadiologyStudyService, since they are not used and RadiologyStudy will soon not be a member of RadiologyOrder.

Remove unused methods from RadiologyStudyService

---

omod/src/main/docker/Dockerfile

update Dockerfile URLs of module dependencies
* update webservices.rest module to 2.15 release
* get legacyui and webservices.rest from mavenrepo.openmrs.org

Get Dockerfile dependencies from nexus

---

docs/DOCKER.md
omod/pom.xml
omod/src/main/docker/Dockerfile

define maven properties with default values for docker environment variables.
this enables users to override for ex. JAVA_OPTS of tomcat or the tomcat port.
furthermore these can be used in setting up acceptance tests since they are
available in maven.
* add maven properties for docker envs
* fix docker image name of the image created in this repo
* update docker image for teleivo/openmrs-platform:2.0.0-1 which replaced
deprecated MySQL session variable "storage_engine"

define maven properties for docker envs

---

api/src/main/java/org/openmrs/module/radiology/report/template/MrrtReportTemplateService.java
api/src/main/java/org/openmrs/module/radiology/report/template/MrrtReportTemplateServiceImpl.java
api/src/test/java/org/openmrs/module/radiology/report/template/MrrtReportTemplateServiceComponentTest.java
omod/src/main/java/org/openmrs/module/radiology/report/template/MrrtReportTemplateFormController.java
omod/src/main/java/org/openmrs/module/radiology/report/template/web/resource/MrrtReportTemplateResource.java
omod/src/main/resources/messages.properties
omod/src/main/webapp/portlets/radiologyReportTemplatesTab.jsp
omod/src/main/webapp/reports/templates/mrrtReportTemplateForm.jsp
omod/src/test/java/org/openmrs/module/radiology/report/template/MrrtReportTemplateFormControllerTest.java
omod/src/test/java/org/openmrs/module/radiology/report/template/web/resource/MrrtReportTemplateResourceComponentTest.java
omod/src/test/java/org/openmrs/module/radiology/report/template/web/resource/MrrtReportTemplateResourceTest.java

RAD-307 View report templates from list
* Modified the report templates tab. Made the dashboard expandable. Added ability to view template structure
#
see https://issues.openmrs.org/browse/RAD-307

RAD-307 View report templates from list

---

api/src/main/java/org/openmrs/module/radiology/order/RadiologyOrderService.java
api/src/main/java/org/openmrs/module/radiology/order/RadiologyOrderServiceImpl.java
api/src/main/java/org/openmrs/module/radiology/study/RadiologyStudyService.java
api/src/main/java/org/openmrs/module/radiology/study/RadiologyStudyServiceImpl.java
api/src/test/java/org/openmrs/module/radiology/order/RadiologyOrderServiceComponentTest.java
api/src/test/java/org/openmrs/module/radiology/study/RadiologyStudyServiceComponentTest.java
omod/src/main/java/org/openmrs/module/radiology/order/web/RadiologyOrderFormController.java
omod/src/main/resources/messages.properties
omod/src/test/java/org/openmrs/module/radiology/order/web/RadiologyOrderFormControllerTest.java

throw openmrs APIException in service methods for cases violating business rules, and IllegalArgumentException for cases that are programming errors.
APIExceptions are thrown using message codes from the message properties files, so the client code can catch those and display the error message to the user.
* RadiologyStudyService.saveRadiologyStudy() does not allow saving existing
* use throw APIException in RadiologyOrderServie.placeRadiologyOrder() and
discontinueRadiologyOrder()
* catch APIException in RadiologyOrderFormController.saveRadiologyOrder()
* reduce code in catch block in
RadiologyOrderFormController.saveRadiologyOrder() only to the service call
* return in save/discontinueRadiologyOrder in controller after redirect since
model objects in model and view will not be used.
see …

RAD-303 Rethink exceptions of API

---

omod/src/main/webapp/reports/radiologyReportForm.jsp

RadiologyReport.uuid did change every time it was saved as draft, unclaimed or
completed.
* was due to missing uuid in model in the radiologyReportForm
see https://issues.openmrs.org/browse/RAD-305

RAD-305 Report uuid changes on saving

---

api/src/main/java/org/openmrs/module/radiology/report/RadiologyReportService.java
api/src/main/java/org/openmrs/module/radiology/report/RadiologyReportServiceImpl.java
api/src/test/java/org/openmrs/module/radiology/report/RadiologyReportServiceComponentTest.java

* turn UnsupportedOperationException into APIException since these cases
violate our business rules. This way they can be handled by the consumer.
* turn one IAE into an APIException because its a business rule violation
see https://issues.openmrs.org/browse/RAD-303

Update exceptions in RadiologyReport

---

api/src/main/java/org/openmrs/module/radiology/report/HibernateRadiologyReportDAO.java
api/src/main/java/org/openmrs/module/radiology/report/RadiologyReportDAO.java
api/src/main/java/org/openmrs/module/radiology/report/RadiologyReportService.java
api/src/main/java/org/openmrs/module/radiology/report/RadiologyReportServiceImpl.java
api/src/test/java/org/openmrs/module/radiology/report/RadiologyReportServiceComponentTest.java
omod/src/main/java/org/openmrs/module/radiology/report/web/RadiologyReportFormController.java
omod/src/main/resources/messages.properties
omod/src/main/webapp/reports/radiologyReportForm.jsp
omod/src/test/java/org/openmrs/module/radiology/report/web/RadiologyReportFormControllerTest.java

* rename createAndClaimRadiologyReport to createRadiologyReport (in service and
controller)
* rename saveRadiologyReport to saveRadiologyReportDraft
* prevent saveRadiologyReportDraft if radiologyReport.reportId is null
* prevent saveRadiologyReportDraft if order already has a completed report
* harmonize tests and javadoc of Service methods
* make createRadiologyReport/saveDraft/complete synchronized
* add class javadoc to RadiologyReportService
* make tests cleaner
* throw APIExceptions using message property codes in RadiologyReportService
* catch APIExceptions in controller
* set session attribute on success/err in controller
see https://issues.openmrs.org/browse/RAD-354

RAD-354 Overhaul ReportService

---

acceptanceTest/resources/demo-data.sql
api/src/main/java/org/openmrs/module/radiology/report/HibernateRadiologyReportDAO.java
api/src/main/java/org/openmrs/module/radiology/report/RadiologyReportDAO.java
api/src/main/java/org/openmrs/module/radiology/report/RadiologyReportSearchCriteria.java
api/src/main/java/org/openmrs/module/radiology/report/RadiologyReportService.java
api/src/main/java/org/openmrs/module/radiology/report/RadiologyReportServiceImpl.java
api/src/main/java/org/openmrs/module/radiology/report/RadiologyReportStatus.java
api/src/main/resources/RadiologyReport.hbm.xml
api/src/main/resources/liquibase.xml
api/src/test/java/org/openmrs/module/radiology/report/RadiologyReportSearchCriteriaTest.java
api/src/test/java/org/openmrs/module/radiology/report/RadiologyReportServiceComponentTest.java
api/src/test/resources/org/openmrs/module/radiology/include/RadiologyReportServiceComponentTestDataset.xml
omod/src/main/java/org/openmrs/module/radiology/report/web/RadiologyReportFormController.java
omod/src/main/java/org/openmrs/module/radiology/report/web/VoidRadiologyReportRequest.java
omod/src/main/java/org/openmrs/module/radiology/report/web/VoidRadiologyReportRequestValidator.java
omod/src/main/java/org/openmrs/module/radiology/report/web/resource/RadiologyReportResource.java
omod/src/main/java/org/openmrs/module/radiology/report/web/search/RadiologyReportSearchHandler.java
omod/src/main/resources/messages.properties
omod/src/main/webapp/portlets/radiologyReportsTab.jsp
omod/src/main/webapp/reports/radiologyReportForm.jsp
omod/src/test/java/org/openmrs/module/radiology/report/web/RadiologyReportFormControllerTest.java
omod/src/test/java/org/openmrs/module/radiology/report/web/VoidRadiologyReportRequestValidatorTest.java
omod/src/test/java/org/openmrs/module/radiology/report/web/resource/RadiologyReportResourceComponentTest.java
omod/src/test/java/org/openmrs/module/radiology/report/web/resource/RadiologyReportResourceTest.java
omod/src/test/java/org/openmrs/module/radiology/report/web/search/RadiologyReportSearchHandlerComponentTest.java
omod/src/test/resources/RadiologyReportResourceComponentTestDataset.xml
omod/src/test/resources/RadiologyReportSearchHandlerComponentTestDataset.xml

* rename unclaimRadiologyReport to voidRadiologyReport
* add liquibase changeset
* adapt hibernate mapping file
* adapt xml test datasets and demo-data.sql
* add messages properties entries and use them in APIException
* add try/catch to controller of voidRadiologyReport
* create tests of controller for redirect/not redirect and session attribute
* remove radiology report status DISCONTINUED, thus from service/dao/rest layers
* remove unused getRadiologyReportsByRadiologyOrderAndRadiologyReportStatus
* adapt SearchCriteria
* adapt REST
* add voided property to RadiologyReportResource
* adapt UI report list filter
* add voidReason to radiologyReportForm and handle its validity in controller
* add VoidRadiologyReportRequest with Validator to ensure voidReason isnt empty
* exclude voided …

RAD-355 Turn unclaim into voidRadiologyReport

---

api/src/main/java/org/openmrs/module/radiology/report/RadiologyReportService.java
api/src/main/java/org/openmrs/module/radiology/report/RadiologyReportServiceImpl.java
api/src/main/java/org/openmrs/module/radiology/report/RadiologyReportValidator.java
api/src/test/java/org/openmrs/module/radiology/report/RadiologyReportServiceComponentTest.java
api/src/test/resources/org/openmrs/module/radiology/include/RadiologyReportServiceComponentTestDataset.xml
omod/src/main/java/org/openmrs/module/radiology/report/web/RadiologyReportFormController.java
omod/src/test/java/org/openmrs/module/radiology/report/web/RadiologyReportFormControllerTest.java

* add Handler annotation to RadiologyReportValidator so AOP kicks in on
saveRadiologyReport
* add test for it
* adapt test dataset since report_body cannot be null
* since now RadiologyReport is ensured to be valid according to our Validator (via
AOP), we dont need param principalResultsInterpreter anymore. delete it
see https://issues.openmrs.org/browse/RAD-353

Rename completeRadiologyReport to saveRadiologyReport

---

api/src/main/java/org/openmrs/module/radiology/order/RadiologyOrderSearchCriteria.java
api/src/main/java/org/openmrs/module/radiology/report/RadiologyReportSearchCriteria.java
api/src/test/java/org/openmrs/module/radiology/order/RadiologyOrderSearchCriteriaTest.java
api/src/test/java/org/openmrs/module/radiology/order/RadiologyOrderServiceComponentTest.java
api/src/test/java/org/openmrs/module/radiology/report/RadiologyReportSearchCriteriaTest.java
api/src/test/java/org/openmrs/module/radiology/report/RadiologyReportServiceComponentTest.java
omod/src/main/java/org/openmrs/module/radiology/order/web/search/RadiologyOrderSearchHandler.java
omod/src/main/java/org/openmrs/module/radiology/report/web/search/RadiologyReportSearchHandler.java
omod/src/main/webapp/radiologyDashboardReportsTab.jsp
omod/src/test/java/org/openmrs/module/radiology/order/web/search/RadiologyOrderSearchHandlerComponentTest.java
omod/src/test/java/org/openmrs/module/radiology/report/web/search/RadiologyReportSearchHandlerComponentTest.java

* rename withFromEffectiveStartDate to fromEffectiveStartDate,
withToEffectiveStartDate to toEffectiveStartDate in
RadiologyOrderSearchCriteria.java
* rename withFromDate to fromDate, withToDate to toDate in
RadiologyReportSearchCriteria.java
* modify construction of RadiologyReportSearchCriteria

Rename date methods in SearchCriteriaBuilders

---

omod/src/main/java/org/openmrs/module/radiology/order/web/RadiologyDashboardOrdersTabController.java
omod/src/test/java/org/openmrs/module/radiology/order/web/RadiologyDashboardOrdersTabControllerTest.java

If orders tab gets selected through tab click and afterwards radiology gutter list link gets clicked
the orders tab controller redirects to previous active tab
see https://issues.openmrs.org/browse/RAD-364

RAD-364 Fix radiology dashboard tab bug

---

api/src/main/java/org/openmrs/module/radiology/RadiologyConstants.java
api/src/main/java/org/openmrs/module/radiology/RadiologyProperties.java
api/src/test/java/org/openmrs/module/radiology/RadiologyPropertiesComponentTest.java
omod/src/main/java/org/openmrs/module/radiology/order/web/RadiologyOrderFormController.java
omod/src/main/resources/config.xml
omod/src/main/webapp/orders/radiologyOrderCreationSegment.jsp
omod/src/main/webapp/orders/radiologyOrderDiscontinuationSegment.jsp

A global property should enable the admin to configure a list of
concept classes for reason coded from which an ordering clinician
can choose from when creating radiology orders.
* add new global property to RadiologyConstants.java
* add gloabl property to config.xml
* add method to get concept class names from specified uuids in
RadiologyProperties.java
* add tests for new method
* add model attribute for reason concept classes to radiology order
form controller
* add description to reason coded field in
radiologyOrderCreationSegment.jsp
* use spring form tags
see https://issues.openmrs.org/browse/RAD-295

RAD-295 Filter coded reason on ordering

---

api/src/main/resources/liquibase.xml

the radiology_order.order_id primary key was set to autoIncrement which makes
it possible to insert a new radiology_order using
"insert into radiology_order values (NULL);"
if there is a test_order matching the current auto_increment value of the
radiology_order. This should not be possible as this can cause a
radiology_order being attached to a test_order which is in fact not a
radiology_order.
Not-null constraint on radiology_order.order_id and Foreign key constraint to test_order.order_id
together ensure integrity of radiology_order data.

Remove radiology_order.order_id autoIncrement

---

omod/src/main/java/org/openmrs/module/radiology/order/web/RadiologyOrderFormController.java
omod/src/main/webapp/orders/radiologyOrderCreationForm.jsp
omod/src/main/webapp/orders/radiologyOrderForm.jsp
omod/src/test/java/org/openmrs/module/radiology/order/web/RadiologyOrderFormControllerTest.java

the radiologyOrderCreationSegment.jsp was included into the
radiologyOrderForm.jsp and surrounded by hasPrivilege tag to not display it
when the user is not allowed to create a report. Doesnt really make sense,
since if the user doesnt have the permission he is allowed on the page and the
page is blank.
* rename the jsp to radiologyOrderCreationForm.jsp
* add necessary header includes/footer
* adapt RadiologyOrderFormController to return the page for GET/POST requests
of new RadiologyOrder's
now when the user is missing a privilege he will be redirected via the
require tag and see what privileges he is missing.

Move radiologyOrderCreationSegment to own Form

---

omod/src/main/docker/Dockerfile

since we currently depend on a legacyui snapshot we need to update the
Dockerfile's url to get the snapshot as snapshots are not keept for ever
on nexus
will be resolved once we depend on 1.1 which has features/fixes we currently
need

Update legacyui snapshot link in Dockerfile

---

api/src/main/java/org/openmrs/module/radiology/report/template/ElementsExpressionValidationRule.java
api/src/main/java/org/openmrs/module/radiology/report/template/MetaTagsValidationEngine.java
api/src/main/java/org/openmrs/module/radiology/report/template/MrrtReportTemplateValidationException.java
api/src/main/java/org/openmrs/module/radiology/report/template/ValidationEngine.java
api/src/main/java/org/openmrs/module/radiology/report/template/ValidationError.java
api/src/main/java/org/openmrs/module/radiology/report/template/ValidationResult.java
api/src/main/java/org/openmrs/module/radiology/report/template/ValidationRule.java
api/src/main/java/org/openmrs/module/radiology/report/template/XsdMrrtReportTemplateValidator.java
api/src/main/resources/moduleApplicationContext.xml
api/src/test/java/org/openmrs/module/radiology/report/template/MetaTagsValidationEngineTest.java
api/src/test/java/org/openmrs/module/radiology/report/template/MrrtReportTemplateValidatorTest.java
api/src/test/java/org/openmrs/module/radiology/report/template/ValidationResultTest.java
omod/src/main/java/org/openmrs/module/radiology/report/template/web/RadiologyDashboardReportTemplatesTabController.java
omod/src/main/resources/messages.properties
omod/src/main/webapp/radiologyDashboardReportTemplatesTab.jsp
omod/src/test/java/org/openmrs/module/radiology/report/template/web/RadiologyDashboardReportTemplatesTabControllerTest.java

use a Production Rule System style approach to validate the mrrt meta
tag rules which are checked using jsoup in the
XsdMrrtReportTemplateValidator
* add validation engine interface which runs validation on given type
and returns a ValidationResult containing the ValidationError's
* add MetaTagsValidationEngine containing the ValidationRule's which
are checked when run
* add ValidationRule interface with ElementsExpressionValidationRule
impl which selects elements via jsoup and tests the condition Predicate
* catch MrrtReportTemplateValidationException in the
RadiologyDashboardReportTemplatesTabController and add the violations
into the model and view for display
* show violations in an <ul> to the user
see https://issues.openmrs.org/browse/RAD-359

RAD-359 Improve validation error messages on mrrt import

---

api/src/main/java/org/openmrs/module/radiology/report/template/DefaultMrrtReportTemplateFileParser.java
api/src/main/java/org/openmrs/module/radiology/report/template/MrrtReportTemplateFileParser.java
api/src/main/java/org/openmrs/module/radiology/report/template/MrrtReportTemplateService.java
api/src/main/java/org/openmrs/module/radiology/report/template/MrrtReportTemplateServiceImpl.java
api/src/main/java/org/openmrs/module/radiology/report/template/MrrtReportTemplateValidator.java
api/src/main/java/org/openmrs/module/radiology/report/template/XsdMrrtReportTemplateValidator.java
api/src/test/java/org/openmrs/module/radiology/report/template/MrrtReportTemplateFileParserComponentTest.java
api/src/test/java/org/openmrs/module/radiology/report/template/MrrtReportTemplateServiceComponentTest.java
api/src/test/java/org/openmrs/module/radiology/report/template/MrrtReportTemplateValidatorTest.java
omod/src/main/java/org/openmrs/module/radiology/report/template/web/RadiologyDashboardReportTemplatesTabController.java
omod/src/test/java/org/openmrs/module/radiology/report/template/web/RadiologyDashboardReportTemplatesTabControllerTest.java

Replace parameter type from InputStream to String in
interfaces for MrrtReportTemplateService.importMrrtReportTemplate
MrrtReportTemplateValidator.validate and MrrtReportTemplateFileParser.parse
since template files are expected to be < 120kB and this greatly
simplifies handling as InputStreams can only be read once.
* change import, parse, validate iface to String instead of InputStream
* simplify tests by extracting repetivite things (getFile,
getFileContent) for test mrrt template files into helper methods
* improve RadiologyDashboardReportTemplatesTabControllerTest verify
service calls and use springs MockMultipartFile
* improve javadoc im MrrtReportTemplateService and tests
* merge tests of MrrtReportTemplateService.importMrrtReportTemplate
ensuring creation in db and filesystem into …

Use String instead of InputStream on importing templates

---

api/src/main/java/org/openmrs/module/radiology/report/template/MrrtReportTemplateService.java
api/src/main/java/org/openmrs/module/radiology/report/template/MrrtReportTemplateServiceImpl.java
api/src/test/java/org/openmrs/module/radiology/report/template/MrrtReportTemplateServiceComponentTest.java

MrrtReportTemplateService.importMrrtReportTemplate now returns the
saved MrrtReportTemplate object which allows client code to for example
redirect the UI to the templates page after the import

importMrrtReportTemplate returns MrrtReportTemplate

---

acceptanceTest/resources/demo-data.sql

Role reading phyisican was missing privilege to get concept sources and
reference terms, which are needed when importing an MRRT Template which
has terms from a coding_scheme which matches a concept source

Demo data: add missing privileges to reading phyisican

---

api/src/main/java/org/openmrs/module/radiology/report/template/MrrtReportTemplateService.java
api/src/main/java/org/openmrs/module/radiology/report/template/MrrtReportTemplateServiceImpl.java
api/src/test/java/org/openmrs/module/radiology/report/template/MrrtReportTemplateServiceComponentTest.java
omod/src/main/java/org/openmrs/module/radiology/report/template/web/RadiologyDashboardReportTemplatesTabController.java
omod/src/main/resources/messages.properties
omod/src/main/webapp/radiologyDashboardReportTemplatesTab.jsp
omod/src/test/java/org/openmrs/module/radiology/report/template/web/RadiologyDashboardReportTemplatesTabControllerTest.java

RAD-374 Delete MrrtReportTemplate
Added a delete button on templates tab to delete templates
Added a controller method to handle delete request
Modified service method to delete template html file from file system
Unit test both controller and service method
see https://issues.openmrs.org/browse/RAD-374

RAD-374 Delete MrrtReportTemplate

---

api/src/test/java/org/openmrs/module/radiology/report/RadiologyReportServiceComponentTest.java
api/src/test/java/org/openmrs/module/radiology/report/RadiologyReportServiceTest.java

Created unit tests for RadiologyReportServiceTest and removed unnecessary integration tests.
see https://issues.openmrs.org/browse/RAD-382

RAD-382 Create RadiologyReportServiceTest

---

omod/src/main/docker/Dockerfile

openmrs retired its nexus repository and now uses artifactory and
bintray from jfrog.
* fixed the URLs to get the legacyui and webservices.rest module omods
in the Dockerfile which creates the radiology modules docker image
* needed to update the webservices.rest from 2.16 to 2.17 since the
former wasnt on jfrog
see https://issues.openmrs.org/browse/RAD-

fix omod Dockerfile URLs to dependencies

---

api/src/test/java/org/openmrs/module/radiology/modality/RadiologyModalityValidatorTest.java
api/src/test/java/org/openmrs/module/radiology/order/RadiologyOrderValidatorTest.java
api/src/test/java/org/openmrs/module/radiology/report/RadiologyReportValidatorTest.java
api/src/test/java/org/openmrs/module/radiology/test/ValidatorAssertions.java

* extract a test helper class to reduce duplcation in testing Validators
* arrange ValidatorTests similarly, make Errors, Validator under test
and the valid object a member of the test class to remove boilerplate
in tests
* arrange tests in Arrange, Act, Assert style
* split the null, empty string, whitespace tests into separate tests so
they do not depend on each other

Extract a test helper class for testing Validators
