- pom.xml
modules repository location moved from svn to github,
point <scm> section of root pom.xml to github
> fix scm in root pom.xml

- LICENSE
Add OpenMRS LICENSE
copied from
https://github.com/openmrs/openmrs-core
c2bb945a7464de7b87ca4240b48df46cc653de29
> GCI-6: Add an OpenMRS License file to selected OpenMRS modules

- api/pom.xml
- api/src/test/resources/TestingApplicationContext.xml
- api/src/test/resources/test-hibernate.cfg.xml
* prepare api for running unit tests
> add test resource infrastructure to api

- license-header.txt
* to be included as header in code files
> add license-header.txt from openmrs-core

- api/pom.xml
- omod/pom.xml
- pom.xml
* apply eclipse formatter on poms
* remove duplicate parent groupId in pom.xml
> Format poms

- api/src/main/java/org/openmrs/module/radiology/DicomUtils.java
* remove unused imports
* format javadocs
with eclipse auto-formatter
> eclipse auto-format DicomUtils imports/comments

- .travis.yml
- README.md
* add travis ci yaml configuration
* embed travis ci build status in readme
> add travis ci

- api/pom.xml
- pom.xml
* hamcrest style unit tests will first be added to api
> add hamcrest dependency for tests

- api/src/main/resources/Radiology.hbm.xml
- api/src/main/resources/liquibase.xml
- api/src/test/resources/TestingApplicationContext.xml
- api/src/test/resources/test-hibernate.cfg.xml
- omod/src/main/resources/config.xml
- omod/src/main/resources/log4j.xml
- omod/src/main/webapp/config.jsp
- omod/src/main/webapp/localHeader.jsp
- omod/src/main/webapp/obsForm.jsp
- omod/src/main/webapp/portlets/DashboardObsDetailsForm.jsp
- omod/src/main/webapp/portlets/DashboardObsForm.jsp
- omod/src/main/webapp/portlets/RadiologyDashboardTab.jsp
- omod/src/main/webapp/portlets/addOrderFields.jsp
- omod/src/main/webapp/portlets/orderSearch.jsp
- omod/src/main/webapp/portlets/patientOverview.jsp
- omod/src/main/webapp/radiologyOrderForm.jsp
- omod/src/main/webapp/radiologyOrderList.jsp
- omod/src/main/webapp/resources/js/orderList.js
- omod/src/main/webapp/resources/js/sortNumbers.js
- omod/src/test/resources/TestingApplicationContext.xml
* used eclipse autoformat (CTRL+SHIFT+F) with OpenMRS Formatter.xml on all xml and jsp files
(one time thing to fix formatting. needs to be done manually before every commit now, since xml and jsp do not get formatted by maven-java-formatter-plugin version 0.3.1)
> eclipse autoformat xml and jsp files

- api/src/main/java/org/openmrs/module/radiology/RadiologyActivator.java
- api/src/main/java/org/openmrs/module/radiology/web/ConfigController.java
- api/src/main/java/org/openmrs/module/radiology/web/RadiologyOrderListController.java
- omod/src/main/resources/config.xml
* rename Activator to RadiologyActivator
see https://issues.openmrs.org/browse/RAD-33
> RAD-33 - Module Activator name not meaningful

- api/src/main/java/org/openmrs/module/radiology/Study.java
* remove code that is never used
* remove unnecessary dependencies
see https://issues.openmrs.org/browse/RAD-19
> RAD-19 Remove unreferenced code from Study

- api/src/main/java/org/openmrs/module/radiology/hl7/CommonOrderOrderControl.java
- api/src/main/java/org/openmrs/module/radiology/hl7/CommonOrderPriority.java
- api/src/main/java/org/openmrs/module/radiology/hl7/HL7Generator.java
- api/src/main/java/org/openmrs/module/radiology/hl7/HL7Utils.java
- api/src/main/java/org/openmrs/module/radiology/hl7/custommodel/v231/message/ORM_O01.java
- api/src/main/java/org/openmrs/module/radiology/hl7/custommodel/v231/segment/ZDS.java
- api/src/main/java/org/openmrs/module/radiology/hl7/message/RadiologyORMO01.java
- api/src/main/java/org/openmrs/module/radiology/hl7/segment/RadiologyMSH.java
- api/src/main/java/org/openmrs/module/radiology/hl7/segment/RadiologyOBR.java
- api/src/main/java/org/openmrs/module/radiology/hl7/segment/RadiologyORC.java
- api/src/main/java/org/openmrs/module/radiology/hl7/segment/RadiologyPID.java
- api/src/main/java/org/openmrs/module/radiology/hl7/segment/RadiologyZDS.java
- api/src/main/java/org/openmrs/module/radiology/utils/DateTimeUtils.java
- api/src/test/java/org/openmrs/module/radiology/hl7/HL7GeneratorTest.java
- api/src/test/java/org/openmrs/module/radiology/hl7/HL7UtilsTest.java
- api/src/test/java/org/openmrs/module/radiology/hl7/custommodel/v231/message/ORM_O01Test.java
- api/src/test/java/org/openmrs/module/radiology/hl7/custommodel/v231/segment/ZDSTest.java
- api/src/test/java/org/openmrs/module/radiology/hl7/message/RadiologyORMO01Test.java
- api/src/test/java/org/openmrs/module/radiology/hl7/segment/RadiologyMSHTest.java
- api/src/test/java/org/openmrs/module/radiology/hl7/segment/RadiologyOBRTest.java
- api/src/test/java/org/openmrs/module/radiology/hl7/segment/RadiologyORCTest.java
- api/src/test/java/org/openmrs/module/radiology/hl7/segment/RadiologyPIDTest.java
- api/src/test/java/org/openmrs/module/radiology/hl7/segment/RadiologyZDSTest.java
- api/src/test/java/org/openmrs/module/radiology/utils/DateTimeUtilsTest.java
* add org.openmrs.module.radiology.hl7 package
* HL7Generator.createEncodedRadiologyORMO01Message() creates the encoded HL7 order message, which will be called by DicomUtils.createHL7Message see RAD-23.
see https://issues.openmrs.org/browse/RAD-14
> RAD-14 - Create hl7 package to generate ORM^O01 message

- NOTICE
describes all 3rd party FOSS components included by this module
see https://issues.openmrs.org/browse/RAD-17
> RAD-17 - Add notice file

- api/src/main/java/org/openmrs/module/radiology/DicomUtils.java
- api/src/main/java/org/openmrs/module/radiology/Modality.java
- api/src/main/java/org/openmrs/module/radiology/Study.java
- api/src/main/java/org/openmrs/module/radiology/web/PortletsController.java
- api/src/main/java/org/openmrs/module/radiology/web/RadiologyDashboardController.java
- api/src/main/java/org/openmrs/module/radiology/web/RadiologyOrderFormController.java
- api/src/main/resources/Radiology.hbm.xml
- api/src/main/resources/liquibase.xml
- omod/src/main/webapp/radiologyOrderForm.jsp
* make Study.modality of type Modality instead of int
see https://issues.openmrs.org/browse/RAD-24
> RAD-24 - Study.modality not type safe

- api/src/main/java/org/openmrs/module/radiology/hl7/segment/RadiologyOBR.java
- api/src/test/java/org/openmrs/module/radiology/hl7/HL7GeneratorTest.java
- api/src/test/java/org/openmrs/module/radiology/hl7/message/RadiologyORMO01Test.java
- api/src/test/java/org/openmrs/module/radiology/hl7/segment/RadiologyOBRTest.java
adapt the hl7 Observation Request Segment population to new Modality enum
fixes current build error
> Fix observationRequestSegment Modality

- api/src/main/java/org/openmrs/module/radiology/DicomUtils.java
- api/src/main/java/org/openmrs/module/radiology/RequestedProcedurePriority.java
- api/src/main/java/org/openmrs/module/radiology/Study.java
- api/src/main/java/org/openmrs/module/radiology/web/PortletsController.java
- api/src/main/java/org/openmrs/module/radiology/web/RadiologyDashboardController.java
- api/src/main/java/org/openmrs/module/radiology/web/RadiologyOrderFormController.java
- api/src/main/resources/Radiology.hbm.xml
- api/src/main/resources/liquibase.xml
- api/src/test/java/org/openmrs/module/radiology/DicomUtilsTest.java
- api/src/test/java/org/openmrs/module/radiology/hl7/HL7GeneratorTest.java
- api/src/test/java/org/openmrs/module/radiology/hl7/message/RadiologyORMO01Test.java
- omod/src/main/webapp/radiologyOrderForm.jsp
see https://issues.openmrs.org/browse/RAD-28
> RAD-28 - Study.priority not type safe

- api/src/main/java/org/openmrs/module/radiology/DicomUtils.java
- api/src/main/java/org/openmrs/module/radiology/ScheduledProcedureStepStatus.java
- api/src/main/java/org/openmrs/module/radiology/Study.java
- api/src/main/java/org/openmrs/module/radiology/web/RadiologyOrderFormController.java
- api/src/main/resources/Radiology.hbm.xml
- api/src/main/resources/liquibase.xml
- api/src/test/java/org/openmrs/module/radiology/ScheduledProcedureStepStatusTest.java
- omod/src/main/webapp/radiologyOrderForm.jsp
see https://issues.openmrs.org/browse/RAD-26
> RAD-26 - Study.scheduledStatus not type safe

- omod/src/main/java/org/openmrs/module/radiology/web/controller/ConfigController.java
- omod/src/main/java/org/openmrs/module/radiology/web/controller/ObsFormController.java
- omod/src/main/java/org/openmrs/module/radiology/web/controller/PortletsController.java
- omod/src/main/java/org/openmrs/module/radiology/web/controller/RadiologyDashboardController.java
- omod/src/main/java/org/openmrs/module/radiology/web/controller/RadiologyDashboardObsController.java
- omod/src/main/java/org/openmrs/module/radiology/web/controller/RadiologyOrderFormController.java
- omod/src/main/java/org/openmrs/module/radiology/web/controller/RadiologyOrderListController.java
- omod/src/main/java/org/openmrs/module/radiology/web/controller/StaticPagesController.java
- omod/src/main/java/org/openmrs/module/radiology/web/extension/html/AdminList.java
- omod/src/main/java/org/openmrs/module/radiology/web/extension/html/RadiologyDashboardExt.java
- omod/src/main/resources/config.xml
- omod/src/main/resources/webModuleApplicationContext.xml
move code related to the web ui to the omod folder
see https://issues.openmrs.org/browse/RAD-22
> RAD-22 - Web related code mixed with api

- api/src/main/java/org/openmrs/module/radiology/DicomUtils.java
- api/src/main/java/org/openmrs/module/radiology/Main.java
- api/src/main/java/org/openmrs/module/radiology/impl/MainImpl.java
- api/src/main/java/org/openmrs/module/radiology/web/RadiologyOrderFormController.java
see https://issues.openmrs.org/browse/RAD-32
> RAD-32 - MainImpl.saveStudy(Study, Date) does not use param Date

- api/src/main/java/org/openmrs/module/radiology/RadiologyActivator.java
- api/src/main/java/org/openmrs/module/radiology/Study.java
- api/src/main/java/org/openmrs/module/radiology/db/hibernate/GenericDAOImpl.java
- api/src/main/java/org/openmrs/module/radiology/db/hibernate/StudyDAOImpl.java
- api/src/main/java/org/openmrs/module/radiology/impl/MainImpl.java
- omod/src/main/java/org/openmrs/module/radiology/web/controller/RadiologyDashboardController.java
- omod/src/main/java/org/openmrs/module/radiology/web/extension/html/AdminList.java
- omod/src/main/java/org/openmrs/module/radiology/web/extension/html/RadiologyDashboardExt.java
* fix formatting of commit https://github.com/openmrs/openmrs-module-radiologydcm4chee/commit/ef9cfbb549111fa51a6edb080ded1b0689cbb2ee "RAD-32 and codestyle fixes"
> fix formatting with formatter plugin

- api/src/main/java/org/openmrs/module/radiology/DicomUtils.java
- api/src/main/java/org/openmrs/module/radiology/PerformedProcedureStepStatus.java
- api/src/main/java/org/openmrs/module/radiology/RadiologyActivator.java
- api/src/main/java/org/openmrs/module/radiology/Study.java
- api/src/main/java/org/openmrs/module/radiology/db/hibernate/GenericDAOImpl.java
- api/src/main/java/org/openmrs/module/radiology/db/hibernate/StudyDAOImpl.java
- api/src/main/java/org/openmrs/module/radiology/impl/MainImpl.java
- api/src/main/resources/Radiology.hbm.xml
- api/src/main/resources/liquibase.xml
- api/src/test/java/org/openmrs/module/radiology/PerformedProcedureStepStatusTest.java
- omod/src/main/java/org/openmrs/module/radiology/web/controller/RadiologyDashboardController.java
- omod/src/main/java/org/openmrs/module/radiology/web/controller/RadiologyOrderFormController.java
- omod/src/main/java/org/openmrs/module/radiology/web/extension/html/AdminList.java
- omod/src/main/java/org/openmrs/module/radiology/web/extension/html/RadiologyDashboardExt.java
- omod/src/main/webapp/radiologyOrderForm.jsp
* Study.performedStatus now type safe
* radiologyOrderForm.jsp performedStatusSelect is localized
see https://issues.openmrs.org/browse/RAD-27
> RAD-27 Study.performedStatus not type safe

- omod/src/main/webapp/obsForm.jsp
* fixes misleading error message
see https://issues.openmrs.org/browse/RAD-43
> RAD-43 obsForm shows wrong error message

- api/src/main/java/org/openmrs/module/radiology/DicomUtils.java
- api/src/main/java/org/openmrs/module/radiology/impl/MainImpl.java
- omod/src/main/java/org/openmrs/module/radiology/web/controller/RadiologyOrderFormController.java
see https://issues.openmrs.org/browse/RAD-37
> RAD-37 - OrderRequest.Default does not convey meaning

- api/src/main/java/org/openmrs/module/radiology/Study.java
- api/src/main/java/org/openmrs/module/radiology/db/StudyDAO.java
- api/src/main/java/org/openmrs/module/radiology/db/hibernate/StudyDAOImpl.java
- api/src/main/resources/Radiology.hbm.xml
- api/src/test/java/org/openmrs/module/radiology/hl7/HL7GeneratorTest.java
- api/src/test/java/org/openmrs/module/radiology/hl7/message/RadiologyORMO01Test.java
- api/src/test/java/org/openmrs/module/radiology/hl7/segment/RadiologyOBRTest.java
- api/src/test/java/org/openmrs/module/radiology/hl7/segment/RadiologyORCTest.java
- omod/src/main/java/org/openmrs/module/radiology/web/controller/RadiologyOrderFormController.java
see https://issues.openmrs.org/browse/RAD-39
> RAD-39 - Study.orderID name and type differ from core

- api/src/main/java/org/openmrs/module/radiology/Study.java
- api/src/main/java/org/openmrs/module/radiology/Utils.java
- api/src/main/java/org/openmrs/module/radiology/db/StudyDAO.java
remove author attributions from Cortex with his permission
see https://issues.openmrs.org/browse/RAD-38
> RAD-38 - Author attributions in code

- README.md
- api/pom.xml
- omod/pom.xml
- pom.xml
* move formatter plugin config from element pluginManagement to plugins in omod and api
(otherwise execution does not run)
* add execution element with goal format to trigger formatting on build in api and omod
* remove non-existing source files from omod formatter exceptions
* updated the readme
> RAD-47 Run maven-java-formatter-plugin on build

- api/src/main/java/org/openmrs/module/radiology/DicomUtils.java
- api/src/main/java/org/openmrs/module/radiology/RadiologyService.java
- api/src/main/java/org/openmrs/module/radiology/Study.java
- api/src/main/java/org/openmrs/module/radiology/Utils.java
- api/src/main/java/org/openmrs/module/radiology/impl/RadiologyServiceImpl.java
- api/src/main/resources/moduleApplicationContext.xml
- omod/src/main/java/org/openmrs/module/radiology/web/controller/ObsFormController.java
- omod/src/main/java/org/openmrs/module/radiology/web/controller/PortletsController.java
- omod/src/main/java/org/openmrs/module/radiology/web/controller/RadiologyDashboardObsController.java
- omod/src/main/java/org/openmrs/module/radiology/web/controller/RadiologyOrderFormController.java
see https://issues.openmrs.org/browse/RAD-30
> RAD-30 Radiology service and implementation class names not meaningful

- api/src/main/java/org/openmrs/module/radiology/DicomUtils.java
- api/src/main/java/org/openmrs/module/radiology/MwlStatus.java
- api/src/main/java/org/openmrs/module/radiology/RadiologyService.java
- api/src/main/java/org/openmrs/module/radiology/Study.java
- api/src/main/java/org/openmrs/module/radiology/Utils.java
- api/src/main/java/org/openmrs/module/radiology/impl/RadiologyServiceImpl.java
- api/src/main/resources/Radiology.hbm.xml
- api/src/main/resources/liquibase.xml
- api/src/main/resources/moduleApplicationContext.xml
- api/src/test/java/org/openmrs/module/radiology/DicomUtilsTest.java
- omod/src/main/java/org/openmrs/module/radiology/web/controller/ObsFormController.java
- omod/src/main/java/org/openmrs/module/radiology/web/controller/PortletsController.java
- omod/src/main/java/org/openmrs/module/radiology/web/controller/RadiologyDashboardController.java
- omod/src/main/java/org/openmrs/module/radiology/web/controller/RadiologyDashboardObsController.java
- omod/src/main/java/org/openmrs/module/radiology/web/controller/RadiologyOrderFormController.java
- omod/src/main/resources/messages.properties
- omod/src/main/webapp/portlets/orderSearch.jsp
* add MwlStatus enum
* remove magic numbers
* store Study.mwlStatus state via enum element name in database
* add enum element names in properties files for internationalization
see https://issues.openmrs.org/browse/RAD-29
> RAD-29 Study.mwlStatus not type safe

- api/src/main/java/org/openmrs/module/radiology/Study.java
see https://issues.openmrs.org/browse/RAD-49
> RAD-49 Remove unused constructor in Study

- omod/src/main/java/org/openmrs/module/radiology/web/controller/RadiologyObsFormController.java
forgot to rename the view name returned by the controller
after renaming the jsp file
> fix RadiologyObsFormController view name

- api/src/main/java/org/openmrs/module/radiology/RadiologyService.java
- api/src/main/java/org/openmrs/module/radiology/Study.java
- api/src/main/java/org/openmrs/module/radiology/db/StudyDAO.java
- api/src/main/java/org/openmrs/module/radiology/db/hibernate/StudyDAOImpl.java
- api/src/main/java/org/openmrs/module/radiology/impl/RadiologyServiceImpl.java
- api/src/test/java/org/openmrs/module/radiology/RadiologyServiceTest.java
- api/src/test/resources/org/openmrs/module/radiology/include/RadiologyServiceTestDataSet.xml
- omod/src/main/java/org/openmrs/module/radiology/web/controller/PortletsController.java
- omod/src/main/java/org/openmrs/module/radiology/web/controller/RadiologyDashboardController.java
* move Study.get(List<Order>) to RadiologyService.getStudiesByOrders(List<Order>)
* add RadiologyServiceTest with RadiologyServiceTestDataSet.xml
see https://issues.openmrs.org/browse/RAD-31
> RAD-31 Study.get() provide radiology service layer functions

- api/src/main/java/org/openmrs/module/radiology/RadiologyService.java
- api/src/main/java/org/openmrs/module/radiology/Study.java
- api/src/main/java/org/openmrs/module/radiology/db/StudyDAO.java
- api/src/main/java/org/openmrs/module/radiology/db/hibernate/StudyDAOImpl.java
- api/src/main/java/org/openmrs/module/radiology/impl/RadiologyServiceImpl.java
- api/src/test/java/org/openmrs/module/radiology/RadiologyServiceTest.java
- omod/src/main/java/org/openmrs/module/radiology/web/controller/RadiologyDashboardObsController.java
- omod/src/main/java/org/openmrs/module/radiology/web/controller/RadiologyObsFormController.java
see https://issues.openmrs.org/browse/RAD-42
> RAD-42 Study.obs() provides radiology service layer functions

- api/src/main/java/org/openmrs/module/radiology/DicomUtils.java
- api/src/main/java/org/openmrs/module/radiology/RadiologyService.java
- api/src/main/java/org/openmrs/module/radiology/db/StudyDAO.java
- api/src/main/java/org/openmrs/module/radiology/db/hibernate/StudyDAOImpl.java
- api/src/main/java/org/openmrs/module/radiology/impl/RadiologyServiceImpl.java
- api/src/test/java/org/openmrs/module/radiology/RadiologyServiceTest.java
* add getStudyByStudyInstanceUid(String) to RadiologyService
* remove duplicate Study Instance UID generation logic in DicomUtils.writeMPPS
see https://issues.openmrs.org/browse/RAD-51
> RAD-51 DicomUtils.writeMPPS() repeats logic of StudyInstanceUID creation

- api/src/main/java/org/openmrs/module/radiology/Study.java
- omod/src/main/java/org/openmrs/module/radiology/web/controller/PortletsController.java
- omod/src/main/java/org/openmrs/module/radiology/web/controller/RadiologyDashboardController.java
- omod/src/main/java/org/openmrs/module/radiology/web/util/StudyStatusColumnGenerator.java
- omod/src/test/java/org/openmrs/module/radiology/web/util/StudyStatusColumnGeneratorTest.java
* moved Study.getStatus(User)
* moved Study.status(boolean, boolean) to web
* renamed methods, and variables but did not change the logic of the methods!
* added unit tests
see https://issues.openmrs.org/browse/RAD-52
> RAD-52 Move Study.getStatus(User) to web

- api/src/main/java/org/openmrs/module/radiology/Study.java
* Removed unnecessary constructor from Study
see https://issues.openmrs.org/browse/RAD-53
> RAD-53 Remove unnecessary constructor from Study

- api/src/main/java/org/dcm4che2/tool/dcmof/MPPSSCP.java
- api/src/main/java/org/openmrs/module/radiology/DicomUtils.java
- api/src/test/java/org/openmrs/module/radiology/DicomUtilsTest.java
* rename to updateStudyPerformedStatusByMpps()
* split functionality into smaller methods
- DicomUtils.getStudyInstanceUidFromMpps(DicomObject)
- DicomUtils.getPerformedProcedureStepStatus(DicomObject)
* add unit tests
see https://issues.openmrs.org/browse/RAD-50
> RAD-50 Refactor DicomUtils.writeMPPS()

- omod/src/main/webapp/radiologyObsForm.jsp
see https://issues.openmrs.org/browse/RAD-46
> RAD-46 obsForm contains unreachable code

- api/src/main/java/org/openmrs/module/radiology/RadiologyService.java
- api/src/main/java/org/openmrs/module/radiology/db/StudyDAO.java
- api/src/main/java/org/openmrs/module/radiology/db/hibernate/StudyDAOImpl.java
- api/src/main/java/org/openmrs/module/radiology/impl/RadiologyServiceImpl.java
- api/src/test/java/org/openmrs/module/radiology/RadiologyServiceTest.java
- api/src/test/resources/org/openmrs/module/radiology/include/RadiologyServiceTestDataSet.xml
* add unit tests for RadiologyService.saveStudy()
* prevent saving a Study with no orderId or modality
see https://issues.openmrs.org/browse/RAD-55
> RAD-55 Add unit tests to RadiologyService.saveStudy(Study)

- api/src/main/java/org/openmrs/module/radiology/Study.java
- api/src/main/java/org/openmrs/module/radiology/db/hibernate/StudyDAOImpl.java
- api/src/main/java/org/openmrs/module/radiology/hl7/segment/RadiologyZDS.java
- api/src/main/resources/Radiology.hbm.xml
- api/src/main/resources/liquibase.xml
- api/src/test/java/org/openmrs/module/radiology/DicomUtilsTest.java
- api/src/test/java/org/openmrs/module/radiology/RadiologyServiceTest.java
- api/src/test/java/org/openmrs/module/radiology/hl7/HL7GeneratorTest.java
- api/src/test/java/org/openmrs/module/radiology/hl7/message/RadiologyORMO01Test.java
- api/src/test/java/org/openmrs/module/radiology/hl7/segment/RadiologyZDSTest.java
- api/src/test/resources/org/openmrs/module/radiology/include/RadiologyServiceTestDataSet.xml
- omod/src/main/java/org/openmrs/module/radiology/web/controller/RadiologyDashboardObsController.java
- omod/src/main/java/org/openmrs/module/radiology/web/controller/RadiologyObsFormController.java
- omod/src/main/java/org/openmrs/module/radiology/web/controller/RadiologyOrderFormController.java
see https://issues.openmrs.org/browse/RAD-48
> RAD-48 Rename Study.uid to Study.studyInstanceUid

- api/src/main/java/org/openmrs/module/radiology/RadiologyActivator.java
see https://issues.openmrs.org/browse/RAD-56
> RAD-56 Remove unnecessary method call from RadiologyActivator

- README.md
- api/src/test/java/org/openmrs/module/radiology/RadiologyServiceTest.java
- api/src/test/resources/org/openmrs/module/radiology/include/RadiologyServiceTestDataSet.xml
- omod/src/main/resources/config.xml
- pom.xml
* Update RadiologyServiceTestDataSet.xml to include order urgency
see https://issues.openmrs.org/browse/RAD-57
> RAD-57 Make the module compatible to OpenMRS version 1.9.4

- omod/src/main/java/org/openmrs/module/radiology/web/controller/PortletsController.java
- omod/src/main/webapp/portlets/addOrderFields.jsp
see https://issues.openmrs.org/browse/RAD-62
> RAD-62 Remove addOrderFields

- omod/src/main/java/org/openmrs/module/radiology/web/controller/RadiologyOrderFormController.java
- omod/src/main/webapp/radiologyOrderForm.jsp
* use spring modelattributes to automatically populate the model
with booleans indicating user roles instead of adding it manually
* use clearer names according to java naming convention for booleans
for readability
see https://issues.openmrs.org/browse/RAD-68
> RAD-68 Use role modelattributes in RadiologyOrderFormController

- README.md
* forgot to update the openmrs-core version in the readme
> RAD-64-addon Fix README after openmrs-core update

- api/src/main/java/org/openmrs/module/radiology/impl/RadiologyServiceImpl.java
- api/src/test/java/org/openmrs/module/radiology/RadiologyServiceTest.java
- omod/src/main/java/org/openmrs/module/radiology/web/controller/RadiologyOrderFormController.java
* move logic of setting Study.studyInstanceUid from omod to api
see https://issues.openmrs.org/browse/RAD-61
> RAD-61 Set StudyInstanceUid in RadiologyService.saveStudy()

- api/src/main/java/org/openmrs/module/radiology/RadiologyActivator.java
- omod/src/main/java/org/openmrs/module/radiology/web/controller/PortletsController.java
- omod/src/main/resources/messages.properties
- omod/src/main/resources/messages_es.properties
- omod/src/main/resources/webModuleApplicationContext.xml
- omod/src/main/webapp/portlets/orderSearch.jsp
- omod/src/main/webapp/radiologyOrderList.jsp
- omod/src/main/webapp/resources/js/orderList.js
- omod/src/test/java/org/openmrs/module/radiology/test/RadiologyTestData.java
- omod/src/test/java/org/openmrs/module/radiology/web/controller/PortletsControllerTest.java
see https://issues.openmrs.org/browse/RAD-65
> RAD-65 Refactor PortletsController Including Tests

- api/src/main/java/org/openmrs/module/radiology/RadiologyActivator.java
- omod/src/main/java/org/openmrs/module/radiology/web/controller/RadiologyObsFormController.java
- omod/src/test/java/org/openmrs/module/radiology/test/RadiologyTestData.java
- omod/src/test/java/org/openmrs/module/radiology/web/controller/RadiologyObsFormControllerTest.java
see https://issues.openmrs.org/browse/RAD-69
> RAD-69 Add RadiologyObsFormControllerTest

- omod/src/main/webapp/radiologyOrderForm.jsp
* its easier to read conditionals testing for
positive than negative statements
see https://issues.openmrs.org/browse/RAD-70
> RAD-70 Reduce if not's in radiologyOrderForm

- omod/src/main/java/org/openmrs/module/radiology/web/controller/RadiologyOrderFormController.java
- omod/src/test/java/org/openmrs/module/radiology/web/controller/RadiologyOrderFormControllerTest.java
* split get method according to concerns
see https://issues.openmrs.org/browse/RAD-71
> RAD-71 Split RadiologyOrderFormController GET variants

- api/src/main/java/org/openmrs/module/radiology/DicomUtils.java
- api/src/main/java/org/openmrs/module/radiology/Utils.java
* increases test coverage, reduces unnecessary dependencies, increases confidence in the code
see https://issues.openmrs.org/browse/RAD-76
> RAD-76 Remove unreferenced DicomUtils and Utils

- api/src/main/java/org/openmrs/module/radiology/Study.java
- api/src/main/java/org/openmrs/module/radiology/impl/RadiologyServiceImpl.java
- api/src/test/java/org/openmrs/module/radiology/RadiologyServiceTest.java
- omod/src/main/java/org/openmrs/module/radiology/web/controller/RadiologyOrderFormController.java
* move logic from Study.setup() to
RadiologyOrderFormController and RadiologyServiceImpl
see https://issues.openmrs.org/browse/RAD-72
> RAD-72 Move logic from Study.setup()

- omod/src/main/java/org/openmrs/module/radiology/web/controller/RadiologyOrderFormController.java
- omod/src/test/java/org/openmrs/module/radiology/web/controller/RadiologyOrderFormControllerTest.java
see https://issues.openmrs.org/browse/RAD-77
> RAD-77 Use spring to bind patient in RadiologyOrderFormController

- api/src/main/java/org/openmrs/module/radiology/DicomUtils.java
- api/src/main/java/org/openmrs/module/radiology/Study.java
- api/src/main/java/org/openmrs/module/radiology/db/hibernate/StudyDAOImpl.java
- api/src/main/java/org/openmrs/module/radiology/hl7/segment/RadiologyOBR.java
- api/src/main/java/org/openmrs/module/radiology/hl7/segment/RadiologyORC.java
- api/src/main/java/org/openmrs/module/radiology/impl/RadiologyServiceImpl.java
- api/src/main/resources/RadiologyStudy.hbm.xml
- api/src/main/resources/liquibase.xml
- api/src/test/java/org/openmrs/module/radiology/DicomUtilsTest.java
- api/src/test/java/org/openmrs/module/radiology/RadiologyServiceTest.java
- api/src/test/java/org/openmrs/module/radiology/hl7/HL7GeneratorTest.java
- api/src/test/java/org/openmrs/module/radiology/hl7/message/RadiologyORMO01Test.java
- api/src/test/java/org/openmrs/module/radiology/hl7/segment/RadiologyOBRTest.java
- api/src/test/java/org/openmrs/module/radiology/hl7/segment/RadiologyORCTest.java
- api/src/test/resources/org/openmrs/module/radiology/include/RadiologyServiceTestDataSet.xml
- omod/src/main/java/org/openmrs/module/radiology/web/controller/RadiologyOrderFormController.java
- omod/src/main/webapp/radiologyOrderForm.jsp
- omod/src/test/java/org/openmrs/module/radiology/test/RadiologyTestData.java
- omod/src/test/java/org/openmrs/module/radiology/web/controller/RadiologyOrderFormControllerTest.java
* rename Study.id to Study.studyId
* change type from int to Integer
see https://issues.openmrs.org/browse/RAD-75
> RAD-75 Rename Study.id and change to wrapper type

- omod/src/main/java/org/openmrs/module/radiology/web/controller/RadiologyDashboardController.java
- omod/src/main/resources/webModuleApplicationContext.xml
- omod/src/main/webapp/portlets/RadiologyDashboardTab.jsp
- omod/src/test/java/org/openmrs/module/radiology/test/RadiologyTestData.java
- omod/src/test/java/org/openmrs/module/radiology/web/controller/RadiologyDashboardControllerTest.java
see https://issues.openmrs.org/browse/RAD-66
> RAD-66 Refactor RadiologyDashboardController Including Tests

- api/src/main/java/org/openmrs/module/radiology/DicomUtils.java
- api/src/main/java/org/openmrs/module/radiology/RadiologyActivator.java
- api/src/main/java/org/openmrs/module/radiology/RadiologyConstants.java
- api/src/main/java/org/openmrs/module/radiology/RadiologyProperties.java
- api/src/main/java/org/openmrs/module/radiology/Utils.java
- api/src/main/java/org/openmrs/module/radiology/impl/RadiologyServiceImpl.java
- api/src/test/java/org/openmrs/module/radiology/DicomUtilsTest.java
- api/src/test/java/org/openmrs/module/radiology/RadiologyPropertiesTest.java
- api/src/test/java/org/openmrs/module/radiology/RadiologyServiceTest.java
- omod/src/main/java/org/openmrs/module/radiology/web/controller/ConfigController.java
- omod/src/main/java/org/openmrs/module/radiology/web/controller/RadiologyDashboardObsController.java
- omod/src/main/java/org/openmrs/module/radiology/web/controller/RadiologyObsFormController.java
- omod/src/main/java/org/openmrs/module/radiology/web/controller/RadiologyOrderFormController.java
- omod/src/main/resources/config.xml
- omod/src/main/webapp/portlets/DashboardObsForm.jsp
- omod/src/main/webapp/radiologyObsForm.jsp
- omod/src/main/webapp/radiologyOrderForm.jsp
- omod/src/test/java/org/openmrs/module/radiology/web/controller/RadiologyObsFormControllerTest.java
- omod/src/test/java/org/openmrs/module/radiology/web/controller/RadiologyOrderFormControllerTest.java
see https://issues.openmrs.org/browse/RAD-79
> RAD-79 Extract global module properties

- omod/src/main/java/org/openmrs/module/radiology/web/controller/RadiologyOrderFormController.java
- omod/src/main/webapp/radiologyOrderForm.jsp
- omod/src/test/java/org/openmrs/module/radiology/web/controller/RadiologyOrderFormControllerTest.java
see https://issues.openmrs.org/browse/RAD-34
> Rad 34 Adding radiology order chooses default concept anemia

- api/src/main/java/org/openmrs/module/radiology/RadiologyConstants.java
- api/src/main/java/org/openmrs/module/radiology/RadiologyProperties.java
- omod/src/main/java/org/openmrs/module/radiology/web/controller/ConfigController.java
see https://issues.openmrs.org/browse/RAD-60
> clean up after RAD-60

- omod/src/test/java/org/openmrs/module/radiology/web/controller/RadiologyOrderFormControllerTest.java
* remove unused local variable concept and
the unused Concept import
was forgotten in PR for https://issues.openmrs.org/browse/RAD-34
> Cleanup after RAD-34

- api/src/main/java/org/openmrs/module/radiology/DicomUtils.java
- api/src/main/java/org/openmrs/module/radiology/RadiologyService.java
- api/src/main/java/org/openmrs/module/radiology/hl7/HL7Generator.java
- api/src/main/java/org/openmrs/module/radiology/hl7/message/RadiologyORMO01.java
- api/src/main/java/org/openmrs/module/radiology/hl7/segment/RadiologyOBR.java
- api/src/main/java/org/openmrs/module/radiology/hl7/segment/RadiologyORC.java
- api/src/main/java/org/openmrs/module/radiology/impl/RadiologyServiceImpl.java
- api/src/test/java/org/openmrs/module/radiology/DicomUtilsTest.java
- api/src/test/java/org/openmrs/module/radiology/hl7/HL7GeneratorTest.java
- api/src/test/java/org/openmrs/module/radiology/hl7/custommodel/v231/message/ORM_O01Test.java
- api/src/test/java/org/openmrs/module/radiology/hl7/message/RadiologyORMO01Test.java
- api/src/test/java/org/openmrs/module/radiology/hl7/segment/RadiologyOBRTest.java
- api/src/test/java/org/openmrs/module/radiology/hl7/segment/RadiologyORCTest.java
- omod/src/main/java/org/openmrs/module/radiology/web/controller/RadiologyOrderFormController.java
* use RadiologyOrder.study in hl7 package methods to remove
method parameter study and only provice radiologyOrder
see https://issues.openmrs.org/browse/RAD-85
> RAD-85 Adapt hl7 package to RadiologyOrder.study

- omod/src/main/java/org/openmrs/module/radiology/web/controller/PortletsController.java
- omod/src/main/resources/messages.properties
- omod/src/main/resources/messages_es.properties
- omod/src/main/webapp/portlets/orderSearch.jsp
- omod/src/main/webapp/resources/js/orderList.js
- omod/src/test/java/org/openmrs/module/radiology/test/RadiologyTestData.java
- omod/src/test/java/org/openmrs/module/radiology/web/controller/PortletsControllerTest.java
see https://issues.openmrs.org/browse/RAD-83
> RAD-83 Refactor PortletsController Including Tests

- omod/src/main/java/org/openmrs/module/radiology/web/controller/RadiologyOrderFormController.java
- omod/src/main/resources/messages.properties
- omod/src/main/resources/messages_es.properties
- omod/src/test/java/org/openmrs/module/radiology/test/RadiologyTestData.java
- omod/src/test/java/org/openmrs/module/radiology/web/controller/RadiologyOrderFormControllerTest.java
see https://issues.openmrs.org/browse/RAD-86
> RAD-86 fix NullPointerException in RadiologyOrderFormController

- omod/src/main/java/org/openmrs/module/radiology/web/controller/RadiologyObsFormController.java
- omod/src/main/java/org/openmrs/module/radiology/web/controller/RadiologyOrderFormController.java
- omod/src/main/webapp/radiologyOrderForm.jsp
- omod/src/test/java/org/openmrs/module/radiology/test/RadiologyTestData.java
- omod/src/test/java/org/openmrs/module/radiology/web/controller/RadiologyObsFormControllerTest.java
- omod/src/test/java/org/openmrs/module/radiology/web/controller/RadiologyOrderFormControllerTest.java
adapt
* RadiologyOrderFormController
* RadiologyObsFormController
to RadiologyOrder.study
see https://issues.openmrs.org/browse/RAD-88
> RAD-88 Adapt Controllers to RadiologyOrder.study

- api/src/main/java/org/openmrs/module/radiology/DicomUtils.java
- api/src/main/java/org/openmrs/module/radiology/RadiologyActivator.java
- api/src/main/java/org/openmrs/module/radiology/RadiologyProperties.java
just adding jdoc and renaming one method, see https://issues.openmrs.org/browse/RAD-79
> RAD-79 amend java doc for radiology properties

- api/src/main/java/org/openmrs/propertyeditor/ObsEditor.java
- api/src/test/java/org/openmrs/propertyeditor/ObsEditorTest.java
- api/src/test/resources/log4j.xml
- omod/src/main/java/org/openmrs/module/radiology/web/controller/RadiologyObsFormController.java
- omod/src/main/webapp/portlets/DashboardObsForm.jsp
- omod/src/main/webapp/radiologyObsForm.jsp
- omod/src/test/java/org/openmrs/module/radiology/web/controller/RadiologyObsFormControllerTest.java
- omod/src/test/resources/log4j.xml
- omod/src/test/resources/test/log4j.properties
see https://issues.openmrs.org/browse/RAD-90
> RAD-90 Refactor RadiologyObsFormController Including Tests

- api/src/main/java/org/openmrs/module/radiology/DicomUtils.java
- api/src/main/java/org/openmrs/module/radiology/RadiologyService.java
- api/src/main/java/org/openmrs/module/radiology/impl/RadiologyServiceImpl.java
- api/src/test/java/org/openmrs/module/radiology/RadiologyServiceTest.java
see https://issues.openmrs.org/browse/RAD-91
> RAD-91 Add RadiologyService.updateStudyPerformedStatus()

- api/src/main/java/org/openmrs/module/radiology/impl/RadiologyServiceImpl.java
see https://issues.openmrs.org/browse/RAD-93
> RAD-93 Make RadiologyServiceImpl package private

- api/src/main/java/org/openmrs/module/radiology/DicomUtils.java
- api/src/main/java/org/openmrs/module/radiology/impl/RadiologyServiceImpl.java
- api/src/test/java/org/openmrs/module/radiology/RadiologyServiceTest.java
see https://issues.openmrs.org/browse/RAD-101
> RAD-101 Remove DicomUtils.write()

- api/pom.xml
* remove unused dependencies to dcm4chee-core and filecache
see https://issues.openmrs.org/browse/RAD-104
> RAD-104 Clean dcm4chee dependencies in api pom

- api/src/main/resources/RadiologyStudy.hbm.xml
- api/src/main/resources/liquibase.xml
* and add unique constraint
see https://issues.openmrs.org/browse/RAD-94
> RAD-94 Add index to radiology_study.study_instance_uid

- api/src/main/resources/liquibase.xml
see https://issues.openmrs.org/browse/RAD-108
> RAD-108 radiology_study.order_id lacks not null constraint

- api/src/main/java/org/openmrs/module/radiology/RadiologyActivator.java
- api/src/test/java/org/openmrs/module/radiology/RadiologyActivatorComponentTest.java
- api/src/test/resources/org/openmrs/module/radiology/include/RadiologyActivatorComponentTestDataset.xml
see https://issues.openmrs.org/browse/RAD-110
> RAD-110 refactor RadiologyActivator including Tests

- omod/src/main/java/org/openmrs/module/radiology/web/controller/RadiologyObsFormController.java
- omod/src/test/java/org/openmrs/module/radiology/test/RadiologyTestData.java
- omod/src/test/java/org/openmrs/module/radiology/web/controller/RadiologyObsFormControllerTest.java
see https://issues.openmrs.org/browse/RAD-111
> RAD-111 Fix error when editing observation

- api/src/test/java/org/openmrs/module/radiology/DicomUtilsComponentTest.java
see https://issues.openmrs.org/browse/RAD-103
> RAD-103 Align DicomUtilsTest with other tests

- api/src/main/java/org/openmrs/module/radiology/RadiologyService.java
- api/src/main/java/org/openmrs/module/radiology/db/StudyDAO.java
- api/src/main/java/org/openmrs/module/radiology/db/hibernate/StudyDAOImpl.java
- api/src/main/java/org/openmrs/module/radiology/impl/RadiologyServiceImpl.java
- api/src/test/java/org/openmrs/module/radiology/DicomUtilsComponentTest.java
- api/src/test/java/org/openmrs/module/radiology/RadiologyServiceComponentTest.java
- api/src/test/java/org/openmrs/module/radiology/impl/RadiologyServiceImplComponentTest.java
see https://issues.openmrs.org/browse/RAD-95
> RAD-95 Add tests for RadiologyService.getStudy

- omod/src/main/webapp/radiologyObsForm.jsp
see https://issues.openmrs.org/browse/RAD-112
> RAD-112 Fix display error in observation form

- api/src/main/java/org/openmrs/module/radiology/RadiologyProperties.java
- api/src/test/java/org/openmrs/module/radiology/RadiologyPropertiesComponentTest.java
see https://issues.openmrs.org/browse/RAD-117
> Refactor RadiologyPropertiesComponentTest

- omod/src/main/webapp/radiologyOrderForm.jsp
See https://issues.openmrs.org/browse/RAD-119
> RAD-119 Link patient in radiologyOrderForm.jsp

- omod/src/main/java/org/openmrs/module/radiology/web/controller/PortletsController.java
- omod/src/main/java/org/openmrs/module/radiology/web/controller/RadiologyDashboardObsController.java
- omod/src/main/java/org/openmrs/module/radiology/web/controller/RadiologyObsFormController.java
- omod/src/test/java/org/openmrs/module/radiology/web/controller/PortletsControllerTest.java
see https://issues.openmrs.org/browse/RAD-123
> RAD-123 Remove @InitBinder from controllers

- omod/src/main/java/org/openmrs/module/radiology/web/controller/RadiologyObsFormController.java
- omod/src/test/java/org/openmrs/module/radiology/web/controller/RadiologyObsFormControllerTest.java
see https://issues.openmrs.org/browse/RAD-124
> RAD-124 Fix edit reason gets lost

- .travis.yml
- README.md
- api/pom.xml
- omod/pom.xml
- pom.xml
* add jacoco dependency
* create jacoco.exec for api and omod on build
* add coveralls-maven-plugin dependency
* create jacoco report and send it to coveralls after
build succeded on travis ci
see https://issues.openmrs.org/browse/RAD-122
> RAD-122 Add test coverage via coveralls.io

- omod/src/main/java/org/openmrs/module/radiology/web/controller/RadiologyObsFormController.java
- omod/src/test/java/org/openmrs/module/radiology/test/RadiologyTestData.java
- omod/src/test/java/org/openmrs/module/radiology/web/controller/RadiologyObsFormControllerTest.java
see https://issues.openmrs.org/browse/RAD-113
> RAD-113 Support images as concepts

- omod/src/main/java/org/openmrs/module/radiology/web/controller/RadiologyObsFormController.java
- omod/src/test/java/org/openmrs/module/radiology/test/RadiologyTestData.java
- omod/src/test/java/org/openmrs/module/radiology/web/controller/RadiologyObsFormControllerTest.java
Reverts openmrs/openmrs-module-radiologydcm4chee#160
> Revert 2942831adadd9431116b27691ed07ed1e7fb0a8e

- omod/src/main/webapp/radiologyObsForm.jsp
see https://issues.openmrs.org/browse/RAD-120
> RAD-120 Make voided obs uneditable

- omod/src/main/java/org/openmrs/module/radiology/web/controller/RadiologyObsFormController.java
- omod/src/test/java/org/openmrs/module/radiology/web/controller/RadiologyObsFormControllerTest.java
see https://issues.openmrs.org/browse/RAD-126
> RAD-126 refactor radiologyobsformcontroller

- api/src/main/java/org/openmrs/module/radiology/RadiologyConstants.java
- api/src/main/java/org/openmrs/module/radiology/RadiologyProperties.java
- api/src/test/java/org/openmrs/module/radiology/RadiologyPropertiesComponentTest.java
- omod/src/main/java/org/openmrs/module/radiology/web/controller/RadiologyOrderFormController.java
- omod/src/main/resources/config.xml
- omod/src/main/webapp/radiologyOrderForm.jsp
Filter Concepts in RadiologyOrderForm by ConceptClasses
Enter UUID of ConceptClasses in Radiology Settings
see [https://issues.openmrs.org/browse/RAD-129](url)
> RAD-129 - Administrator configures concept classes mapping to radiology orders

- CONTRIBUTING.md
- README.md
* add contributing guide
* clean readme and refer to contributing
see https://issues.openmrs.org/browse/RAD-134
> RAD-134 Add CONTRIBUTING.md

- README.md
- pom.xml
the modules wiki page moved to
https://wiki.openmrs.org/display/docs/Radiology+Module
> RAD-149 Update references to modules wiki

- api/src/main/resources/liquibase.xml
* Add role uuids
* Add privilege uuids
> RAD-130 Add uuids to liquibase.xml

- omod/src/main/webapp/radiologyOrderForm.jsp
see https://issues.openmrs.org/browse/RAD-153
> RAD-153: Error message now displayed against 'Related Concept'

- omod/src/main/resources/messages_es.properties
converted the file from ansi to utf8
> RAD-158 message_es.properties not in utf8

- .gitignore
- .tx/config
* added .tx/config to configure translation of
the modules resources via transifex
see https://issues.openmrs.org/browse/RAD-141
> RAD-141 Manage translations via transifex

- acceptanceTest/build.gradle
- acceptanceTest/config/config_example.config
- acceptanceTest/config/db/config_db_example.config
- acceptanceTest/config/login/config_login_example.config
- acceptanceTest/gradle/wrapper/gradle-wrapper.properties
- acceptanceTest/gradlew
- acceptanceTest/gradlew.bat
- acceptanceTest/readme.md
- acceptanceTest/src/main/java/org/openmrs/module/radiology/acceptancetest/dataset/DbTestSelectSupport.java
- acceptanceTest/src/test/java/org/openmrs/module/radiology/acceptancetest/dataset/Aselecttests/FindUsersTest.java
- acceptanceTest/src/test/java/org/openmrs/module/radiology/acceptancetest/dataset/DbTestConfiguration.java
As a developer I want the acceptance tests to check if any data (users, patients, concepts, orders) exists that is needed to run the tests by the acceptance test module itself.
> RAD-148 Implementing DB operations for acceptance Tests

- api/src/main/java/org/openmrs/module/radiology/RadiologyOrder.java
- api/src/main/java/org/openmrs/module/radiology/RadiologyService.java
- api/src/main/java/org/openmrs/module/radiology/Study.java
- api/src/main/java/org/openmrs/module/radiology/impl/RadiologyServiceImpl.java
- api/src/test/java/org/openmrs/module/radiology/RadiologyOrderTest.java
- api/src/test/java/org/openmrs/module/radiology/RadiologyServiceComponentTest.java
- api/src/test/java/org/openmrs/module/radiology/StudyTest.java
- omod/src/main/java/org/openmrs/module/radiology/web/controller/RadiologyOrderFormController.java
- omod/src/main/webapp/radiologyOrderForm.jsp
- omod/src/test/java/org/openmrs/module/radiology/web/controller/RadiologyOrderFormControllerTest.java
* add tests for Study.isCompleted()
* add RadiologyOrder.isCompleted()
* add RadiologyOrder.isNotCompleted
* replace use of ! Study.isCompleted() in
RadiologyServiceImpl.createAndClaimRadiologyReport() by
RadiologyOrder.isNotCompleted()
* add missing tests for radiologyReportNeedsToBeCreated in RadiologyOrderFormControllerTest
* simplify radiologyReportNeedsToBeCreated
see https://issues.openmrs.org/browse/RAD-166
> RAD-166 Add RadiologyOrder.isCompleted()

- api/src/main/java/org/openmrs/module/radiology/impl/RadiologyServiceImpl.java
this is done via AOP on save of BaseOpenmrsData objects
see https://issues.openmrs.org/browse/RAD-176
> RAD-176 Do not set report creator

- api/src/main/java/org/openmrs/module/radiology/dicom/DicomViewer.java
- api/src/test/java/org/openmrs/module/radiology/dicom/DicomViewerTest.java
- omod/src/main/java/org/openmrs/module/radiology/web/controller/RadiologyOrderFormController.java
- omod/src/main/webapp/portlets/radiologyOrderDetailsPortlet.jsp
- omod/src/test/java/org/openmrs/module/radiology/web/controller/RadiologyOrderFormControllerTest.java
Added link to DICOM images for completed RadiologyOrder
see https://issues.openmrs.org/browse/RAD-145
> RAD-145 Add link to DICOM images for completed RadiologyOrder

- api/src/main/java/org/openmrs/module/radiology/dicom/DicomViewer.java
- api/src/test/java/org/openmrs/module/radiology/dicom/DicomViewerTest.java
- omod/src/main/java/org/openmrs/module/radiology/web/controller/RadiologyOrderFormController.java
- omod/src/main/java/org/openmrs/module/radiology/web/controller/RadiologyReportFormController.java
- omod/src/main/webapp/portlets/radiologyOrderDetailsPortlet.jsp
- omod/src/test/java/org/openmrs/module/radiology/web/controller/RadiologyOrderFormControllerTest.java
- omod/src/test/java/org/openmrs/module/radiology/web/controller/RadiologyReportFormControllerTest.java
add to previous RAD-145 PR
* only show dicomViewerUrl for completed orders
* add tests in RadiologyOrderFormController for all cases
of getRadiologyReportFormWithExistingRadiologyReport()
* add dicomViewerUrl to RadiologyReportFormController with tests
see https://issues.openmrs.org/browse/RAD-145
> RAD-145 only show dicomViewerUrl for completed orders

- omod/src/main/resources/messages.properties
- omod/src/main/webapp/portlets/radiologyOrderDetailsPortlet.jsp
- omod/src/main/webapp/radiologyOrderForm.jsp
- omod/src/main/webapp/radiologyReportForm.jsp
* add patient header and boxes in radiologyOrderForm
* adapt comments in radiologyOrderForm
* rename related concepts to imaging procedure
* fix overwritten "general.id" in radiologyOrderForm's and radiologyReportForm
* add radiology.radiologyOrder message property and use it
as title for RadiologyOrder's in radiologyOrderForm.jsp
see https://issues.openmrs.org/browse/RAD-143
> RAD-143 Harmonize radiologyOrderForm look

- omod/src/main/java/org/openmrs/module/radiology/web/controller/RadiologyOrderFormController.java
- omod/src/test/java/org/openmrs/module/radiology/web/controller/RadiologyOrderFormControllerTest.java
just redirect to radiologyOrderForm when saving a new radiology order
and show the new order.
see https://issues.openmrs.org/browse/RAD-179
> RAD-179 Redirect to radiologyOrderForm on save of radiology order

- NOTICE
- api/src/main/java/org/openmrs/module/radiology/RadiologyService.java
- api/src/main/java/org/openmrs/module/radiology/db/RadiologyReportDAO.java
- api/src/main/java/org/openmrs/module/radiology/db/hibernate/RadiologyReportDAOImpl.java
- api/src/main/java/org/openmrs/module/radiology/impl/RadiologyServiceImpl.java
- api/src/test/java/org/openmrs/module/radiology/RadiologyServiceComponentTest.java
- omod/src/main/java/org/openmrs/module/radiology/web/controller/PortletsController.java
- omod/src/main/resources/messages.properties
- omod/src/main/webapp/portlets/orderSearch.jsp
- omod/src/main/webapp/radiologyOrderList.jsp
- omod/src/main/webapp/resources/js/orderList.js
- omod/src/test/java/org/openmrs/module/radiology/web/controller/PortletsControllerTest.java
addition of sortType to radiologyOrderList causes the order list not to show
any orders for "All orders" and "Orders without Report"
remove feature
see https://issues.openmrs.org/browse/RAD-180
> RAD-180 radiologyOrderList sortType fails

- omod/src/main/resources/messages.properties
- omod/src/main/webapp/portlets/RadiologyDashboardTab.jsp
- omod/src/main/webapp/portlets/orderSearch.jsp
* remove unnecessary includes in RadiologyDashboardTab.jsp
* adapt includes of css and js files to radiologyOrderList.jsp
* remove references to colvis
see https://issues.openmrs.org/browse/RAD-168
> RAD-168 Adapt RadiologyDashboardTab list to new style

- omod/src/main/java/org/openmrs/module/radiology/web/controller/PortletsController.java
- omod/src/main/java/org/openmrs/module/radiology/web/controller/RadiologyDashboardController.java
- omod/src/main/webapp/portlets/orderSearch.jsp
- omod/src/main/webapp/portlets/radiologyDashboardTab.jsp
- omod/src/main/webapp/radiologyOrderList.jsp
- omod/src/main/webapp/resources/js/radiologyOrderList.js
- omod/src/test/java/org/openmrs/module/radiology/web/controller/PortletsControllerTest.java
- omod/src/test/java/org/openmrs/module/radiology/web/controller/RadiologyDashboardControllerTest.java
* rename RadiologyDashboardTab.jsp to radiologyDashboardTab.jsp
* improve tests of RadiologyDashboardTabController
* rename orderList to radiologyOrders in radiologyDashboardTab
* rename orderList.js to radiologyOrderList.js
* remove voidReasonPopup
* radiologyOrderList.js is not needed in RadiologyDashboardTab
see https://issues.openmrs.org/browse/RAD-181
> RAD-181 Improve radiology order lists

- omod/src/main/webapp/portlets/radiologyOrderDetailsPortlet.jsp
- omod/src/main/webapp/radiologyOrderForm.jsp
when entering the scheduled order date
see https://issues.openmrs.org/browse/RAD-182
> RAD-182 Use datetimepicker in radiologyOrderForm

- omod/src/main/resources/messages.properties
- omod/src/main/webapp/portlets/orderSearch.jsp
- omod/src/main/webapp/portlets/radiologyDashboardTab.jsp
- omod/src/main/webapp/portlets/radiologyOrderDetailsPortlet.jsp
- omod/src/main/webapp/radiologyOrderForm.jsp
Add translations where missing and use existing ones for urgency, performed,
scheduled status in lists and create form
see https://issues.openmrs.org/browse/RAD-183
> RAD-183 Translate urgency, performed, scheduled status

- omod/src/main/webapp/portlets/orderSearch.jsp
add hyperlink to patientDashboard.form in patient columns in
radiologyOrderList
see https://issues.openmrs.org/browse/RAD-184
> RAD-184 Link patient columns in order list to patientDashboard

- omod/src/main/webapp/resources/js/radiologyOrderList.js
open child-data in radiologyOrder.list when clicking on the row, instead of
the +/- buttons.
see ttps://issues.openmrs.org/browse/RAD-186
> RAD-186 Open child on row click

- api/src/main/java/org/openmrs/module/radiology/DicomUtils.java
- api/src/main/java/org/openmrs/module/radiology/RadiologyActivator.java
- api/src/main/java/org/openmrs/module/radiology/RadiologyConstants.java
- api/src/main/java/org/openmrs/module/radiology/RadiologyProperties.java
- api/src/test/java/org/openmrs/module/radiology/DicomUtilsComponentTest.java
- api/src/test/java/org/openmrs/module/radiology/RadiologyActivatorComponentTest.java
- api/src/test/java/org/openmrs/module/radiology/RadiologyPropertiesComponentTest.java
- api/src/test/resources/org/openmrs/module/radiology/include/RadiologyActivatorComponentTestDataset.xml
- api/src/test/resources/org/openmrs/module/radiology/include/RadiologyServiceComponentTestDataset.xml
- omod/src/main/resources/config.xml
rename PACS global properties and add RadiologyProperties methods
to retrieve them.
see https://issues.openmrs.org/browse/RAD-191
> RAD_191 Rename PACS GPs

- api/src/main/java/org/openmrs/module/radiology/RadiologyActivator.java
- api/src/main/java/org/openmrs/module/radiology/RadiologyConstants.java
- api/src/main/java/org/openmrs/module/radiology/RadiologyProperties.java
- api/src/test/java/org/openmrs/module/radiology/RadiologyActivatorComponentTest.java
- api/src/test/java/org/openmrs/module/radiology/RadiologyPropertiesComponentTest.java
- api/src/test/resources/org/openmrs/module/radiology/include/RadiologyActivatorComponentTestDataset.xml
- omod/src/main/resources/config.xml
since its the port of the module and not the PACS
* rename GP
* rename RadiologyProperties get method and tests
* update description in config.xml
see https://issues.openmrs.org/browse/RAD-192
> RAD-192 Rename GP pacsDicomMppsPort

- api/src/main/java/org/openmrs/module/radiology/DicomUtils.java
- api/src/main/java/org/openmrs/module/radiology/impl/RadiologyServiceImpl.java
* rename method to sendHL7Message
* return true on success of sending message and false otherwise
see https://issues.openmrs.org/browse/RAD-197
> RAD-197 Refactor DicomUtils.sendHL7Worklist

- api/src/main/java/org/openmrs/module/radiology/impl/RadiologyServiceImpl.java
- api/src/test/java/org/openmrs/module/radiology/impl/RadiologyServiceImplComponentTest.java
since RadiologyServiceImpl.sendModalityWorklist() does
more than just one thing. Improves testability
see https://issues.openmrs.org/browse/RAD-200
> RAD-200 Extract private method updateStudyMwlStatus

- api/src/main/java/org/openmrs/module/radiology/DicomUtils.java
- api/src/main/java/org/openmrs/module/radiology/RadiologyService.java
- api/src/main/java/org/openmrs/module/radiology/impl/RadiologyServiceImpl.java
- api/src/test/java/org/openmrs/module/radiology/DicomUtilsComponentTest.java
- api/src/test/java/org/openmrs/module/radiology/RadiologyServiceComponentTest.java
- omod/src/main/java/org/openmrs/module/radiology/web/controller/RadiologyOrderFormController.java
- omod/src/test/java/org/openmrs/module/radiology/web/controller/RadiologyOrderFormControllerTest.java
* remove sendModalityWorklist(RadiologyOrder, OrderRequest) parameter
OrderRequest by splitting the method into two
- placeRadiologyOrderInPacs(RadiologyOrder)
- discontinueRadiologyOrderInPacs(RadiologyOrder)
* remove DicomUtils.getCommonOrderControlFrom() and pass in
CommonOrderControl to createHL7Message directly
see https://issues.openmrs.org/browse/RAD-201
> RAD-201 Remove OrderRequest

- api/src/main/java/org/openmrs/module/radiology/RadiologyConstants.java
- api/src/main/java/org/openmrs/module/radiology/RadiologyEncounterMatcher.java
- api/src/main/java/org/openmrs/module/radiology/RadiologyProperties.java
- api/src/main/java/org/openmrs/module/radiology/RadiologyService.java
- api/src/main/java/org/openmrs/module/radiology/impl/RadiologyServiceImpl.java
- api/src/main/java/org/openmrs/module/radiology/validator/RadiologyDiscontinuedOrderValidator.java
- api/src/main/resources/liquibase.xml
- api/src/main/resources/moduleApplicationContext.xml
- api/src/test/java/org/openmrs/module/radiology/RadiologyEncounterMatcherComponentTest.java
- api/src/test/java/org/openmrs/module/radiology/RadiologyPropertiesComponentTest.java
- api/src/test/java/org/openmrs/module/radiology/RadiologyServiceComponentTest.java
- api/src/test/java/org/openmrs/module/radiology/impl/RadiologyServiceImplComponentTest.java
- api/src/test/resources/org/openmrs/module/radiology/include/RadiologyServiceComponentTestDataset.xml
- omod/src/main/java/org/openmrs/module/radiology/web/controller/RadiologyOrderFormController.java
- omod/src/main/resources/config.xml
- omod/src/main/webapp/radiologyOrderForm.jsp
- omod/src/test/java/org/openmrs/module/radiology/web/controller/RadiologyOrderFormControllerTest.java
see https://issues.openmrs.org/browse/RAD-160
> RAD-160 Use emr-api to manage encounters

- omod/src/main/webapp/radiologyOrderForm.jsp
- omod/src/main/webapp/radiologyReportForm.jsp
see https://issues.openmrs.org/browse/RAD-204
> RAD-204 Exchange personHeader by patientHeader

- api/src/test/java/org/openmrs/module/radiology/RadiologyEncounterMatcherComponentTest.java
- api/src/test/java/org/openmrs/module/radiology/RadiologyServiceComponentTest.java
see https://issues.openmrs.org/browse/RAD-202
> RAD-202 Use autowired in component tests

- api/src/main/java/org/openmrs/module/radiology/db/hibernate/RadiologyOrderDAOImpl.java
- api/src/main/java/org/openmrs/module/radiology/db/hibernate/RadiologyReportDAOImpl.java
- api/src/main/java/org/openmrs/module/radiology/db/hibernate/StudyDAOImpl.java
- api/src/main/resources/moduleApplicationContext.xml
see https://issues.openmrs.org/browse/RAD-207
> RAD-207 Use autowired in DAO Implementations

- api/src/main/java/org/openmrs/module/radiology/db/hibernate/HibernateRadiologyOrderDAO.java
- api/src/main/java/org/openmrs/module/radiology/db/hibernate/HibernateRadiologyReportDAO.java
- api/src/main/java/org/openmrs/module/radiology/db/hibernate/HibernateStudyDAO.java
- api/src/main/resources/moduleApplicationContext.xml
- api/src/test/java/org/openmrs/module/radiology/impl/RadiologyServiceImplComponentTest.java
see https://issues.openmrs.org/browse/RAD-208
> RAD-208 Rename dao implementations

- api/src/main/java/org/openmrs/module/radiology/DicomUtils.java
- api/src/main/java/org/openmrs/module/radiology/hl7/util/HL7Sender.java
- api/src/main/java/org/openmrs/module/radiology/impl/RadiologyServiceImpl.java
* extract sending of HL7 into own class HL7Sender
so DicomUtils concern is Dicom stuff
see https://issues.openmrs.org/browse/RAD-209
> RAD-209 Extract hl7snd into own class

- api/src/main/java/org/openmrs/module/radiology/db/hibernate/HibernateRadiologyOrderDAO.java
- api/src/main/java/org/openmrs/module/radiology/db/hibernate/HibernateRadiologyReportDAO.java
- api/src/main/java/org/openmrs/module/radiology/db/hibernate/HibernateStudyDAO.java
- api/src/main/java/org/openmrs/module/radiology/impl/RadiologyServiceImpl.java
- api/src/main/resources/moduleApplicationContext.xml
- api/src/test/java/org/openmrs/module/radiology/impl/RadiologyServiceImplComponentTest.java
see https://issues.openmrs.org/browse/RAD-211
> RAD-211 Change configuration of DAOs to annotation driven

- api/src/main/java/org/openmrs/module/radiology/RadiologyService.java
- api/src/main/java/org/openmrs/module/radiology/impl/RadiologyServiceImpl.java
- api/src/main/resources/moduleApplicationContext.xml
- api/src/test/java/org/openmrs/module/radiology/impl/RadiologyServiceImplComponentTest.java
see https://issues.openmrs.org/browse/RAD-212
> RAD-212 Use autowired in radiology service

- api/src/main/java/org/openmrs/module/radiology/impl/RadiologyServiceImpl.java
- api/src/test/java/org/openmrs/module/radiology/impl/RadiologyServiceImplComponentTest.java
see https://issues.openmrs.org/browse/RAD-213
> RAD-213 Remove service setter methods from radiology service impl

- omod/src/main/java/org/openmrs/module/radiology/web/controller/RadiologyOrderFormController.java
- omod/src/test/java/org/openmrs/module/radiology/web/controller/RadiologyOrderFormControllerTest.java
see https://issues.openmrs.org/browse/RAD-214
> RAD-214 Wrong error message format in radiology order form controller

- api/src/main/java/org/openmrs/module/radiology/RadiologyConstants.java
- api/src/main/java/org/openmrs/module/radiology/RadiologyProperties.java
- api/src/test/java/org/openmrs/module/radiology/RadiologyPropertiesComponentTest.java
- api/src/test/resources/org/openmrs/module/radiology/include/RadiologyServiceComponentTestDataset.xml
- omod/src/main/resources/config.xml
* add DICOM UID org root GP
* use org root in dicom uid study prefix
* rename "dicomApplicationUID" to "dicomUIDApplication"
* rename "dicomStudyUIDSlug" to "dicomUIDTypeStudy"
* move gps in test dataset to top
see https://issues.openmrs.org/browse/RAD-216
> RAD-216 Add org root UID and rename UID GPs

- omod/src/main/resources/messages.properties
- omod/src/main/webapp/radiologyOrderForm.jsp
see https://issues.openmrs.org/browse/RAD-193
> RAD-193 Highlight discontinued order in radiologyOrderForm

- README.md
see https://issues.openmrs.org/browse/RAD-229
> RAD-229 Add codacy badge to readme

- api/src/main/java/org/openmrs/module/radiology/DicomUtils.java
- api/src/main/java/org/openmrs/module/radiology/dicom/DicomWebViewer.java
- api/src/main/java/org/openmrs/module/radiology/hl7/v231/segment/RadiologyOBR.java
- api/src/main/java/org/openmrs/module/radiology/hl7/v231/segment/RadiologyORC.java
- api/src/main/java/org/openmrs/module/radiology/hl7/v231/segment/RadiologyZDS.java
- api/src/main/java/org/openmrs/module/radiology/order/RadiologyOrder.java
- api/src/main/java/org/openmrs/module/radiology/order/RadiologyOrderServiceImpl.java
- api/src/main/java/org/openmrs/module/radiology/study/HibernateRadiologyStudyDAO.java
- api/src/main/java/org/openmrs/module/radiology/study/RadiologyStudy.java
- api/src/main/java/org/openmrs/module/radiology/study/RadiologyStudyDAO.java
- api/src/main/java/org/openmrs/module/radiology/study/RadiologyStudyService.java
- api/src/main/java/org/openmrs/module/radiology/study/RadiologyStudyServiceImpl.java
- api/src/main/resources/RadiologyStudy.hbm.xml
- api/src/test/java/org/openmrs/module/radiology/DicomUtilsComponentTest.java
- api/src/test/java/org/openmrs/module/radiology/dicom/DicomWebViewerTest.java
- api/src/test/java/org/openmrs/module/radiology/hl7/v231/message/RadiologyORMO01Test.java
- api/src/test/java/org/openmrs/module/radiology/hl7/v231/segment/RadiologyOBRTest.java
- api/src/test/java/org/openmrs/module/radiology/hl7/v231/segment/RadiologyZDSTest.java
- api/src/test/java/org/openmrs/module/radiology/order/RadiologyOrderServiceComponentTest.java
- api/src/test/java/org/openmrs/module/radiology/order/RadiologyOrderServiceImplComponentTest.java
- api/src/test/java/org/openmrs/module/radiology/order/RadiologyOrderTest.java
- api/src/test/java/org/openmrs/module/radiology/report/RadiologyReportTest.java
- api/src/test/java/org/openmrs/module/radiology/report/RadiologyReportValidatorTest.java
- api/src/test/java/org/openmrs/module/radiology/study/RadiologyStudyServiceComponentTest.java
- api/src/test/java/org/openmrs/module/radiology/study/RadiologyStudyTest.java
- omod/src/main/java/org/openmrs/module/radiology/web/controller/RadiologyOrderFormController.java
- omod/src/test/java/org/openmrs/module/radiology/test/RadiologyTestData.java
- omod/src/test/java/org/openmrs/module/radiology/web/controller/PortletsControllerTest.java
* rename Study to RadiologyStudy
* rename StudyDAO
* rename HibernateStudyDAO
see https://issues.openmrs.org/browse/RAD-228
> RAD-228 Rename Study to RadiologyStudy

- api/src/main/java/org/dcm4che2/tool/dcmof/MPPSSCP.java
- api/src/main/java/org/openmrs/module/radiology/dicom/DicomUtils.java
- api/src/test/java/org/openmrs/module/radiology/dicom/DicomUtilsComponentTest.java
see https://issues.openmrs.org/browse/RAD-234
> RAD-234 Move DicomUtils to package dicom

- .github/PULL_REQUEST_TEMPLATE.md
- .gitignore
see https://issues.openmrs.org/browse/RAD-137
> RAD-137 Create a pull request template

- .github/PULL_REQUEST_TEMPLATE.md
Refined the pull request template
see https://issues.openmrs.org/browse/RAD-137
> RAD-137 Addition to pull request template

- omod/src/main/java/org/openmrs/module/radiology/order/web/PortletsController.java
- omod/src/main/java/org/openmrs/module/radiology/order/web/RadiologyDashboardController.java
- omod/src/main/java/org/openmrs/module/radiology/order/web/RadiologyOrderFormController.java
- omod/src/main/java/org/openmrs/module/radiology/order/web/RadiologyOrderListController.java
- omod/src/main/java/org/openmrs/module/radiology/report/web/RadiologyReportFormController.java
- omod/src/test/java/org/openmrs/module/radiology/order/web/PortletsControllerTest.java
- omod/src/test/java/org/openmrs/module/radiology/order/web/RadiologyDashboardControllerTest.java
- omod/src/test/java/org/openmrs/module/radiology/order/web/RadiologyOrderFormControllerTest.java
- omod/src/test/java/org/openmrs/module/radiology/report/web/RadiologyReportFormControllerTest.java
* create package org.openmrs.module.radiology.order.web
and move RadiologyOrderControllers to it
* create package org.openmrs.module.radiology.report.web
and move RadiologyReportControllers to it
see https://issues.openmrs.org/browse/RAD-239
> RAD-239 Restructure controller packages

- api/src/main/java/org/openmrs/module/radiology/RadiologyPrivileges.java
- api/src/main/java/org/openmrs/module/radiology/report/RadiologyReportService.java
- api/src/main/resources/liquibase.xml
- omod/src/main/java/org/openmrs/module/radiology/report/web/RadiologyReportFormController.java
- omod/src/main/webapp/portlets/radiologyReportPortlet.jsp
- omod/src/main/webapp/radiologyOrderForm.jsp
Currently there are no privileges controlling the reporting workflow. This PR adds these privileges as described in the JIRA issue. Also the reporting code in the jsp has been moved to the radiologyReportPortlet.jsp
see https://issues.openmrs.org/browse/RAD-171
> RAD-171 Add privileges for reporting

- api/src/main/java/org/openmrs/module/radiology/RadiologyPrivileges.java
- api/src/main/java/org/openmrs/module/radiology/order/RadiologyOrderService.java
- api/src/main/resources/liquibase.xml
- omod/src/main/webapp/portlets/radiologyOrderDiscontinuationPortlet.jsp
- omod/src/main/webapp/radiologyOrderForm.jsp
* Add privilege checks for radiology order discontinuation
* Add privilege "Delete Radiology Order"
* Sort the privileges in radiologyOrderForm.jsp in alphabetical order, which makes managing them easier
see https://issues.openmrs.org/browse/RAD-237
> RAD-237 Add privileges for order discontinuation

- api/src/main/java/org/openmrs/module/radiology/RadiologyPrivileges.java
- api/src/main/java/org/openmrs/module/radiology/order/RadiologyOrderService.java
- api/src/main/resources/liquibase.xml
- omod/src/main/webapp/portlets/discontinuationOrderDisplayPortlet.jsp
- omod/src/main/webapp/portlets/radiologyOrderDisplayPortlet.jsp
- omod/src/main/webapp/radiologyOrderForm.jsp
* Add privilege checks for getting radiology orders
* Add privilege "GetRadiology Orders"
see https://issues.openmrs.org/browse/RAD-241
> RAD-241 Add privileges for getting orders

- api/src/main/java/org/openmrs/module/radiology/order/HibernateRadiologyOrderDAO.java
- api/src/main/java/org/openmrs/module/radiology/report/HibernateRadiologyReportDAO.java
- api/src/main/java/org/openmrs/module/radiology/study/HibernateRadiologyStudyDAO.java
* Add @SuppressWarnings("unchecked") to avoid compiler warnings
see https://issues.openmrs.org/browse/RAD-215
> RAD-215 Resolve compiler warnings

- omod/src/main/resources/messages.properties
- omod/src/main/webapp/portlets/orderSearch.jsp
- omod/src/main/webapp/portlets/radiologyDashboardTab.jsp
- omod/src/main/webapp/portlets/radiologyOrderCreationPortlet.jsp
- omod/src/main/webapp/portlets/radiologyOrderDetailsPortlet.jsp
* add modality names (key=enum name) into message.properities
* use spring:message tag in jsps to access message properities key/value of
modality names
see https://issues.openmrs.org/browse/RAD-235
> RAD-235 Internationalize modality names

- omod/src/main/webapp/portlets/radiologyOrderCreationPortlet.jsp
* remove auto-expire field from radiologyOrderCreationPortlet.jsp
see https://issues.openmrs.org/browse/RAD-250
> RAD-250 Remove autoexpire date field from order form

- omod/src/main/resources/messages.properties
* cleaned messages.properties file of unused
entries.
messages_es.properties will be updated in a later commit since
it has to be pulled from transifex
see https://issues.openmrs.org/browse/RAD-159
> RAD-159 Clean all messages.properties

- omod/src/main/webapp/portlets/orderSearch.jsp
- omod/src/main/webapp/radiologyOrderList.jsp
see https://issues.openmrs.org/browse/RAD-251
> RAD-251 Fix redirect in orderList and Search

- omod/src/main/webapp/radiologyOrderForm.jsp
Prevent unauthorized order discontinuation in UI
see https://issues.openmrs.org/browse/RAD-252
> RAD-252 Prevent unauthorized order discontinuation in UI

- acceptanceTest/resources/testdata.sql
- omod/src/main/java/org/openmrs/module/radiology/order/web/RadiologyOrderFormController.java
- omod/src/main/webapp/radiologyOrderForm.jsp
Add SQL test data for
* Referring physician
* Scheduler
* Performing physician
* Reading physician
see https://issues.openmrs.org/browse/RAD-257
> RAD-257 Add sql file for test data

- api/src/test/java/org/openmrs/module/radiology/RadiologyEncounterMatcherComponentTest.java
- api/src/test/java/org/openmrs/module/radiology/dicom/DicomWebViewerTest.java
- api/src/test/java/org/openmrs/module/radiology/order/RadiologyOrderServiceComponentTest.java
- api/src/test/java/org/openmrs/module/radiology/order/RadiologyOrderServiceImplComponentTest.java
- api/src/test/java/org/openmrs/module/radiology/report/RadiologyReportServiceComponentTest.java
- api/src/test/java/org/openmrs/module/radiology/study/RadiologyStudyServiceComponentTest.java
- omod/src/test/java/org/openmrs/module/radiology/order/web/PatientDashboardRadiologyTabPortletControllerTest.java
- omod/src/test/java/org/openmrs/module/radiology/order/web/PortletsControllerTest.java
- omod/src/test/java/org/openmrs/module/radiology/order/web/RadiologyOrderFormControllerTest.java
* name all @Before methods in test setUp() since its a widely used convention
see https://issues.openmrs.org/browse/RAD-259
> RAD-259 Name all @Before test methods to setUp

- api/src/main/java/org/openmrs/module/radiology/RadiologyConstants.java
- api/src/main/java/org/openmrs/module/radiology/RadiologyPrivileges.java
- api/src/main/java/org/openmrs/module/radiology/RadiologyProperties.java
- api/src/main/java/org/openmrs/module/radiology/RadiologyRoles.java
- api/src/main/java/org/openmrs/module/radiology/order/HibernateRadiologyOrderDAO.java
- api/src/main/java/org/openmrs/module/radiology/order/RadiologyDiscontinuedOrderValidator.java
- api/src/main/java/org/openmrs/module/radiology/order/RadiologyOrderServiceImpl.java
- api/src/main/java/org/openmrs/module/radiology/order/RadiologyOrderValidator.java
- api/src/main/java/org/openmrs/module/radiology/report/HibernateRadiologyReportDAO.java
- api/src/main/java/org/openmrs/module/radiology/report/RadiologyReportServiceImpl.java
- api/src/main/java/org/openmrs/module/radiology/report/RadiologyReportValidator.java
- api/src/main/java/org/openmrs/module/radiology/study/HibernateRadiologyStudyDAO.java
- api/src/main/java/org/openmrs/module/radiology/study/RadiologyStudy.java
- api/src/test/java/org/openmrs/module/radiology/study/RadiologyStudyTest.java
- omod/src/main/java/org/openmrs/module/radiology/order/web/PatientDashboardRadiologyTabPortletController.java
- omod/src/main/java/org/openmrs/module/radiology/order/web/PortletsController.java
- omod/src/main/java/org/openmrs/module/radiology/order/web/RadiologyOrderFormController.java
- omod/src/main/java/org/openmrs/module/radiology/report/web/RadiologyReportFormController.java
* declare variables as final if only assigned once
* remove reflection code in RadiologyStudy.toString()
* remove useless parenthesis
* inline some temp vars
* add private constructor to utility classes
* remove unnecessary ternary operator on expressions that already return
required boolean
see https://issues.openmrs.org/browse/RAD-174
> RAD-174 clean smells

- pom.xml
- tools/formatter/README.md
- tools/formatter/java.xml
- tools/formatter/readme-OpenMRSFormatter.txt
* rename formatter file to java.xml
* rename formatter profile to "OpenMRS Radiology Module" since it differs from
the OpenMRS profile
* update formatter readme
> Rename eclipse formatter file

- api/pom.xml
- omod/pom.xml
* remove overriding of formatter version
* add m2e config so eclipse ignores plugin
> fix pom's formatter plugin configuration

- omod/src/main/webapp/localHeader.jsp
- omod/src/main/webapp/portlets/discontinuationOrderDisplayPortlet.jsp
- omod/src/main/webapp/portlets/orderSearch.jsp
- omod/src/main/webapp/portlets/patientDashboardRadiologyTab.jsp
- omod/src/main/webapp/portlets/patientOverview.jsp
- omod/src/main/webapp/portlets/radiologyOrderCreationPortlet.jsp
- omod/src/main/webapp/portlets/radiologyOrderDetailsPortlet.jsp
- omod/src/main/webapp/portlets/radiologyOrderDiscontinuationPortlet.jsp
- omod/src/main/webapp/portlets/radiologyOrderDisplayPortlet.jsp
- omod/src/main/webapp/portlets/radiologyOrdersTab.jsp
- omod/src/main/webapp/portlets/radiologyReportPortlet.jsp
- omod/src/main/webapp/radiologyDashboardForm.jsp
- omod/src/main/webapp/radiologyOrderForm.jsp
- omod/src/main/webapp/radiologyOrderList.jsp
- omod/src/main/webapp/radiologyReportForm.jsp
- tools/formatter/README.md
Our jsp's have a max width of 75chars, extend to 125 like all other files.
Change from tabs to spaces with indentation of 2 like in js files. Add to
format readme so other know how to configure their formatter in eclipse.
see https://issues.openmrs.org/browse/RAD-269
> RAD-269 Change jsp style

- api/src/main/java/org/openmrs/module/radiology/report/HibernateRadiologyReportDAO.java
- api/src/main/java/org/openmrs/module/radiology/report/RadiologyReport.java
- api/src/main/java/org/openmrs/module/radiology/report/RadiologyReportDAO.java
- api/src/main/java/org/openmrs/module/radiology/report/RadiologyReportEditor.java
- api/src/main/java/org/openmrs/module/radiology/report/RadiologyReportService.java
- api/src/main/java/org/openmrs/module/radiology/report/RadiologyReportServiceImpl.java
- api/src/test/java/org/openmrs/module/radiology/report/RadiologyReportEditorComponentTest.java
- api/src/test/java/org/openmrs/module/radiology/report/RadiologyReportServiceComponentTest.java
- omod/src/main/java/org/openmrs/module/radiology/report/web/RadiologyReportFormController.java
- omod/src/test/java/org/openmrs/module/radiology/report/web/RadiologyReportFormControllerTest.java
* Add dao getRadiologyReportByUuid()
* Add property editor for radiology reports
* Add unit tests for radiology reports property editor
see https://issues.openmrs.org/browse/RAD-255
> RAD-255 Use PropertyEditor for radiology reports

- .travis.yml
- README.md
- api/src/main/java/org/openmrs/module/radiology/order/RadiologyOrder.java
- api/src/main/java/org/openmrs/module/radiology/order/RadiologyOrderService.java
- api/src/main/java/org/openmrs/module/radiology/order/RadiologyOrderServiceImpl.java
- api/src/main/resources/RadiologyReport.hbm.xml
- api/src/main/resources/RadiologyStudy.hbm.xml
- api/src/test/java/org/openmrs/module/radiology/order/RadiologyOrderServiceComponentTest.java
- api/src/test/java/org/openmrs/module/radiology/order/RadiologyOrderTest.java
- api/src/test/java/org/openmrs/module/radiology/report/RadiologyReportServiceComponentTest.java
- api/src/test/resources/org/openmrs/module/radiology/include/RadiologyEncounterMatcherComponentTestDataset.xml
- api/src/test/resources/org/openmrs/module/radiology/include/RadiologyOrderServiceComponentTestDataset.xml
- api/src/test/resources/org/openmrs/module/radiology/include/RadiologyReportServiceComponentTestDataset.xml
- api/src/test/resources/org/openmrs/module/radiology/include/RadiologyStudyServiceComponentTestDataset.xml
- omod/pom.xml
- omod/src/main/resources/config.xml
- pom.xml
* upgrade openmrs dependency to 2.0-SNAPSHOT
* compile with java8
* add dependency in omod to legacyui since openmrs-core doesnt contain ui
anymore
* travis ci build only on java8
* update readme
* org.openmrs.util.HibernateEnumType was deleted, switch to hibernates enum type in mapping xml's
* add dependency on legacyui to omod
* dependencies of emrapi should have scope test
see https://issues.openmrs.org/browse/RAD-59
> RAD-59 Update module to run on Platform 2.0

- omod/src/test/java/org/openmrs/module/radiology/order/web/search/RadiologyOrderSearchHandlerComponentTest.java
- omod/src/test/java/org/openmrs/module/radiology/order/web/search/RadiologyOrderSearchHandlerTest.java
- omod/src/test/resources/RadiologyOrderSearchHandlerComponentTestDataset.xml
Added more component tests with own dataset xml to RadiologyOrderSearchHandler.
* add RadiologyOrderSearchHandlerComponentTestDataset.xml
* add tests to RadiologyOrderSearchHandlerComponentTest
see https://issues.openmrs.org/browse/RAD-280
> RAD-280 Add tests to RadiologyOrderSearchHandler

- omod/src/main/java/org/openmrs/module/radiology/order/web/search/RadiologyOrderSearchHandler.java
- omod/src/main/webapp/portlets/patientDashboardRadiologyTab.jsp
- omod/src/main/webapp/portlets/radiologyOrdersTab.jsp
- omod/src/main/webapp/template/includeDatatablesWithDefaults.jsp
- omod/src/test/java/org/openmrs/module/radiology/order/web/search/RadiologyOrderSearchHandlerComponentTest.java
- pom.xml
Make use of new totalCount property that is returned by BasePageableResult if
totalCount request parameter is supported.
* depend on webservices 2.15-SNAPSHOT
* add totalCount as optional parameter to RadiologyOrderSearchHandler to
support new webservices property totalCount
* use new totalCount property by sending totalCount=true in ajax requests
see https://issues.openmrs.org/browse/RAD-288
> RAD-288 Fix paging in radiologyOrders lists

- omod/src/main/resources/messages.properties
- omod/src/main/webapp/orders/discontinuationOrderDisplayPortlet.jsp
- omod/src/main/webapp/orders/radiologyOrderCreationPortlet.jsp
- omod/src/main/webapp/orders/radiologyOrderDetailsPortlet.jsp
- omod/src/main/webapp/portlets/patientDashboardRadiologyTab.jsp
- omod/src/main/webapp/portlets/radiologyOrdersTab.jsp
* add order reason to radiologyOrderForm
* add childrows to datatables radiology orders with orderReason/NonCoded and
instruction
see https://issues.openmrs.org/browse/RAD-RAD-286
> RAD-286 Add order reason to order entry page

- api/src/main/java/org/openmrs/module/radiology/study/HibernateRadiologyStudyDAO.java
- api/src/main/java/org/openmrs/module/radiology/study/RadiologyStudyDAO.java
- api/src/main/java/org/openmrs/module/radiology/study/RadiologyStudyService.java
- api/src/main/java/org/openmrs/module/radiology/study/RadiologyStudyServiceImpl.java
- api/src/test/java/org/openmrs/module/radiology/study/RadiologyStudyServiceComponentTest.java
Remove the ByXXX substring from RadiologyStudyService.getStudyByStudyId
to adhere to openmrs-core and now the modules convention for get method on
internal id
see https://issues.openmrs.org/browse/RAD-285
> RAD-285 Rename RadiologyStudyService.getStudy

- api/src/main/java/org/openmrs/module/radiology/order/HibernateRadiologyOrderDAO.java
- api/src/main/java/org/openmrs/module/radiology/order/RadiologyOrderDAO.java
- api/src/main/java/org/openmrs/module/radiology/order/RadiologyOrderService.java
- api/src/main/java/org/openmrs/module/radiology/order/RadiologyOrderServiceImpl.java
- api/src/test/java/org/openmrs/module/radiology/order/RadiologyOrderServiceComponentTest.java
- api/src/test/resources/org/openmrs/module/radiology/include/RadiologyEncounterMatcherComponentTestDataset.xml
- api/src/test/resources/org/openmrs/module/radiology/include/RadiologyOrderServiceComponentTestDataset.xml
- api/src/test/resources/org/openmrs/module/radiology/include/RadiologyReportServiceComponentTestDataset.xml
- api/src/test/resources/org/openmrs/module/radiology/include/RadiologyStudyServiceComponentTestDataset.xml
- omod/src/main/java/org/openmrs/module/radiology/order/web/resource/RadiologyOrderResource.java
- omod/src/test/java/org/openmrs/module/radiology/order/web/resource/RadiologyOrderResourceComponentTest.java
- omod/src/test/java/org/openmrs/module/radiology/order/web/resource/RadiologyOrderResourceTest.java
- omod/src/test/resources/RadiologyOrderResourceComponentTestDataset.xml
- omod/src/test/resources/RadiologyOrderSearchHandlerComponentTestDataset.xml
* add RadiologyOrderService.getRadiologyOrderByUuid
* use it in RadiologyOrderResource REST
* add DAO method for it
* fix test method names in RadiologyOrderServiceComponentTest
* add uuid's to all orders in our testdata sets
see https://issues.openmrs.org/browse/RAD-284
> RAD-284 Add RadiologyOrderService.getRadiologyOrderByUuid

- api/src/main/java/org/openmrs/module/radiology/order/RadiologyOrderService.java
Explicitly make new method public, it is implicitly but it is a convention in the module so stick to it.
see https://issues.openmrs.org/browse/RAD-284
> RAD-284 Explicitly make new method public

- api/src/main/java/org/openmrs/module/radiology/study/HibernateRadiologyStudyDAO.java
- api/src/main/java/org/openmrs/module/radiology/study/RadiologyStudyDAO.java
- api/src/main/java/org/openmrs/module/radiology/study/RadiologyStudyService.java
- api/src/main/java/org/openmrs/module/radiology/study/RadiologyStudyServiceImpl.java
- api/src/test/java/org/openmrs/module/radiology/study/RadiologyStudyServiceComponentTest.java
Add RadiologyStudyService.getRadiologyStudyByUuid()
see https://issues.openmrs.org/browse/RAD-296
> RAD-296 Add getRadiologyStudyByUuid()

- omod/src/main/webapp/orders/radiologyOrderCreationSegment.jsp
show scheduled date in order form only when urgency is set to on scheduled date
* fix error div at top
* use jquery to hide, clear scheduledDate and its error span when urgencySelect changes to
ON_SCHEDULED_DATE
* put scheduledDate in line with urgencySelect
see https://issues.openmrs.org/browse/RAD-188
> RAD-188 Show scheduled date only for correct urgency

- api/src/main/java/org/openmrs/module/radiology/study/HibernateRadiologyStudyDAO.java
- api/src/main/java/org/openmrs/module/radiology/study/RadiologyStudyDAO.java
- api/src/main/java/org/openmrs/module/radiology/study/RadiologyStudyService.java
- api/src/main/java/org/openmrs/module/radiology/study/RadiologyStudyServiceImpl.java
- api/src/test/java/org/openmrs/module/radiology/study/RadiologyStudyServiceComponentTest.java
starting with RadiologyStudyService
* add class javadoc
* harmonize javadocs
* remove throws IAE declarations
* return null if given null for getters that look for unique result
see https://issues.openmrs.org/browse/RAD-297
> RAD-297 Harmonize service getters RadiologyStudy

- api/src/main/java/org/openmrs/module/radiology/order/RadiologyOrderDAO.java
- api/src/main/java/org/openmrs/module/radiology/order/RadiologyOrderService.java
- api/src/main/java/org/openmrs/module/radiology/order/RadiologyOrderServiceImpl.java
- api/src/main/java/org/openmrs/module/radiology/study/RadiologyStudyDAO.java
- api/src/main/java/org/openmrs/module/radiology/study/RadiologyStudyService.java
- api/src/test/java/org/openmrs/module/radiology/order/RadiologyOrderServiceComponentTest.java
continue with RadiologyOrderService
* add class javadoc
* harmonize javadocs
* remove throws IAE declarations
* throw IAE if given null if param required
* minor javadoc adjustment in RadiologyStudy part
see https://issues.openmrs.org/browse/RAD-297
> RAD-297 Harmonize service getters RadiologyOrder

- api/src/main/java/org/openmrs/module/radiology/order/RadiologyOrderService.java
- api/src/main/java/org/openmrs/module/radiology/report/RadiologyReportDAO.java
- api/src/main/java/org/openmrs/module/radiology/report/RadiologyReportService.java
- api/src/main/java/org/openmrs/module/radiology/report/RadiologyReportServiceImpl.java
- api/src/main/java/org/openmrs/module/radiology/study/RadiologyStudyService.java
- api/src/test/java/org/openmrs/module/radiology/report/RadiologyReportServiceComponentTest.java
- api/src/test/java/org/openmrs/module/radiology/study/RadiologyStudyServiceComponentTest.java
continue with RadiologyReportService
* add class javadoc
* harmonize javadocs
* remove throws IAE declarations
* throw IAE if given null if param required
* and use "should" instead of "shall" in RadiologyOrderService to be consistent>
see https://issues.openmrs.org/browse/RAD-297
> RAD-297 Harmonize service getters RadiologyReport

- pom.xml
see https://issues.openmrs.org/browse/RAD-230
> RAD-230 Add license and issue info to root pom

- omod/pom.xml
new class paths missing from jacoco config
* add jacoco include path for new REST classes
see https://issues.openmrs.org/browse/RAD-301
> RAD-301 Add REST paths to jacoco

- omod/src/main/java/org/openmrs/module/radiology/report/web/RadiologyReportFormController.java
- omod/src/test/java/org/openmrs/module/radiology/report/web/RadiologyReportFormControllerTest.java
cleaned RadiologyReportFormController
* updated javadocs
* remove unnecessary filling of model and view on redirect
* remove modelAttribute name if it is same as default
> Update RadiologyReportFormController and its tests

- omod/src/main/java/org/openmrs/module/radiology/order/web/DiscontinuationOrderRequest.java
- omod/src/main/java/org/openmrs/module/radiology/order/web/RadiologyOrderFormController.java
- omod/src/test/java/org/openmrs/module/radiology/order/web/RadiologyOrderFormControllerTest.java
* autowire RadiologyOrderValidator
* udpate javadocs to match module conventions
* remove context.isAuthenticated checks, this is done in the jsps
* remove unnecessary ModelAttribute names if same as default
* remove unnecessary RequestParam required=true since its default
* remove unnecessary parameters for saveRadiologyOrder POST method
* rename methods, remove duplicate info from their names. POST is known via
RequestMapping
> Update RadiologyOrderFormController and its tests

- omod/src/main/resources/messages.properties
- omod/src/main/webapp/orders/discontinuationOrderDisplaySegment.jsp
- omod/src/main/webapp/orders/radiologyOrderCreationSegment.jsp
- omod/src/main/webapp/orders/radiologyOrderDetailsSegment.jsp
TestOrder already has cliniclHistory, add it as textarea to the
radiologyOrderForm.
see https://issues.openmrs.org/browse/RAD-302
> RAD-302 Add clinicalHistory field to order form

- omod/src/main/resources/config.xml
- pom.xml
* Update emr api version in pom.xml
* Remove global property from config.xml
see https://issues.openmrs.org/browse/RAD-275
> RAD-275 Upgrade emrapi to 1.14

- omod/src/main/java/org/openmrs/module/radiology/report/web/resource/RadiologyReportResource.java
- omod/src/test/java/org/openmrs/module/radiology/report/web/resource/RadiologyReportControllerComponentTest.java
- omod/src/test/java/org/openmrs/module/radiology/report/web/resource/RadiologyReportResourceComponentTest.java
- omod/src/test/java/org/openmrs/module/radiology/report/web/resource/RadiologyReportResourceTest.java
- omod/src/test/resources/RadiologyReportResourceComponentTestDataset.xml
Start with adding GET request handling
for getting a single RadiologyReport by its UUID.
* add REST resource for RadiologyReport
* add dataset xml for component tests
* add unit tests
* add component tests
see https://issues.openmrs.org/browse/RAD-281
> RAD-281 Add first REST API for RadiologyReport

- api/src/main/java/org/openmrs/module/radiology/report/RadiologyReportSearchCriteria.java
- api/src/main/java/org/openmrs/module/radiology/report/RadiologyReportService.java
- api/src/test/java/org/openmrs/module/radiology/report/RadiologyReportServiceComponentTest.java
- omod/src/main/java/org/openmrs/module/radiology/order/web/search/RadiologyOrderSearchHandler.java
- omod/src/main/java/org/openmrs/module/radiology/report/web/resource/RadiologyReportResource.java
- omod/src/main/java/org/openmrs/module/radiology/report/web/search/RadiologyReportSearchHandler.java
- omod/src/test/java/org/openmrs/module/radiology/report/web/search/RadiologyReportSearchHandlerComponentTest.java
- omod/src/test/resources/RadiologyReportSearchHandlerComponentTestDataset.xml
Provide search capabilities for the RadiologyReport resource so that a
user of the API can get all RadiologyReports within a certain date
range.
* add RadiologyReportSearchHandler
* add component tests for RadiologyReportSearchHandler
* add test to RadiologyReportServiceComponentTest
* add RadiologyReportSearchHandlerComponentTestDataset.xml for component tests
see https://issues.openmrs.org/browse/RAD-282
> RAD-282 Add REST search for RadiologyReport by date

- api/src/main/java/org/openmrs/module/radiology/report/HibernateRadiologyReportDAO.java
- api/src/main/java/org/openmrs/module/radiology/report/RadiologyReportSearchCriteria.java
- api/src/main/java/org/openmrs/module/radiology/report/RadiologyReportService.java
- api/src/test/java/org/openmrs/module/radiology/report/RadiologyReportServiceComponentTest.java
- api/src/test/resources/org/openmrs/module/radiology/include/RadiologyReportServiceComponentTestDataset.xml
- omod/src/main/java/org/openmrs/module/radiology/report/web/search/RadiologyReportSearchHandler.java
- omod/src/test/java/org/openmrs/module/radiology/report/web/search/RadiologyReportSearchHandlerComponentTest.java
- omod/src/test/resources/RadiologyReportResourceComponentTestDataset.xml
- omod/src/test/resources/RadiologyReportSearchHandlerComponentTestDataset.xml
Provide search capabilities for the RadiologyReport resource so that
a user of the API can get all RadiologyReports of a specific author.
* add search parameter to RadiologyReportSearchHandler
* add component test for new paramter
* modify dao method
* add new attribute to RadiologyReportSearchCriteria
* add test to RadiologyReportServiceComponentTest
see https://issues.openmrs.org/browse/RAD-283
> RAD-283 REST search for RadiologyReport by principalResultsInterpreter

- omod/src/main/java/org/openmrs/module/radiology/report/web/search/RadiologyReportSearchHandler.java
- omod/src/main/resources/messages.properties
- omod/src/main/webapp/portlets/radiologyOrdersTab.jsp
- omod/src/main/webapp/portlets/radiologyReportsTab.jsp
- omod/src/main/webapp/radiologyDashboardForm.jsp
- omod/src/test/java/org/openmrs/module/radiology/report/web/search/RadiologyReportSearchHandlerComponentTest.java
* add report tab into radiology dashboard
* add new entries in message.properties
* ensure no duplicate ids exist in radiology dashboard document with ordersTab and reportsTab
included
see https://issues.openmrs.org/browse/RAD-136
> RAD-136 Create a list with radiology reports

- omod/src/main/resources/messages.properties
- omod/src/main/webapp/reports/radiologyReportForm.jsp
* show jquery-ui-dialog when unclaiming a report with text
see https://issues.openmrs.org/browse/RAD-187
> RAD-187 Add alert when unclaiming a report

- api/src/main/java/org/openmrs/module/radiology/report/HibernateRadiologyReportDAO.java
- api/src/main/java/org/openmrs/module/radiology/report/RadiologyReportSearchCriteria.java
- api/src/main/java/org/openmrs/module/radiology/report/RadiologyReportService.java
- api/src/test/java/org/openmrs/module/radiology/report/RadiologyReportSearchCriteriaTest.java
- api/src/test/java/org/openmrs/module/radiology/report/RadiologyReportServiceComponentTest.java
- omod/src/main/java/org/openmrs/module/radiology/report/web/RadiologyReportsTabPortletController.java
- omod/src/main/java/org/openmrs/module/radiology/report/web/search/RadiologyReportSearchHandler.java
- omod/src/main/resources/messages.properties
- omod/src/main/resources/webModuleApplicationContext.xml
- omod/src/main/webapp/portlets/radiologyReportsTab.jsp
- omod/src/test/java/org/openmrs/module/radiology/report/web/search/RadiologyReportSearchHandlerComponentTest.java
* modify dao method
* add status parameter to RadiologyReportSearchCriteria
* add tests for RadiologyReportSearchCriteria
* add tests to RadiologyReportServiceComponentTest
* add search paramter to RadiologyReportSearchHandler
* add tests for RadiologyReportSearchHandler
* add entries to messages.properties
* add select-item for status to radiologyReportsTab.jsp
see https://issues.openmrs.org/browse/RAD-315
> RAD-315 REST search for RadiologyReport by status

- omod/src/main/resources/messages.properties
- omod/src/main/webapp/portlets/radiologyReportsTab.jsp
- omod/src/main/webapp/tags/providerField.tag
As a radiologist I want to find a report by its principal results
interpreter
* add providerField.tag
* add new tag to radiologyReportsTab.jsp and add new parameter to ajax
request
* add entry to messages.properties
see https://issues.openmrs.org/browse/RAD-327
> RAD-327 Find report by principalResultsInterpreter

- README.md
- docker-compose.yml
- omod/pom.xml
- omod/src/main/docker/Dockerfile
- pom.xml
* use spotify docker plugin to create image
* update readme
* add docker-compose
see https://issues.openmrs.org/browse/RAD-333
> RAD-333 Use docker for setup

- README.md
* be more explicit on build prerequisites
* fix error in docker:build command
see https://issues.openmrs.org/browse/RAD-333
> RAD-333 Update readme

- omod/src/main/webapp/radiologyDashboardForm.jsp
- omod/src/main/webapp/resources/css/radiology.css
* replace javascript code to display tabs with jquery-ui tabs in
radiologDashboardForm.jsp
* replace tab styling in radiology.css
see https://issues.openmrs.org/browse/RAD-331
> RAD-331 Replace tab magic with jqueryui tabs

- omod/pom.xml
- omod/src/main/webapp/orders/radiologyOrderList.jsp
- omod/src/main/webapp/portlets/patientDashboardRadiologyTab.jsp
- omod/src/main/webapp/portlets/radiologyOrdersTab.jsp
- omod/src/main/webapp/portlets/radiologyReportsTab.jsp
- omod/src/main/webapp/resources/scripts/radiology.js
- omod/src/main/webapp/template/includeScripts.jsp
- omod/src/test/javascript/helpers/definitions.js
- omod/src/test/javascript/helpers/jasmine-jquery.js
- omod/src/test/javascript/helpers/jquery-1.8.1.js
- omod/src/test/javascript/radiologySpec.js
* add jasmine to test js code
* add radiology.js
* add tests for radiology.js
* modify jsp files to use extracted code
* add radiology.js to includeScripts.jsp
see https://issues.openmrs.org/browse/RAD-270
> RAD-270 Extract frequently used code into js file

- acceptanceTest/resources/demo-data.sql
Add new ADD, GET and VIEW Radiology Report Templates privilege to demo-data.sql role
"Reading Physician" so they can see the report templates tab.
* regroup the view privileges
see https://issues.openmrs.org/browse/RAD-272
> RAD-272 Add new template privileges to demo-data

- api/src/main/java/org/openmrs/module/radiology/order/HibernateRadiologyOrderDAO.java
- api/src/main/java/org/openmrs/module/radiology/order/RadiologyOrderSearchCriteria.java
- api/src/main/java/org/openmrs/module/radiology/order/RadiologyOrderService.java
- api/src/test/java/org/openmrs/module/radiology/order/RadiologyOrderSearchCriteriaTest.java
- api/src/test/java/org/openmrs/module/radiology/order/RadiologyOrderServiceComponentTest.java
- api/src/test/resources/org/openmrs/module/radiology/include/RadiologyOrderServiceComponentTestDataset.xml
* Add voided to RadiologyOrderSearchCriteria, including tests
see https://issues.openmrs.org/browse/RAD-279
> RAD-279 Add voided to RadiologyOrderSearchCriteria

- README.md
- docs/DEVELOPER.md
- docs/FORMATTER.md
add DEVELOPER.md to docs and link from README.md
move formatter readme to docs/FORMATTER.md
see https://issues.openmrs.org/browse/RAD-335
> RAD-335 Create developer readme

- api/src/main/java/org/openmrs/module/radiology/report/template/HibernateMrrtReportTemplateDAO.java
- api/src/main/java/org/openmrs/module/radiology/report/template/MrrtReportTemplateDAO.java
- api/src/main/java/org/openmrs/module/radiology/report/template/MrrtReportTemplateSearchCriteria.java
- api/src/main/java/org/openmrs/module/radiology/report/template/MrrtReportTemplateService.java
- api/src/main/java/org/openmrs/module/radiology/report/template/MrrtReportTemplateServiceImpl.java
- api/src/test/java/org/openmrs/module/radiology/report/template/MrrtReportTemplateSearchCriteriaTest.java
- api/src/test/java/org/openmrs/module/radiology/report/template/MrrtReportTemplateServiceComponentTest.java
- omod/src/main/java/org/openmrs/module/radiology/report/template/web/search/MrrtReportTemplateSearchHandler.java
- omod/src/test/java/org/openmrs/module/radiology/report/template/web/search/MrrtReportTemplateSearchHandlerComponentTest.java
- omod/src/test/java/org/openmrs/module/radiology/report/template/web/search/MrrtReportTemplateSearchHandlerTest.java
RAD-312 add MrrtReportTemplateSearchCriteria
* added MrrtReportTemplateSearchCriteria
* deleted MrrtReportTemplateService.getMrrtReportTemplateByTitle(String)
* added MrrtReportTemplateService.getMrrtReportTemplates(MrrtReportTemplateSearchCriteria)
* added test cases for MrrtReportTemplateSearchCriteria and MrrtReportTemplateService.getMrrtReportTemplates()
* fixed other tests including MrrtReportTemplateServiceComponentTest, MrrtReportTemplateSearchHandlerTest, MrrtReportTemplateSearchHandlerComponentTest to reflect latest changes
see https://issues.openmrs.org/browse/RAD-312
> RAD-312 add MrrtReportTemplateSearchCriteria

- api/src/main/java/org/openmrs/module/radiology/order/HibernateRadiologyOrderDAO.java
- api/src/main/java/org/openmrs/module/radiology/order/RadiologyOrderSearchCriteria.java
- api/src/main/java/org/openmrs/module/radiology/order/RadiologyOrderService.java
- api/src/test/java/org/openmrs/module/radiology/order/RadiologyOrderSearchCriteriaTest.java
- api/src/test/java/org/openmrs/module/radiology/order/RadiologyOrderServiceComponentTest.java
- api/src/test/resources/org/openmrs/module/radiology/include/RadiologyOrderServiceComponentTestDataset.xml
* Add urgency to RadiologyOrderSearchCriteria including tests
see https://issues.openmrs.org/browse/RAD-321
> RAD-321 Add urgency to RadiologyOrderSearchCriteria

- acceptanceTest/resources/demo-data.sql
- api/src/main/java/org/openmrs/module/radiology/RadiologyPrivileges.java
- api/src/main/java/org/openmrs/module/radiology/study/RadiologyStudyService.java
- api/src/main/resources/liquibase.xml
Add privileges
* Add Radiology Studies
* Edit Radiology Studies
* Get Radiology Studies
to RadiologyPrivileges and to the database using liquibase.xml
Add authorized annotations in the RadiologyStudyService
see https://issues.openmrs.org/browse/RAD-347
> RAD-347 Add privileges for RadiologyStudyService

- README.md
- pom.xml
openmrs-core 2.0.0 has been released so SNAPSHOT isnt available anymore
> Update to openmrs-core 2.0.0

- docs/DEMO-DATA.md
> Update demo-data.sql path in DEMO-DATA.md

- api/src/main/resources/RadiologyStudy.hbm.xml
- api/src/main/resources/liquibase.xml
Add not null contraint for RadiologyStudy.studyInstanceUid in
RadiologyStudy.hbm.xml and not null in db in table radiology_study
see https://issues.openmrs.org/browse/RAD-328
> RAD-328 Add not null contraint for study instance uid

- api/src/main/java/org/openmrs/module/radiology/order/HibernateRadiologyOrderDAO.java
- api/src/main/java/org/openmrs/module/radiology/order/RadiologyOrderSearchCriteria.java
- api/src/main/java/org/openmrs/module/radiology/order/RadiologyOrderService.java
- api/src/test/java/org/openmrs/module/radiology/order/RadiologyOrderSearchCriteriaTest.java
- api/src/test/java/org/openmrs/module/radiology/order/RadiologyOrderServiceComponentTest.java
* Add accession number to RadiologyOrderSearchCriteria, including Tests
see https://issues.openmrs.org/browse/RAD-343
> RAD-343 Add accession number to RadiologyOrderSearchCriteria

- omod/src/main/java/org/openmrs/module/radiology/order/web/RadiologyOrderTabPortletController.java
- omod/src/main/java/org/openmrs/module/radiology/order/web/search/RadiologyOrderSearchHandler.java
- omod/src/main/java/org/openmrs/module/radiology/report/web/search/RadiologyReportSearchHandler.java
- omod/src/main/resources/messages.properties
- omod/src/main/webapp/orders/radiologyOrderCreationSegment.jsp
- omod/src/main/webapp/orders/radiologyOrderDetailsSegment.jsp
- omod/src/main/webapp/portlets/radiologyOrdersTab.jsp
- omod/src/main/webapp/portlets/radiologyReportTemplatesTab.jsp
- omod/src/main/webapp/portlets/radiologyReportsTab.jsp
- omod/src/main/webapp/resources/css/radiology.css
- omod/src/test/java/org/openmrs/module/radiology/order/web/search/RadiologyOrderSearchHandlerComponentTest.java
- omod/src/test/java/org/openmrs/module/radiology/order/web/search/RadiologyOrderSearchHandlerTest.java
- omod/src/test/java/org/openmrs/module/radiology/report/web/search/RadiologyReportSearchHandlerComponentTest.java
- omod/src/test/resources/RadiologyOrderSearchHandlerComponentTestDataset.xml
* add new parameter to radiology order rest search
* add select for urgencies to radiologyOrderTab.jsp
* add and modify entries in messages.properties
* add css styling for select tag
* add component tests for RadiologyOrderSearchHandler
see https://issues.openmrs.org/browse/RAD-321
> RAD-321 REST search for RadiologyOrder by urgency

- omod/src/main/java/org/openmrs/module/radiology/order/web/resource/RadiologyOrderResource.java
- omod/src/main/java/org/openmrs/module/radiology/order/web/search/RadiologyOrderSearchHandler.java
- omod/src/main/resources/messages.properties
- omod/src/main/webapp/portlets/radiologyOrdersTab.jsp
- omod/src/test/java/org/openmrs/module/radiology/order/web/resource/RadiologyOrderResourceComponentTest.java
- omod/src/test/java/org/openmrs/module/radiology/order/web/resource/RadiologyOrderResourceTest.java
- omod/src/test/java/org/openmrs/module/radiology/order/web/search/RadiologyOrderSearchHandlerComponentTest.java
* add new parameter to RadiologyOrderSearchHandler
* add entry to message.properties
* add accession number input field to filters in radiologyOrdersTab
* add component tests for RadiologyOrderSearchHandler
see https://issues.openmrs.org/browse/RAD-343
> RAD-343 REST search for RadiologyOrder by accession number

- acceptanceTest/resources/demo-data.sql
- docs/DEMO-DATA.md
* it missing was causing REST services to return "" for patient.display
* add accession numbers to demo-data.md
see https://issues.openmrs.org/browse/RAD-330
> RAD-330 Add patient identifiers to demo-data

- pom.xml
this release includes
https://issues.openmrs.org/browse/LUI-81
which enables us to validate the GP of DICOM root org UID
https://issues.openmrs.org/browse/RAD-107
> Update legacyui dependency to 0.3.1

- omod/src/main/resources/messages.properties
- omod/src/main/webapp/portlets/radiologyOrdersTab.jsp
- omod/src/main/webapp/portlets/radiologyReportTemplatesTab.jsp
- omod/src/main/webapp/portlets/radiologyReportsTab.jsp
- omod/src/main/webapp/tags/patientField.tag
- omod/src/main/webapp/tags/providerField.tag
* add placeholder and remove label of filters in radiologyReportsTab and
radiologyReportsTemplateTab
* modify entries in messages.properties
> Change filter design

- omod/src/main/java/org/openmrs/module/radiology/order/web/search/RadiologyOrderSearchHandler.java
- omod/src/main/java/org/openmrs/module/radiology/report/web/search/RadiologyReportSearchHandler.java
- omod/src/main/resources/messages.properties
- omod/src/main/webapp/portlets/patientDashboardRadiologyTab.jsp
- omod/src/main/webapp/portlets/radiologyOrdersTab.jsp
- omod/src/test/java/org/openmrs/module/radiology/order/web/search/RadiologyOrderSearchHandlerComponentTest.java
- omod/src/test/resources/RadiologyOrderSearchHandlerComponentTestDataset.xml
* add new parameters to radiology order search handler
* add input field to radiologyOrderTab.jsp
* add stopped date column to datatable in radiologyOrderTab.jsp and
patientDashboardRadiologyTab.jsp
* add and modify entries in messages.properties
* add component tests for RadiologyOrderSearchHandler
see https://issues.openmrs.org/browse/RAD-320
> RAD-320 REST search for RadiologyOrder by effective start date

- omod/pom.xml
- omod/src/main/docker/Dockerfile
* released docker images for openmrs 2.0.0
for teleivo/openmrs-platform and teleivo/openmrs-platform-mysql to docker hub
* update references in omod/pom.xml and the Dockerfile to use these images
> Update docker setup to 2.0.0

- checkstyle.xml
- docs/DEVELOPER.md
* udpate checktyle.xml
* update DEVELOPER.md for it
also imported the checkstyle.xml into codacy so we are in sync
see https://issues.openmrs.org/browse/RAD-261
> RAD-261 Use codacy autosync

- docs/IMPORT-RADLEX.md
Add readme for importing radlex catalog
readme shows how to transform radlex csv file into sql file ready to be
imported
> Add readme for importing radlex catalog

- api/src/main/java/org/openmrs/module/radiology/study/RadiologyStudyEditor.java
- api/src/test/java/org/openmrs/module/radiology/study/RadiologyStudyEditorComponentTest.java
* Add RadiologyStudyPropertyEditor including tests
see https://issues.openmrs.org/browse/RAD-256
> RAD-256 Use PropertyEditor for radiology studies

- api/src/main/java/org/openmrs/module/radiology/order/HibernateRadiologyOrderDAO.java
- api/src/main/java/org/openmrs/module/radiology/order/RadiologyOrderDAO.java
- api/src/main/java/org/openmrs/module/radiology/order/RadiologyOrderSearchCriteria.java
- api/src/main/java/org/openmrs/module/radiology/order/RadiologyOrderService.java
- api/src/test/java/org/openmrs/module/radiology/order/RadiologyOrderServiceComponentTest.java
* Clean code
* Add additional test
see https://issues.openmrs.org/browse/RAD-317
> RAD-317 Clean up RadiologyOrderSearchCriteria

- api/src/main/java/org/openmrs/module/radiology/report/template/MrrtReportTemplateEditor.java
- api/src/test/java/org/openmrs/module/radiology/report/template/MrrtReportTemplateEditorComponentTest.java
- omod/src/main/java/org/openmrs/module/radiology/report/template/MrrtReportTemplateFormController.java
- omod/src/test/java/org/openmrs/module/radiology/report/template/MrrtReportTemplateFormControllerTest.java
Add PropertyEditor for MrrtReportTemplate and use it in controller
see https://issues.openmrs.org/browse/RAD-350
> RAD-350 Add PropertyEditor for MrrtReportTemplate

- api/src/main/java/org/openmrs/module/radiology/dicom/code/PerformedProcedureStepStatus.java
- api/src/main/java/org/openmrs/module/radiology/order/RadiologyOrderSearchCriteria.java
- api/src/main/java/org/openmrs/module/radiology/order/RadiologyOrderServiceImpl.java
- api/src/main/java/org/openmrs/module/radiology/report/RadiologyReportEditor.java
- api/src/main/java/org/openmrs/module/radiology/report/RadiologyReportServiceImpl.java
- api/src/main/java/org/openmrs/module/radiology/report/RadiologyReportValidator.java
- api/src/main/java/org/openmrs/module/radiology/report/template/DefaultMrrtReportTemplateFileParser.java
- api/src/main/java/org/openmrs/module/radiology/report/template/HibernateMrrtReportTemplateDAO.java
- api/src/main/java/org/openmrs/module/radiology/report/template/MrrtReportTemplateServiceImpl.java
- api/src/main/java/org/openmrs/module/radiology/util/DecimalUuid.java
- omod/src/main/java/org/openmrs/module/radiology/order/web/DiscontinuationOrderRequest.java
- omod/src/main/java/org/openmrs/module/radiology/order/web/RadiologyOrderFormController.java
- omod/src/main/java/org/openmrs/module/radiology/order/web/resource/RadiologyOrderResource.java
- omod/src/main/java/org/openmrs/module/radiology/report/template/MrrtReportTemplateFormController.java
- omod/src/main/java/org/openmrs/module/radiology/report/template/web/resource/MrrtReportTemplateResource.java
- omod/src/main/java/org/openmrs/module/radiology/report/template/web/search/MrrtReportTemplateSearchHandler.java
Cleanup some code smells found in our checkstyle rules
> Clean up some code smells

- README.md
* setup the repo on versioneye.com manually not using its maven plugin yet
* added badge to readme
see https://issues.openmrs.org/browse/RAD-338
> RAD-338 Setup version and security alerts

- pom.xml
version 2.11 was released over a year ago
> Update maven license plugin to latest version

- pom.xml
version 2.4 was released over 4 years ago.
latest 2.10 is already out for 1 year
> Update maven dependency plugin

- pom.xml
Release 0.7.7 (2016/06/06) former version was about 1 year ago
> Update jacoco maven plugin to 0.7.7

- pom.xml
> Update coveralls plugin to 4.2.0

- api/src/main/java/org/openmrs/module/radiology/report/HibernateRadiologyReportDAO.java
- api/src/main/java/org/openmrs/module/radiology/report/RadiologyReport.java
- api/src/main/java/org/openmrs/module/radiology/report/RadiologyReportEditor.java
- api/src/main/java/org/openmrs/module/radiology/report/RadiologyReportServiceImpl.java
- api/src/main/java/org/openmrs/module/radiology/report/RadiologyReportValidator.java
- api/src/main/resources/RadiologyReport.hbm.xml
- api/src/test/java/org/openmrs/module/radiology/report/RadiologyReportServiceComponentTest.java
- api/src/test/java/org/openmrs/module/radiology/report/RadiologyReportTest.java
- api/src/test/java/org/openmrs/module/radiology/report/RadiologyReportValidatorTest.java
- omod/src/main/java/org/openmrs/module/radiology/report/web/RadiologyReportFormController.java
- omod/src/main/java/org/openmrs/module/radiology/report/web/resource/RadiologyReportResource.java
- omod/src/main/webapp/orders/radiologyReportSegment.jsp
- omod/src/main/webapp/portlets/radiologyReportsTab.jsp
- omod/src/main/webapp/reports/radiologyReportForm.jsp
- omod/src/test/java/org/openmrs/module/radiology/order/web/RadiologyOrderFormControllerTest.java
- omod/src/test/java/org/openmrs/module/radiology/report/web/RadiologyReportFormControllerTest.java
- omod/src/test/java/org/openmrs/module/radiology/report/web/resource/RadiologyReportResourceComponentTest.java
- omod/src/test/java/org/openmrs/module/radiology/report/web/resource/RadiologyReportResourceTest.java
- omod/src/test/java/org/openmrs/module/radiology/report/web/search/RadiologyReportSearchHandlerComponentTest.java
Rename RadiologyReport members
* radiologyReportId -> reportId
* reportDate -> date
* reportStatus -> status
* reportBody -> body
see https://issues.openmrs.org/browse/RAD-323
> RAD-323 Rename RadiologyReport members

- omod/src/main/resources/messages.properties
- omod/src/main/webapp/orders/radiologyOrderCreationSegment.jsp
- omod/src/main/webapp/portlets/radiologyOrdersTab.jsp
- omod/src/main/webapp/portlets/radiologyReportsTab.jsp
- omod/src/main/webapp/resources/css/radiology.css
* style input fields and buttons
* remove jquery-ui timepicker and add daterangepicker to select
scheduled ate
* customize top bar in daterangepickers
* remove bug in scheduled date utc adjustment
> Style radiologyOrderCreationSegment

- omod/src/main/java/org/openmrs/module/radiology/report/web/RadiologyReportFormController.java
- omod/src/main/webapp/reports/radiologyReportForm.jsp
- omod/src/test/java/org/openmrs/module/radiology/report/web/RadiologyReportFormControllerTest.java
* add spring:bind tag to ensure date gets formatted
* prune time with moment.js
see https://issues.openmrs.org/browse/RAD-164
> RAD-164 Report completion date shows datetime

- omod/src/main/webapp/portlets/radiologyReportsTab.jsp
- omod/src/main/webapp/reports/radiologyReportForm.jsp
Show radiology order details in report form only when box header gets clicked
see https://issues.openmrs.org/browse/RAD-352
> RAD-352 Add accordion for radiology order details in report form

- acceptanceTest/resources/demo-data.sql
- api/src/main/java/org/openmrs/module/radiology/report/HibernateRadiologyReportDAO.java
- api/src/main/java/org/openmrs/module/radiology/report/RadiologyReport.java
- api/src/main/java/org/openmrs/module/radiology/report/RadiologyReportService.java
- api/src/main/java/org/openmrs/module/radiology/report/RadiologyReportStatus.java
- api/src/test/java/org/openmrs/module/radiology/report/RadiologyReportSearchCriteriaTest.java
- api/src/test/java/org/openmrs/module/radiology/report/RadiologyReportServiceComponentTest.java
- api/src/test/java/org/openmrs/module/radiology/report/RadiologyReportTest.java
- api/src/test/resources/org/openmrs/module/radiology/include/RadiologyReportServiceComponentTestDataset.xml
- omod/src/main/resources/messages.properties
- omod/src/main/webapp/orders/radiologyReportSegment.jsp
- omod/src/main/webapp/portlets/radiologyReportsTab.jsp
- omod/src/main/webapp/reports/radiologyReportForm.jsp
- omod/src/test/java/org/openmrs/module/radiology/order/web/RadiologyOrderFormControllerTest.java
- omod/src/test/java/org/openmrs/module/radiology/report/web/RadiologyReportFormControllerTest.java
- omod/src/test/java/org/openmrs/module/radiology/report/web/search/RadiologyReportSearchHandlerComponentTest.java
- omod/src/test/resources/RadiologyReportSearchHandlerComponentTestDataset.xml
* rename enum name CLAIMED to DRAFT
* merge status column with voided column in radiologyReportsTab
see https://issues.openmrs.org/browse/RAD-356
> RAD-356 Rename CLAIMED to DRAFT

- omod/src/main/java/org/openmrs/module/radiology/report/web/RadiologyReportFormController.java
- omod/src/main/resources/messages.properties
- omod/src/main/webapp/reports/radiologyReportForm.jsp
- omod/src/test/java/org/openmrs/module/radiology/report/web/RadiologyReportFormControllerTest.java
* redirect to report form after voiding instead of order form
* restructure message.property codes for report form
* show awesomefonts icons on reportform as well
* make sure user sees "Deleted" instead of voided
> Refine voiding in UI

- api/src/main/java/org/openmrs/module/radiology/report/RadiologyReportService.java
Fix javadoc of getActiveRadiologyReportByRadiologyOrder
> Fix javadoc of getActiveRadiologyReportByRadiologyOrder

- omod/src/main/webapp/orders/discontinuationOrderDisplaySegment.jsp
remove hyperlink to patient dashboard as we have a local header which already
provides this functionality. also the link was broken
> Fix discontinuation display segment jsp

- acceptanceTest/resources/demo-data.sql
- api/src/main/resources/RadiologyReport.hbm.xml
- api/src/main/resources/liquibase.xml
- omod/src/main/webapp/reports/radiologyReportForm.jsp
RadiologyReport changedBy dateChanged properties are missing in the db.
Foreign key constraint is missing for voided_by.
Simplify the radiologyReportForm.jsp using spring-form tags
see https://issues.openmrs.org/browse/RAD-362
> RAD-362 Add RadiologyReport changedBy dateChanged to db

- omod/src/main/java/org/openmrs/module/radiology/order/web/RadiologyOrderDetailsPortletController.java
- omod/src/main/java/org/openmrs/module/radiology/order/web/RadiologyOrdersTabPortletController.java
- omod/src/main/java/org/openmrs/module/radiology/report/web/RadiologyReportFormController.java
- omod/src/main/java/org/openmrs/module/radiology/report/web/RadiologyReportsTabPortletController.java
- omod/src/main/resources/messages.properties
- omod/src/main/webapp/orders/radiologyOrderDisplaySegment.jsp
- omod/src/main/webapp/portlets/radiologyOrderDetails.jsp
- omod/src/main/webapp/reports/radiologyReportForm.jsp
- omod/src/main/webapp/template/includeScripts.jsp
- omod/src/test/java/org/openmrs/module/radiology/order/web/RadiologyOrderDetailsPortletControllerTest.java
- omod/src/test/java/org/openmrs/module/radiology/order/web/RadiologyOrdersTabPortletControllerTest.java
- omod/src/test/java/org/openmrs/module/radiology/report/web/RadiologyReportFormControllerTest.java
- omod/src/test/java/org/openmrs/module/radiology/report/web/RadiologyReportsTabPortletControllerTest.java
* add RadiologyOrderDetailsPortletController.java
* override populateModel-method
* add radiology order details portlet
* add unit tests for RadiologyOrderDetailsPortletController.java
* add unit test for RadiologyOrdersTabPortletController.java
* add unit test for RadiologyReportsTabPortletController.java
see https://issues.openmrs.org/browse/RAD-352
> RAD-352 Provide radiology order details as a portlet

- api/src/main/java/org/openmrs/module/radiology/RadiologyConstants.java
Add javadocs to RadiologyConstants
> Add javadocs to RadiologyConstants

- api/src/main/java/org/openmrs/module/radiology/RadiologyProperties.java
- api/src/main/java/org/openmrs/module/radiology/dicom/DicomUidValidator.java
- omod/src/main/java/org/openmrs/module/radiology/order/web/search/RadiologyOrderSearchHandler.java
- omod/src/main/java/org/openmrs/module/radiology/report/web/search/RadiologyReportSearchHandler.java
instead of commons.lang
* also fix some javadoc ref in SearchHandler's
> Use apache commons lang3

- omod/pom.xml
see https://issues.openmrs.org/browse/RAD-270
> RAD-270 Remove test goal from jasmine-maven-plugin to fix build

- omod/src/main/webapp/radiologyDashboardOrdersTab.jsp
- omod/src/main/webapp/radiologyDashboardReportTemplatesTab.jsp
- omod/src/main/webapp/radiologyDashboardReportsTab.jsp
* put focus on first filter when loading page
* reload datatables by pressing enter on filter fields
* disable include deleted checkbox if status completed is selected in
reports tab
> Add features to filter fields

- omod/src/main/webapp/orders/radiologyOrderCreationSegment.jsp
- omod/src/main/webapp/orders/radiologyOrderDiscontinuationSegment.jsp
- omod/src/main/webapp/reports/radiologyReportForm.jsp
* add * to required input fields in radiologyOrderCreationSegment.jsp, radiologyOrderDiscontinuationSegment.jsp and radiologyReportForm.jsp
* also disable diagnosis textarea if report is voided
> Add * to all required input fields

- omod/src/main/webapp/portlets/radiologyOrderDetails.jsp
- omod/src/main/webapp/reports/radiologyReportForm.jsp
* add box header and box to radiologyOrderDetails.jsp
* add accordion to radiologyOrderDetails.jsp if withAccordion parameter
is set
see https://issues.openmrs.org/browse/RAD-352
> RAD-352 Add accordion option to radiologyOrderDetails portlet

- omod/src/main/webapp/orders/radiologyOrderCreationSegment.jsp
* add patient header to radiologyOrderCreationSegment.jsp if patient
is set
> Add patient header to order form if patient is selected

- omod/src/main/resources/messages.properties
- omod/src/main/webapp/radiologyDashboardOrdersTab.jsp
- omod/src/main/webapp/radiologyDashboardReportTemplatesTab.jsp
- omod/src/main/webapp/radiologyDashboardReportsTab.jsp
- omod/src/main/webapp/resources/scripts/radiology.js
* store filter values in session storage on each filter request
* fetch filter values from session storage on page load
* add method to show alert dialog to radiology.js
* add new entries to message.properties for error dialog
* log error and show alert dialog if an error occured while fetching data from rest
> Remember filter values and show dialog on rest error

- pom.xml
update to latest release of maven mycila license plugin (3.0)
> Update maven license plugin to 3.0

- omod/src/main/docker/Dockerfile
- pom.xml
* update dependency to legacyui release of 1.0
* update legacyui in Dockerfile
> Update legacyui to 1.0

- api/pom.xml
- omod/pom.xml
- pom.xml
Adjust module version to semver style
MAJOR.MINOR.PATCH-optional
see http://semver.org/
> Adjust module version to semver style

- omod/src/main/webapp/orders/radiologyOrderCreationSegment.jsp
* add disabled input field if patient is set in
radiologyOrderCreationSegment.jsp
> Disable patient input if patient is set in order form

- omod/pom.xml
* remove filtering in webapp directory in omod pom.xml
> Remove filtering in webapp directory

- omod/src/main/webapp/orders/radiologyOrderCreationSegment.jsp
> Set focus to first input on radiologyOrderCreationForm

- api/src/main/java/org/openmrs/module/radiology/RadiologyPrivileges.java
- api/src/main/java/org/openmrs/module/radiology/modality/HibernateRadiologyReportDAO.java
- api/src/main/java/org/openmrs/module/radiology/modality/RadiologyModality.java
- api/src/main/java/org/openmrs/module/radiology/modality/RadiologyModalityDAO.java
- api/src/main/java/org/openmrs/module/radiology/modality/RadiologyModalityEditor.java
- api/src/main/java/org/openmrs/module/radiology/modality/RadiologyModalityService.java
- api/src/main/java/org/openmrs/module/radiology/modality/RadiologyModalityServiceImpl.java
- api/src/main/java/org/openmrs/module/radiology/modality/RadiologyModalityValidator.java
- api/src/main/resources/RadiologyModality.hbm.xml
- api/src/main/resources/liquibase.xml
- api/src/main/resources/moduleApplicationContext.xml
- api/src/test/java/org/openmrs/module/radiology/modality/RadiologyModalityEditorComponentTest.java
- api/src/test/java/org/openmrs/module/radiology/modality/RadiologyModalityServiceComponentTest.java
- api/src/test/java/org/openmrs/module/radiology/modality/RadiologyModalityValidatorTest.java
- api/src/test/resources/org/openmrs/module/radiology/include/RadiologyModalityServiceComponentTestDataset.xml
- api/src/test/resources/test-hibernate.cfg.xml
- omod/src/main/java/org/openmrs/module/radiology/modality/web/RadiologyModalityFormController.java
- omod/src/main/resources/config.xml
- omod/src/main/resources/messages.properties
- omod/src/main/webapp/modalities/radiologyModalityCreationForm.jsp
- omod/src/main/webapp/modalities/radiologyModalityForm.jsp
- omod/src/test/java/org/openmrs/module/radiology/modality/web/RadiologyModalityFormControllerTest.java
- omod/src/test/resources/test-hibernate.cfg.xml
add entity RadiologyModality with DAO, service, view layers
* add RadiologyModality entity
* add DAO with Hibernate implementation
* add Service with implementation
* add Validator
* add PropertyEditor
* add Controller
* add jsp for creation/display
see https://issues.openmrs.org/browse/RAD-366
> RAD-366 Add RadiologyModality

- omod/src/test/java/org/openmrs/module/radiology/modality/web/RadiologyModalityFormControllerTest.java
- omod/src/test/java/org/openmrs/module/radiology/order/web/RadiologyOrderFormControllerTest.java
- omod/src/test/java/org/openmrs/module/radiology/report/web/RadiologyReportFormControllerTest.java
ensure expected service methods are called by the controllers
> Verify service method calls in controllers

- api/src/main/java/org/openmrs/module/radiology/modality/RadiologyModality.java
- api/src/main/java/org/openmrs/module/radiology/modality/RadiologyModalityService.java
- api/src/main/java/org/openmrs/module/radiology/modality/RadiologyModalityValidator.java
- api/src/main/resources/RadiologyModality.hbm.xml
- api/src/main/resources/liquibase.xml
- api/src/test/java/org/openmrs/module/radiology/modality/RadiologyModalityServiceComponentTest.java
- api/src/test/java/org/openmrs/module/radiology/modality/RadiologyModalityValidatorTest.java
- api/src/test/resources/org/openmrs/module/radiology/include/RadiologyModalityServiceComponentTestDataset.xml
- omod/src/main/webapp/modalities/radiologyModalityCreationForm.jsp
- omod/src/main/webapp/modalities/radiologyModalityForm.jsp
- omod/src/test/java/org/openmrs/module/radiology/modality/web/RadiologyModalityFormControllerTest.java
- omod/src/test/java/org/openmrs/module/radiology/order/web/RadiologyOrderFormControllerTest.java
- omod/src/test/java/org/openmrs/module/radiology/report/web/RadiologyReportFormControllerTest.java
turn RadiologyModality into OpenmrsMetadata inheriting BaseOpenmrsMetadata
* add db columns
* add validation and improve ae title validation via core message property
see https://issues.openmrs.org/browse/RAD-369
> RAD-369 Make RadiologyModality metadata

- api/src/test/java/org/openmrs/module/radiology/modality/RadiologyModalityServiceComponentTest.java
- omod/src/main/java/org/openmrs/module/radiology/modality/web/resource/RadiologyModalityResource.java
- omod/src/test/java/org/openmrs/module/radiology/modality/web/resource/RadiologyModalityResourceComponentTest.java
- omod/src/test/java/org/openmrs/module/radiology/modality/web/resource/RadiologyModalityResourceTest.java
- omod/src/test/resources/RadiologyModalityResourceComponentTestDataset.xml
* add RadiologyModalityResource
* allow get/save/update
see https://issues.openmrs.org/browse/RAD-368
> RAD-368 Expose Modality via REST

- omod/src/main/resources/messages.properties
- omod/src/main/webapp/reports/templates/mrrtReportTemplateForm.jsp
RAD-358 Show mrrt template attributes coding scheme and terms
* Showing template attribute schemes and terms on the template form
see https://issues.openmrs.org/browse/RAD-358
> RAD-358 Show mrrt template attributes coding scheme and terms

- omod/src/main/resources/messages.properties
- omod/src/main/webapp/reports/templates/mrrtReportTemplateForm.jsp
see https://issues.openmrs.org/browse/RAD-
show the reference term name instead of its version
as this speeks more to the user as just scheme and code
> RAD-358 Show terms name instead of version

- omod/src/main/java/org/openmrs/module/radiology/modality/web/resource/RadiologyModalityResource.java
- omod/src/test/java/org/openmrs/module/radiology/modality/web/resource/RadiologyModalityResourceTest.java
Enable retiring a modality via REST
see https://issues.openmrs.org/browse/RAD-372
> RAD-371 Enable retiring a modality via REST

- omod/src/main/java/org/openmrs/module/radiology/report/template/web/resource/MrrtReportTemplateResource.java
- omod/src/test/java/org/openmrs/module/radiology/report/template/web/resource/MrrtReportTemplateResourceComponentTest.java
- omod/src/test/java/org/openmrs/module/radiology/report/template/web/resource/MrrtReportTemplateResourceTest.java
RAD-358 Add terms to MrrtReportTemplateResource
Added template attribute terms to rest resource
see https://issues.openmrs.org/browse/RAD-358
> RAD-358 Add terms to MrrtReportTemplateResource

- api/src/main/java/org/openmrs/module/radiology/modality/HibernateRadiologyModalityDAO.java
- api/src/main/java/org/openmrs/module/radiology/modality/RadiologyModalityDAO.java
- api/src/main/java/org/openmrs/module/radiology/modality/RadiologyModalityService.java
- api/src/main/java/org/openmrs/module/radiology/modality/RadiologyModalityServiceImpl.java
- api/src/test/java/org/openmrs/module/radiology/modality/RadiologyModalityServiceComponentTest.java
- api/src/test/resources/org/openmrs/module/radiology/include/RadiologyModalityServiceComponentTestDataset.xml
- omod/src/main/java/org/openmrs/module/radiology/modality/web/resource/RadiologyModalityResource.java
- omod/src/test/java/org/openmrs/module/radiology/modality/web/resource/RadiologyModalityResourceComponentTest.java
- omod/src/test/resources/RadiologyModalityResourceComponentTestDataset.xml
* add RadiologyModalityService.getRadiologyModalities(includeRetired)
* implement doGetAll() in RadiologyModalityResource
see https://issues.openmrs.org/browse/RAD-372
> RAD-372 Get all modalities via REST

- acceptanceTest/resources/demo-data.sql
- api/src/main/resources/liquibase.xml
- docs/DEMO-DATA.md
- omod/src/main/java/org/openmrs/module/radiology/modality/web/RadiologyDashboardModalitiesTabController.java
- omod/src/main/resources/messages.properties
- omod/src/main/webapp/dashboardHeader.jsp
- omod/src/main/webapp/radiologyDashboardModalitiesTab.jsp
- omod/src/main/webapp/radiologyDashboardReportsTab.jsp
- omod/src/test/java/org/openmrs/module/radiology/modality/web/RadiologyDashboardModalitiesTabControllerTest.java
* add controller + jsp for modality tab
* add demo-data modalities
* add demo-data radiology admin role
* add privileges GET/MANAGE rad modalities via liquibase
see https://issues.openmrs.org/browse/RAD-373
> RAD-373 Add modalities tab to UI

- acceptanceTest/resources/demo-data.sql
- docs/IMPORT-RADLEX.md
* define hl7_code in IMPORT-RADLEX.md in docs
* remove the "Edit Concepts" from the radmin privileges
and add missing ones to enable admin to manage/purge concepts,
source and ref terms.
> Update IMPORT-RADLEX.md and demo privileges

- omod/src/main/docker/Dockerfile
- pom.xml
* update version to 1.1-SNAPSHOT to use fixes/new features
* udpate Dockerfile legacyui module to a specific 1.1-SNAPSHOT with timestamp
since SNAPSHOT only come with timestamps and not only the latest.
> Update legacyui to 1.1-SNAPSHOT

- acceptanceTest/resources/demo-data.sql
add privileges needed to add reference terms and see the concepts page
> Add privileges to radmin demo-user

- omod/src/main/docker/Dockerfile
- pom.xml
Update legacyui to 1.1
and webservices.rest to 1.6
in both pom and Dockerfile
> update lui and rest dependencies to latest releases

- README.md
legacui is already released, fix readme
> fix readme line about legacyui

- api/src/test/java/org/openmrs/module/radiology/report/template/MrrtReportTemplateValidatorComponentTest.java
Rename MrrtReportTemplateValidatorTest to ComponentTest since it is one
> Rename MrrtReportTemplateValidatorTest to ComponentTest

- omod/src/main/webapp/orders/radiologyOrderForm.jsp
legacyui 1.1 has new feature of hasPrivilege hasAll attribute
which makes the user require all privileges in the privilege list
* use it to clean up radiologyOrderForm.jsp
> Use hasPrivilege hasAll in orderForm jsp

- api/src/main/java/org/openmrs/module/radiology/report/template/MrrtReportTemplateValidator.java
- api/src/main/java/org/openmrs/module/radiology/report/template/XsdMrrtReportTemplateValidator.java
- api/src/test/java/org/openmrs/module/radiology/report/template/MrrtReportTemplateValidatorComponentTest.java
- api/src/test/resources/mrrttemplates/ihe/connectathon/2015/invalidMrrtReportTemplate-missingCharsetTitleTemplateAttributesBodyElements.html
RAD-359 Get all error messages
Instead of failing on the first violation, the code now adds all violoations into an errors object and throws exception with all errors
see https://issues.openmrs.org/browse/RAD-359
> RAD-359 Get all error messages

- omod/src/main/docker/Dockerfile
- pom.xml
fixes issue "Cannot create a session after response has been
commited" on logout
> Update legacyui to 1.2

- README.md
Update readme link to legacyui extraction issue
> Update readme link to legacyui extraction issue

- api/src/main/java/org/openmrs/module/radiology/report/template/XsdMrrtReportTemplateValidator.java
RAD-359 follow up commit to clean up error messages displayed## Description
> RAD-359 follow up commit to clean up error messages displayed

- pom.xml
* update maven docker plugin to 0.16.7
* delete maven property formerlyused for the spotify plugin
> Update maven docker plugin to 0.16.7

- acceptanceTest/resources/demo-data.sql
add privilege for radiologists to delete mrrt templates
see https://issues.openmrs.org/browse/RAD-351
> RAD-351 Add missing demo-data privilege

- api/src/main/java/org/openmrs/module/radiology/report/template/HibernateMrrtReportTemplateDAO.java
- api/src/main/java/org/openmrs/module/radiology/report/template/MrrtReportTemplateSearchCriteria.java
- api/src/main/java/org/openmrs/module/radiology/report/template/MrrtReportTemplateService.java
- api/src/test/java/org/openmrs/module/radiology/report/template/MrrtReportTemplateSearchCriteriaTest.java
- api/src/test/java/org/openmrs/module/radiology/report/template/MrrtReportTemplateServiceComponentTest.java
- api/src/test/resources/org/openmrs/module/radiology/include/MrrtReportTemplateServiceComponentTestDataset.xml
- omod/src/main/java/org/openmrs/module/radiology/report/template/web/search/MrrtReportTemplateSearchHandler.java
- omod/src/test/java/org/openmrs/module/radiology/report/template/web/search/MrrtReportTemplateSearchHandlerComponentTest.java
- omod/src/test/java/org/openmrs/module/radiology/report/template/web/search/MrrtReportTemplateSearchHandlerTest.java
- omod/src/test/resources/MrrtReportTemplateSearchHandlerComponentTestDataset.xml
RAD-376 Search by report template publisher
Added publisher to search criteria
Modify getMrrtReportTemplates to query by publisher 
Updated REST seach handler to query by publisher
Unit test all changes
see https://issues.openmrs.org/browse/RAD-376
> RAD-376 Search by report template publisher

- api/src/test/java/org/openmrs/module/radiology/report/template/MrrtReportTemplateServiceComponentTest.java
adapt test for getMrrtReportTemplates by the publisher string to test
if the returned templates publisher string matches/partially matches
the publisher defined in the search criteria
see https://issues.openmrs.org/browse/RAD-376
> RAD-376 Adapt test for getting publisher

- api/src/main/java/org/openmrs/module/radiology/report/template/MrrtReportTemplateService.java
- api/src/test/java/org/openmrs/module/radiology/report/template/MrrtReportTemplateServiceComponentTest.java
remove duplicate test of getMrrtReportTemplate(Integer)
the test should ensure we get the template with given id
testing if the template contains the reference terms is done
on importing templates and doesnt need to be done here again
> Remove duplicate test of getMrrtReportTemplate

- omod/gulpfile.js
- omod/package.json
- omod/pom.xml
- add development maven profile to omod pom.xml
- add dev-task and tasks with creation of sourcemaps of js and css files
to gulpfile.js
see https://issues.openmrs.org/browse/RAD-387
> RAD-387 Add sourcemaps for more comfortable frontend development

- api/src/test/java/org/openmrs/module/radiology/order/RadiologyOrderServiceComponentTest.java
- api/src/test/java/org/openmrs/module/radiology/order/RadiologyOrderServiceTest.java
Created unit tests for RadiologyOrderServiceImpl and removed unnecessary integration tests.
see https://issues.openmrs.org/browse/RAD-381
> RAD-381 Create RadiologyOrderServiceTest

- README.md
the travis ci badge is blurry since its a png,
made it an svg
see https://issues.openmrs.org/browse/RAD-
> make travis ci badge svg in readme

- docs/DOCKER.md
Fixed syntax issue on line 97, plus some minor formatting proposals
On line, fixed a typo. And some certain words changed format
see https://issues.openmrs.org/browse/RAD-
> Syntax issue on line 97
